### ISSUE TITLE
[2.0 Beta] ]Youtube Music - Generic playlists overridden in case of multiple accounts

### ISSUE THREAD

**Issue by Aasikki** [music-assistant/hass-music-assistant#1126]
### What version of Music Assistant has the issue?

2.0.0b1

### The problem

I added my and my so's yt music accounts as individual providers, but it has resulted into some weirdness.
~Only the first one I added is visible in the "browse" -section and~ the latter one seems to have overridden playlists with same names from the first one. E.g. there now is only one "Your Likes" -playlist and it only contains the songs of the account I added after the first one.

Not sure if the same extends to other providers like spotify.

### How to reproduce

Add more than one ytmusic provider.

### What version of Home Assistant Core are your running

2023.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Hmm, this is more like a feature request to split out the auto generated playlists ?
I think this is caused by the fact that Youtube has to unique identifiers on many places, unlike all other providers.
So this issue is YTM specific.

Browse section is not yet ready, see the backlog: https://github.com/orgs/music-assistant/projects/2/views/1

How can I reproduce this ? Multiple brand accounts ?

**Comment by Aasikki** [comment]
> 

Multiple brand accounts could work, not sure, we have ytmusic family plan, so they are two completey different google accounts.

**Comment by Aasikki** [comment]
Also now noticed that playback doesn't work at all with ytmusic, added spotify provider to test and with that it works fine.

**Comment by marcelveldt** [comment]
> Also now noticed that playback doesn't work at all with ytmusic, added spotify provider to test and with that it works fine.

Track progress for that issue here:
https://github.com/orgs/music-assistant/projects/2/views/1?pane=issue&itemId=22655199

**Comment by marcelveldt** [comment]
beta 10 should fix this issue but I could not test it as there no longer seem to exist a "Your likes" playlist, at least I couldn't find it on my YTM test account.

**Comment by Aasikki** [comment]
> beta 10 should fix this issue

Seems to work partially, but I still can't seem get two likes playlists shown under "playlists". When I go through browse, I can see that they now have differrent names under them though, "ytmusic" and "ytmusic2". Under playlists view I only get the ytmusic2 one.

> but I could not test it as there no longer seem to exist a "Your likes" playlist, at least I couldn't find it on my YTM test account

Have you liked any songs, maybe the list doesn't get generated until you do? Our accounts still definitely have them.

**Comment by marcelveldt** [comment]
I can't reproduce this one in other streaming providers and I can't seem to enable the generic playlists on my YT Music test account. @MarvinSchenkel can you have a look at this ?

**Comment by Aasikki** [comment]
> I can't reproduce this one in other streaming providers and I can't seem to enable the generic playlists on my YT Music test account. @MarvinSchenkel can you have a look at this ?

If there's any way I can help, by providing logs et.c let know!

**Comment by MarvinSchenkel** [comment]
I will have a look and see if I can reproduce this issue on my setup. Will let you know if I need any more help.

**Comment by OzGav** [comment]
Any updates on this one team?

**Comment by MarvinSchenkel** [comment]
Fixed in the next beta (31).

So Youtube Music assigns the very 'unique' id of "LM" to a likes playlist. Made sure this is unique across multiple users:
![image](https://github.com/music-assistant/hass-music-assistant/assets/17671719/d8e09d10-9bd2-45e7-a463-59989591060b)

Please verify when beta 31 is released!

**Comment by Aasikki** [comment]
Ah, I forgot to update here, as I was talking about it on the discord with @MarvinSchenkel. I can confirm it's definitely fixed when it comes to the likes playlist, but the other default playlists like "My Supermix" still has that problem.

**Comment by Aasikki** [comment]
All playlists now work correctly for me!
