### ISSUE TITLE
Last track in the queue doesn’t move to played items

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1153]
### What version of Music Assistant has the issue?

2 beta 9

### The problem

When’s playlist finishes,  the last track in the queue doesn’t move to played items (remains in next items)

### How to reproduce

Schedule a number of tracks and play the queue 

### Relevant log output

None

### Additional information

The last seconds of the last track in the queue:
https://user-images.githubusercontent.com/4363599/226190508-00c10f7b-1a02-4c3f-a4fa-8aad66032604.MOV

### What version of Home Assistant Core are your running

2023.3.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by erkr** [comment]
Update : still the case for b12

**Comment by erkr** [comment]
The original issue definitely is not fixed yet

**Comment by marcelveldt** [comment]
fixed in beta25

**Comment by erkr** [comment]
Yes, it is Thanks!

**Comment by erkr** [comment]
Saw the same error again in B27

**Comment by erkr** [comment]
Still in B29

**Comment by erkr** [comment]
Still the case in b30

**Comment by OzGav** [comment]
@erkr I just tried this by adding three songs to the queue and then playing them (I skipped each until about a minute to the end) out and the last song moved to the played items queue. Is this perhaps fixed?

**Comment by erkr** [comment]
Didn't test it recently, will do that

**Comment by OzGav** [comment]
Closing this one @erkr as I believe it has been fixed.

**Comment by erkr** [comment]
Tested with b58. Issue still persists. Last track doesn't move to played items. Recorded the last 5 seconds of the queue. Notice the player State changes, but the last track remains in play next:
https://github.com/music-assistant/hass-music-assistant/assets/4363599/422d98fc-1c7f-4242-b65f-d49833827505

**Comment by OzGav** [comment]
Just tested in b60 and this worked correctly for me. @erkr when you get a chance can you have another look?

**Comment by erkr** [comment]
Next week when I'm back from holiday 👍

**Comment by erkr** [comment]
Still the same issue in b62. I added 3 tracks to an initial empty queue. Last track remains in the queue

**Comment by OzGav** [comment]
OK I tried this with a Picoreplayer, Airplay and Chromecast. They all moved the last track out of the queue EXCEPT the Chromecast!

**Comment by marcelveldt** [comment]
Thanks for the detective work @OzGav that explains why I couldn't reproduce it.

**Comment by erkr** [comment]
Yeah finally fixed 👌
