### ISSUE TITLE
Warning with core 2023.7.0

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#1341]
### What version of Music Assistant has the issue?

Latest integration

### The problem

After upgrading to core 2023.7.0. , the mass integration triggered a warning

### How to reproduce

Update to latest core, having the integration installed

### Relevant log output

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:371 
First occurred: 23:09:17 (5 occurrences) 
Last logged: 23:09:17

Entity None (<class 'custom_components.mass.media_player.MassPlayer'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

### What version of Home Assistant Core are your running

2023.7.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Yes was reported in discord here https://discord.com/channels/753947050995089438/1098936700434124811/1123977134289993880 and Marcel said it would be fixed soon

I’ll add to the backlog just to make sure it is tracked

**Comment by tombloemker** [comment]
I'm not sure how this works, when it's fixed will I need to back out of this install? Will someone announce here that a solution was found?

**Comment by OzGav** [comment]
Not sure what you mean about backing out of the install. A subsequent beta will fix this. You can monitor the backlog to see when it is fixed.

**Comment by erkr** [comment]
Seems fixed with latest integration b1

**Comment by tombloemker** [comment]
Sweet, still getting same error. I assume I need to reinstall/download/tweak something? A brief explanation to send me in the right direction would be really appreciated.

**Comment by marcelveldt** [comment]
You need to enable the option in HACS that allows you to see beta updates.

**Comment by tombloemker** [comment]
> Seems fixed with latest integration b1

Yep, got it. Thanks for the patience. 

> You need to enable the option in HACS that allows you to see beta updates.
