### ISSUE TITLE
Search results don’t display correctly if entry is typed quickly

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1461]
### What version of Music Assistant has the issue?

2.0.0b70

### The problem

When typing in any search box if you type quickly results either don’t appear or appear incorrectly. Subsequent typing or removing a character results in the correct display 

### How to reproduce

As above

### What version of Home Assistant Core are your running

2023.8.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
I'm not sure if this one is resolved. I ran into it last week again.

**Comment by marcelveldt** [comment]
this one has been fixed today so will be in next beta

**Comment by gNeeUs** [comment]
From my experience, this issue is still present. In the Music Assistant main Search field ("Type here to search..."), when typing an entry fast (actually at my normal typing speed), all kinds of irrelevant results appear. Only when typing extremely slow do I obtain a reasonably limited and correct result of Tracks, Albums, and Artists. I am using Microsoft Edge browser on my computer. In the mobile app on my iPhone this does not happen and brings up correct search results, or I can't type fast enough :-)

Core 2024.8.1
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0
