### ISSUE TITLE
Queued songs randomly play twice in a row

### ISSUE THREAD

**Issue by bj61251** [music-assistant/hass-music-assistant#1554]
### What version of Music Assistant has the issue?

2023.6.0 BETA 3

### The problem

When I queue up a Deezer playlist to play on a Google speaker group, every few songs will play twice in a row. Usually the first song will play and end, and then the second song will start, but as soon as the second song ends it will start right back up and play a second time. Then the third song will play, and maybe the fourth, but then the next one will repeat twice as well. I'm not sure if this is unique to the speaker group or Deezer, but felt like it might be relevant information. 

### How to reproduce

Clear queue, click Deezer "Loved Tracks" playlist (the built in list of favorited songs), choose play, and then select a Google speaker group (Chromecast Audios and Google Home devices), and choose play now.

Usually the first song will play fine and move on to the second song, but when the second song ends it will repeat and play a second time. 

### Additional information

It's not consistent on exactly which songs will repeat, but it reliably happens for me every 3-5 songs, so it might take a bit to reproduce. 

### What version of Home Assistant Core are your running

2023.8.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
When the song repeats can you check the logs for any errors

**Comment by OzGav** [comment]
Actually I think this is related if not the same as another reported issue of chromecasts repeating tracks. For some reason I can find that issue right now so I’ll will add this to the backlog to track it.

**Comment by R0bin83** [comment]
I have exactly the same problem but with a combination of youtube music (Album) and sonos speakers. I thought i saw this issue already addressed in the development pipeline.

**Comment by LeeHanYeong** [comment]
When playing a playlist on YouTube Music, the same song is often repeated two or three times.

**Comment by dkvhin** [comment]
Same issue for me, when playing YouTube music playlist, same song repeats two or more times unless I manually click next button (then the same issue occurs again after 2 to 3 songs)

**Comment by OzGav** [comment]
It’s marked as a bug so will be looked at when there is time

**Comment by mareque** [comment]
> ### What version of Music Assistant has the issue?
> 2023.6.0 BETA 3
> 
> ### The problem


Same issue here, YT Music premium and Chromecast/GH flavor of players. 
Noticed more frequent occurences on tracks that have a) huge amount of text b) non-EN, diacritical characters, in name/artis/title. I'm using native automations to launch playlist playback (https://www.youtube.com/watch?v=eOC0CTaydUk). Hard to wkaround, as no controls are displayed when launching playback this way neither on MASS nor on GH Android app. However, what seems to work is voice command series on the player w/ Google Assistant: Hey G, pause, Hey G, resume, Hey G, next. The chain of commands may IMO add on to this issue, but I bet this is the most frequent way people are using playlist playback.

**Comment by mareque** [comment]
> When the song repeats can you check the logs for any errors

The log does not show any errors - last entry logged is playlist playback start, while the 'repeating' happens I think 'above' the MASS (in my case GH player infrastructure)

**Comment by OzGav** [comment]
Can we have some followup on this issue. I am trying to reproduce on beta 74 without luck. If you can reproduce it then change the logging for the player to debug and capture everything over the period of duplicated playback.

**Comment by OzGav** [comment]
@MarvinSchenkel I don’t see any issues in the upstream library related to this. Thoughts?

**Comment by dkvhin** [comment]
I turned on "Queue Flow Mode" for players, no more repeat songs (not the proper fix, but this works for me since I automate my music everyday)

**Comment by OzGav** [comment]
Thanks. We will keep this open for a little while so that it gets properly reviewed.

**Comment by Mace404** [comment]
I also have this with Youtube radio mode and Chromecast players, but only when flow mode is disabled.

**Comment by OzGav** [comment]
@marcelveldt I think I captured the logs for a repeating song. Looking at the timestamps in the attached log excerpt, at about 18:28:38 the song starts the first time and then I think at 18:35:26 the song started again. The song is Paradise City which goes for 6mins 45secs. The previous song was Message in a Bottle. I paused the song not long after it started the second time.
[MA_log.txt](https://github.com/music-assistant/hass-music-assistant/files/13265559/MA_log.txt)

**Comment by EpicMount** [comment]
I came here to report that I have the same issue, even with flow mode disabled. I checked the logs and I don't see anything related to playback,

**Comment by patrick1792** [comment]
I have the same issue with chromecast player and different types of playlists (spotify, filesystem remote share)

**Comment by OzGav** [comment]
Possible temporary workaround - Enable REPEAT ALL. Let us know if that works

**Comment by EpicMount** [comment]
> Possible temporary workaround - Enable REPEAT ALL. Let us know if that works

I tried this and it didn't work.

**Comment by OzGav** [comment]
Ok thanks. A proper fix is being worked on.

**Comment by patrick1792** [comment]
I have updated to 2.0.0b75, still it is not working:
* Queue Flow Mode off: The next song from the playlist is not started automatically (new problem)
* Queue Flow Mode on: I had still a song playing twice

I am using a chromecast player

**Comment by OzGav** [comment]
Check if you are using b75 as last time I checked that hasn’t been released yet? But as I type this I think it may have been.

**Comment by OzGav** [comment]
This should be fixed in beta 75. Let us know if not.

**Comment by OzGav** [comment]
You need to open a new issue with more details about your setup. We aren’t getting a flood of reports about playlists not playing. Please review the troubleshooting FAQ as well.

**Comment by Mace404** [comment]
Just tried with b75. Still having the same issue.
No errors in log.

I had the 4th and 5th track being the same on a radio started on a track basis. 
When the duplicate started as the 5th there was no entry in the played/recent tracks of the 4th. (so only the first 3 songs were listed)
Played on a chromecast device.

**Comment by OzGav** [comment]
Thanks everyone. This will get looked at again.

**Comment by Mace404** [comment]
> Just tried with b75. Still having the same issue. No errors in log.
> 
> I had the 4th and 5th track being the same on a radio started on a track basis. When the duplicate started as the 5th there was no entry in the played/recent tracks of the 4th. (so only the first 3 songs were listed) Played on a chromecast device.

Kept it running and just had another duplicate at track 15. Again no entry in the last played from the duplicate when it restarted.
Interval is lower since previously it repeated every 3 or 4 tracks.

**Comment by bj61251** [comment]
Yeah, I also updated to the new version and tested it again, and the issue is still there. It did seem to be less frequent, but it's difficult to confirm since it has always been intermittent. Same thing with the logs, I see nothing to indicate any errors. This was mostly playing from a Deezer playlist and casting to a Chromecast speaker group. I will also try from Plex soon to see if that has any effect on it.

**Comment by bj61251** [comment]
Just saw this error message today right around the time a song repeated on Plex ( this one actually played three times in a row, which I don't ever think has happened before for me):

AssertionError[0m
[31m2023-11-17 07:59:56.093 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57106' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m
[31m2023-11-17 07:59:56.531 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57113' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m
[31m2023-11-17 07:59:57.274 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57122' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m
[31m2023-11-17 07:59:57.406 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57125' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m
[31m2023-11-17 07:59:57.702 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57128' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m
[31m2023-11-17 07:59:57.975 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57135' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m
[31m2023-11-17 07:59:58.466 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57142' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m
[31m2023-11-17 07:59:58.676 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57145' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m
[31m2023-11-17 07:59:59.542 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-57149' coro=<TracksController.add_item_to_library() done, defined at /usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py:122> exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 163, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 172, in get_track_metadata
    assert isinstance(track_artist, Artist)
AssertionError[0m

**Comment by guussprokkereef** [comment]
Having the same issue here: using version 2.0.0b75 on RB Pi 4 8GB with HA 2023.11.3 and Chromecast playing music from the local file system on an external USB SSD.
I noticed that when I disable the "queue flow mode" MA stops frequently playing when a song ends. |When you click play, the same song starts playing again. 
When the "queue flow mode" is enabled. The music continues to play, but the same song is sometimes played twice. In rare cases MA stops playing when in "queue flow mode".

**Comment by michaeldufour** [comment]
Same issue with YTM provider and Chromecast group speaker

**Comment by OzGav** [comment]
This should be fixed in beta 83 please advise if not

**Comment by patrick1792** [comment]
Unfortunately the issue is still there.. Please advise if you need more information or logs

**Comment by elchininet** [comment]
[As I reported here](https://github.com/music-assistant/hass-music-assistant/issues/1657#issuecomment-1902619981) my previous issue is solved, but this started to happen randomly with some discs, every song in the list is played twice in a row.

Player: Google Nest Music / Google Nest Mini
Provider: local

**Comment by OzGav** [comment]
@elchininet open a new issue please with some more detail about how you are starting  automation or via the UI. What “list” are you referring to, the queue? Are you using speakers in a group?

**Comment by michaeldufour** [comment]
> This should be fixed in beta 83 please advise if not

Issue still there
YTM Provider with Chromecast, no error in the log

**Comment by OzGav** [comment]
@michaeldufour please open a new issue with YouTube in the title
