### ISSUE TITLE
Stops after one Song

### ISSUE THREAD

**Issue by Thomas-Caffin-Sune** [music-assistant/hass-music-assistant#1657]
### What version of Music Assistant has the issue?

2.0.0b75

### The problem

Music assistant stops after one Song

### How to reproduce

Using a google chromecast ultra just playing any songs/playlists after one Song it just stops

### Relevant log output

I could not find anything useful in the log output

### Additional information

2.0.0b74 did not have this problem

### What version of Home Assistant Core are your running

2023.11.3

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
What music provider are you using?

**Comment by Thomas-Caffin-Sune** [comment]
I've had this Problem with YT Music and soundcloud and I think with local files aswell

**Comment by steelbrothers** [comment]
Same problem with Playlist Spotify. Any list of songs stops after one song.

**Comment by OzGav** [comment]
Does it play to the exact end of the song or at a random point during the track?

**Comment by silverbladeg** [comment]
+1 same issue, playlist stops after the first song is played (first song on shuffle or regular press playlist behavior). I'm using YT Music, HAOS, latest beta. 

Player is airplay. 

Im adding a couple other things I've noticed, which I can start another issue thread on if deemed required. 

there's a noticeable delay when starting to play (initial play request). Scrubbing timeline on a track is either non responsive or very lagged. Volume control slider is lagged and sometimes doesn't display where on the slider it is correctly (will show the last position it was in). 

P.S: just started using the addon and it's already my favorite thing about HA, keep up the great work!

**Comment by jsv93** [comment]
+1 for the same issue here using 2 Google Nest Minis. However adding my experiences. 

Restarting MA occasionally fixes the issue temporarily, as does rebooting the Nest Mini. Eventually the system falls back to the same condition of only playing one track. Additionally this eventually results in the play command having no affect at all. The player shows the pause symbol for a split second then returns to idle. Unsure if this is a related issue though.

**Comment by piertjep** [comment]
Same problem. After exactly one song in the end. Using it with youtube music

**Comment by emile-bodin** [comment]
+1 
- nest mini's (does not matter which one)
- Sonos playbase
- MASS 2.0.0b77 (previous versions had the same issue)

When starting playlist from spotify it stops after 1 song, BUT there are playlists that do work.....

**Comment by SiboutVanLoo** [comment]
jup, same here, 1 song, big playlist, smal playlist, 1 song is all you get.
Could be lack of power, running on a RP4 that, well, has a ton running for its size...
But, pressing next starts the next song with just a small delay, so i'm guessing it has nothing to do with that. :-)

**Comment by OzGav** [comment]
This is a open issue related to others. It will get looked at in due course.

**Comment by Dunkelschunkel** [comment]
Thank you

**Comment by reganerasmus** [comment]
> This is a open issue related to others. It will get looked at in due course.

I thought i was the only one with this issue, funny enough it only started over the weekend, but not being able toplay more than one song of a playlist is really baffling, hope you guys fix this soon

**Comment by OzGav** [comment]
Can everyone that responded to this issue thumbs up this comment if you are using a universal group and thumbs down it if not. We are trying to work out if that is the problem.

**Comment by emile-bodin** [comment]
> Can everyone that responded to this issue thumbs up this comment if you are using a universal group and thumbs down it if not. We are trying to work out if that is the problem.

I have it configured but I don't use the group.

**Comment by Dunkelschunkel** [comment]
Playlist only gets filled with one song when playing an album from Spotify

**Comment by OzGav** [comment]
> Playlist only gets filled with one song when playing an album from Spotify

This is a separate problem then

**Comment by emile-bodin** [comment]
Some log files on a working and non working playlist, the same playlist(s) always fails. Same goes for a working one.
Global debug enabled

**non working playlist**
```
[36m2023-12-13 10:16:01.936 DEBUG (MainThread) [music_assistant.audio] Using cached streamdetails for spotify://track/4GhtDORJiSRYxj6M1bv0vX[0m
[36m2023-12-13 10:16:01.936 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem spotify://track/4GhtDORJiSRYxj6M1bv0vX to Deesie[0m
[36m2023-12-13 10:16:01.950 DEBUG (MainThread) [music_assistant.audio] start media stream for: spotify://track/4GhtDORJiSRYxj6M1bv0vX[0m
[36m2023-12-13 10:16:01.952 DEBUG (MainThread) [music_assistant.audio] writer started for spotify://track/4GhtDORJiSRYxj6M1bv0vX[0m
[36m2023-12-13 10:16:02.123 DEBUG (MainThread) [music_assistant.audio] writer finished for spotify://track/4GhtDORJiSRYxj6M1bv0vX[0m
[36m2023-12-13 10:16:02.290 DEBUG (MainThread) [music_assistant.audio] stripped 3.7 seconds of silence from end of pcm audio. bytes stripped: 653116[0m
[36m2023-12-13 10:16:02.290 DEBUG (MainThread) [music_assistant.audio] finished media stream for: spotify://track/4GhtDORJiSRYxj6M1bv0vX[0m
[36m2023-12-13 10:16:02.763 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:16:02.765 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:16:02.766 DEBUG (MainThread) [music_assistant.event] player_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:16:02.809 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:16:02.825 DEBUG (MainThread) [music_assistant.audio] writer finished for spotify://track/4GhtDORJiSRYxj6M1bv0vX[0m
[36m2023-12-13 10:16:03.077 DEBUG (MainThread) [music_assistant.audio] stripped 0.96 seconds of silence from end of pcm audio. bytes stripped: 169760[0m
[36m2023-12-13 10:16:03.077 DEBUG (MainThread) [music_assistant.audio] finished media stream for: spotify://track/4GhtDORJiSRYxj6M1bv0vX[0m
[flac @ 0x557539abcac0] unable to rewrite FLAC header.
[36m2023-12-13 10:16:03.760 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:16:03.761 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:16:03.783 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:16:07.797 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:16:12.307 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:16:17.820 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m

## end of song and playlist stops playing

[36m2023-12-13 10:16:22.885 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received cast status - app_id: CC1AD845 - volume: 0.20000000298023224[0m
[36m2023-12-13 10:16:22.892 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: IDLE[0m
[36m2023-12-13 10:16:22.896 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:16:22.900 DEBUG (MainThread) [music_assistant.event] player_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:16:24.093 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-15) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={ServiceInfo(type='mdns', data='Google-Nest-Mini-28149d95709754121cd663d4d1043762._googlecast._tcp.local.'), ServiceInfo(type='host', data=('192.168.87.38', 8009))}, uuid=UUID('28149d95-7097-5412-1cd6-63d4d1043762'), model_name='Google Nest Mini', friendly_name='Deesie', host='192.168.87.38', port=8009, cast_type='audio', manufacturer='Google Inc.')[0m
```

**Working** playlist
```
[36m2023-12-13 10:20:59.597 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:06.158 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/artists/3TPeQMiM9oABYCs59cAP4q took 0.08 seconds[0m
[36m2023-12-13 10:21:06.316 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/artists/3TPeQMiM9oABYCs59cAP4q/albums?include_groups=album,single,compilation took 0.09 seconds[0m
[36m2023-12-13 10:21:06.388 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/artists/3TPeQMiM9oABYCs59cAP4q took 0.06 seconds[0m
[36m2023-12-13 10:21:06.441 DEBUG (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Jim DeMain
 - using lookup-album(s): none
 - using lookup-track(s): Hungry Eyes/Hungry Eyes
[0m
[36m2023-12-13 10:21:06.530 DEBUG (MainThread) [music_assistant.music.artist] updated Jim DeMain in database: 268[0m
[36m2023-12-13 10:21:06.533 DEBUG (MainThread) [music_assistant.event] media_item_updated library://artist/268[0m
[36m2023-12-13 10:21:06.537 DEBUG (MainThread) [music_assistant.event] media_item_added library://artist/268[0m
[36m2023-12-13 10:21:09.621 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:19.651 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:24.126 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:29.827 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:29.923 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/2Q01M0X7yJeLfGg4ebLORO took 0.08 seconds[0m
[36m2023-12-13 10:21:30.483 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:30.485 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:30.515 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:21:30.618 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/0uCGho2Tyzcq3vTKerkWiQ took 0.05 seconds[0m
[36m2023-12-13 10:21:30.812 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:30.858 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:21:31.159 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:31.343 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/6wFXD2RWM5THayMLrNmyqw took 0.17 seconds[0m
[36m2023-12-13 10:21:31.814 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:31.845 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:21:31.875 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:31.944 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/4AQnXdOq7ChjMhibKrKne1 took 0.06 seconds[0m
[31m2023-12-13 10:21:32.000 ERROR (MainThread) [music_assistant] Exception in task Task-503 - target: <bound method TracksController.add_item_to_library of <music_assistant.server.controllers.media.tracks.TracksController object at 0x7f841cb70150>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 170, in get_track_metadata
    return self.__parse_track(adb_track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 242, in __parse_track
    metadata.lyrics = track_obj.get("strTrackLyrics")
                      ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'[0m
[36m2023-12-13 10:21:32.069 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/4AQnXdOq7ChjMhibKrKne1 took 0.07 seconds[0m
[36m2023-12-13 10:21:32.174 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/4AQnXdOq7ChjMhibKrKne1 took 0.07 seconds[0m
[31m2023-12-13 10:21:32.218 ERROR (MainThread) [music_assistant] Exception in task Task-506 - target: <bound method TracksController.add_item_to_library of <music_assistant.server.controllers.media.tracks.TracksController object at 0x7f841cb70150>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/media/tracks.py", line 132, in add_item_to_library
    await self.mass.metadata.get_track_metadata(item)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/metadata.py", line 169, in get_track_metadata
    if metadata := await provider.get_track_metadata(track):
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 170, in get_track_metadata
    return self.__parse_track(adb_track)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/providers/theaudiodb/__init__.py", line 242, in __parse_track
    metadata.lyrics = track_obj.get("strTrackLyrics")
                      ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'[0m
[36m2023-12-13 10:21:32.746 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:32.748 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:32.790 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:21:32.908 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/2C2vSufLm1wLq2GjDH3iMh took 0.07 seconds[0m
[36m2023-12-13 10:21:33.448 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:33.449 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:33.473 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:21:33.504 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received cast status - app_id: CC1AD845 - volume: 0.20000000298023224[0m
[36m2023-12-13 10:21:33.508 DEBUG (MainThread) [music_assistant.streams] Got GET request to /28149d95-7097-5412-1cd6-63d4d1043762/single/a5465c2136614dc7890ff0ce2c8ebfba.flac from 192.168.86.64
headers: <CIMultiDictProxy('Host': '192.168.86.104:8096', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (X11; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.225 Safari/537.36 CrKey/1.56.500000 DeviceType/SmartSpeaker', 'Range': 'bytes=0-', 'Accept-Encoding': 'identity;q=1, *;q=0', 'Accept': '*/*', 'CAST-DEVICE-CAPABILITIES': '{"audio_assistant":true,"bluetooth_supported":true,"display_supported":false,"hi_res_audio_supported":false,"remote_control_input_supported":false,"touch_input_supported":false}', 'Accept-Language': 'nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7')>
[0m
[36m2023-12-13 10:21:33.508 DEBUG (MainThread) [music_assistant.audio] Using cached streamdetails for spotify://track/2Q01M0X7yJeLfGg4ebLORO[0m
[36m2023-12-13 10:21:33.508 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem spotify://track/2Q01M0X7yJeLfGg4ebLORO to Deesie[0m
[36m2023-12-13 10:21:33.521 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received cast status - app_id: CC1AD845 - volume: 0.20000000298023224[0m
[36m2023-12-13 10:21:33.521 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: IDLE[0m
[36m2023-12-13 10:21:33.524 DEBUG (MainThread) [music_assistant.audio] start media stream for: spotify://track/2Q01M0X7yJeLfGg4ebLORO[0m
[36m2023-12-13 10:21:33.527 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:33.529 DEBUG (MainThread) [music_assistant.event] player_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:33.534 DEBUG (MainThread) [music_assistant.audio] writer started for spotify://track/2Q01M0X7yJeLfGg4ebLORO[0m
[36m2023-12-13 10:21:33.573 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:21:33.677 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/tracks/4a30Pk6uuvHH8zPN4SoMlM took 0.07 seconds[0m
[36m2023-12-13 10:21:33.953 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:33.960 DEBUG (MainThread) [music_assistant.event] queue_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:33.966 DEBUG (MainThread) [music_assistant.event] player_updated 28149d95-7097-5412-1cd6-63d4d1043762[0m
[36m2023-12-13 10:21:34.000 DEBUG (MainThread) [music_assistant.webserver] [140205427171344] Handling command music/item_by_uri[0m
[36m2023-12-13 10:21:34.303 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:34.570 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-15) [music_assistant.providers.chromecast] Discovered new or updated chromecast CastInfo(services={ServiceInfo(type='mdns', data='Google-Nest-Mini-28149d95709754121cd663d4d1043762._googlecast._tcp.local.'), ServiceInfo(type='host', data=('192.168.87.38', 8009))}, uuid=UUID('28149d95-7097-5412-1cd6-63d4d1043762'), model_name='Google Nest Mini', friendly_name='Deesie', host='192.168.87.38', port=8009, cast_type='audio', manufacturer='Google Inc.')[0m
[36m2023-12-13 10:21:35.265 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:36.613 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/artists/57Qb0icZ6QjiyQHoEGdVyN took 0.07 seconds[0m
[36m2023-12-13 10:21:36.894 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/artists/57Qb0icZ6QjiyQHoEGdVyN/albums?include_groups=album,single,compilation took 0.23 seconds[0m
[36m2023-12-13 10:21:36.946 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/artists/57Qb0icZ6QjiyQHoEGdVyN took 0.05 seconds[0m
[36m2023-12-13 10:21:37.057 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/artists/57Qb0icZ6QjiyQHoEGdVyN took 0.05 seconds[0m
[36m2023-12-13 10:21:37.160 DEBUG (MainThread) [music_assistant.providers.spotify] Processing GET/artists/57Qb0icZ6QjiyQHoEGdVyN/top-tracks took 0.05 seconds[0m
[36m2023-12-13 10:21:37.161 DEBUG (MainThread) [music_assistant.metadata] Unable to get musicbrainz ID for artist Kay Black
 - using lookup-album(s): none
 - using lookup-track(s): none
[0m
[36m2023-12-13 10:21:37.259 DEBUG (MainThread) [music_assistant.music.artist] updated Kay Black in database: 653[0m
[36m2023-12-13 10:21:37.262 DEBUG (MainThread) [music_assistant.event] media_item_updated library://artist/653[0m
[36m2023-12-13 10:21:37.266 DEBUG (MainThread) [music_assistant.event] media_item_added library://artist/653[0m
[36m2023-12-13 10:21:39.843 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
[36m2023-12-13 10:21:49.870 DEBUG (Thread-17) [music_assistant.providers.chromecast.Deesie] Received media status update: PLAYING[0m
```

**Comment by foreverimagining** [comment]
> "enable queue flow mode" fixed my issue.

Funny thing, disabling this function just fixed this issue for me. I have many more issues that I may get back to looking into in the near future, but this is at least functional enough for my get-together tomorrow.

Updated to the b78 server today to see if it fixed any of the issues, including this one, that I had experienced on an earlier (I don't remember which) beta version of the server. It did not automatically fix anything.

**Comment by emile-bodin** [comment]
> Please redo the logs with debug logging DISABLED. It is just cluttering the issue.
> 
> edit! And are you using b78?

Yes 

small update.
On the non-working playlist, when I press the **blue play button** it plays 1 song.
When I right-klick the first song and select **play playlist from here** it works fine.

**Comment by OzGav** [comment]
@marcelveldt an interesting observation above

**Comment by jwaes** [comment]
For me the 'play from here' trick does not work ... it just stops after the first song. (youtubemusic)

**Comment by bj61251** [comment]
I'm also having this problem, playing on a Chromecast speaker group from Deezer and/or Plex sources.

**Comment by mocalv** [comment]
> > "enable queue flow mode" fixed my issue.
> 
> Funny thing, disabling this function just fixed this issue for me. 

Enabling fixed the problem for me 🤣

**Comment by SiboutVanLoo** [comment]
🤣😂

Op di 2 jan 2024 22:09 schreef mocalv ***@***.***>:

**Comment by TSK7M** [comment]
Hello,
I have the same problem. Only 1 title is played at a time and then the player stops.
All services are affected: Plex, Qobuz, YouTube. 
Therefore it took a long time for the stream to start.

**Comment by happosade** [comment]
Same issue, running container `ghcr.io/music-assistant/server` with latest as a server and plugged to home assistant with HACS integration version `2024.1.0b2`
Plays on Bose SoundTouch that turns the status light to amber (some error occurred) and source is YT Music.

**Comment by TSK7M** [comment]
[2.0.0 BETA 81] - 09.01.2024 --> Even in the version, the problem still exists.
music-assistant is currently not usable with Chromecast. It doesn't work and the problem hasn't been fixed.

**Comment by OzGav** [comment]
> [2.0.0 BETA 81] - 09.01.2024 --> the problem hasn't been fixed.

Yes we know.

**Comment by sewershagger** [comment]
I have the same issues when using Music Assistant to play Spotify playlist to any Chromecast speaker. Ends after the fist song. It started recently can't can't tell you which version because I did a bunch of updates in one go from an older version from several months ago.

**Comment by CalamarBicefalo** [comment]
Yes it definitely creeped in half way through the beta journey

**Comment by elchininet** [comment]
In my case it always happens with the providers that I have configured (local provider and Spotify provider). I am not using a universal group and enabling queue flow mode doesn‘t fix the issue and it doesn‘t matter if I instruct it to reproduce the entire disc.

**Comment by OzGav** [comment]
This should be fixed in beta 83 please advise if not

**Comment by elchininet** [comment]
I can confirm that after two tests the issue of playing just the first song is fixed (and before it was something that happened all the time). Now I am having a new issue but this should be addressed in a separated issue.

**Comment by PlantsThatsWhatsUp** [comment]
I still have this issue via Airplay + Plex despite running 83

**Comment by OzGav** [comment]
@PlantsThatsWhatsUp please open a new issue with more info. Has it ever worked? Looks like you are using YouTube. Do other providers work ok? While using YouTube have you tried a variety of songs to confirm every song fails to play with the same errors?

**Comment by OzGav** [comment]
Also there is a bug with Chromecast groups that will be fixed in the next beta

**Comment by rcluver** [comment]
Still an issue for me in the latest Beta, though now it stops after 2 songs

**Comment by OzGav** [comment]
Being tracked in a different issue and has been reproduced

**Comment by OzGav** [comment]
All related issues have been closed

**Comment by gaswirth** [comment]
I'm still having this issue. Lovely that all related issues have been closed, but can anyone provide any additional info from these other issue threads? This is so far the only promising lead I've got, and it just dead-ends here. Thanks in advance!

**Comment by OzGav** [comment]
You are not going to get any help in a closed thread. Go through the troubleshooting page in the docs, read the open and closed issues and if you are still stuck open your own issue with all of the requested information. The response you get will be commensurate with the effort you put in trying to solve this yourself.

**Comment by gaswirth** [comment]
Yes, I understand that, and how these things work. I didn't think it could hurt, as part of said effort to solve this myself, to check in here. Thanks.
