### ISSUE TITLE
v1.1.3: Cosmetics media panel

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#177]
When playing tracks with long titles, the player view in the mobile app is a little messed up:
![image](https://user-images.githubusercontent.com/4363599/168606752-8659d51b-c372-4a62-a98c-c31498ac30ae.jpeg)

I know. A very nitty gritty detail 😎

**Comment by marcelveldt** [comment]
It's fixing these little nitty gritty details that make a product "wow" instead of "okay" so keep reporting them, thanks!

**Comment by marcelveldt** [comment]
this should be fixed in version 1.1.5

**Comment by erkr** [comment]
On me mobile is still the same with 1.1.5:
![image](https://user-images.githubusercontent.com/4363599/169023399-9f1643f8-be35-4396-84c0-4c02908d8587.png)
Best
Eric

**Comment by marcelveldt** [comment]
Did you force refresh the app/browser?
Frontend updates tend to stick in the browser cache....
Easy way to see you'r eon latest frontend if there now is a "hamburger menu" at the home page on mobile because I've added that yesterday

**Comment by erkr** [comment]
Although I did a front end cache reset  in the mobile app, I do see the hamburger in the MA home page, but the glitch is still there.

**Comment by marcelveldt** [comment]
Changed it a tiny bit more. Can you check ?

**Comment by erkr** [comment]
Yes that tiny change fixed it:
![image](https://user-images.githubusercontent.com/4363599/169508255-70897208-9a3b-4e78-b184-22852c0ada61.jpeg)
