### ISSUE TITLE
the integration cant browse to albums

### ISSUE THREAD

**Issue by Bram-diederik** [music-assistant/hass-music-assistant#1802]
### What version of Music Assistant has the issue?

2023.12

### The problem

browsing albums in the INTEGRATION (not the addon) does not work.

### How to reproduce

in your LOVELACE open a mass music player and browse to to albums.

### Relevant log output

`homeassistant.log
``; rv:109.0) Gecko/20100101 Firefox/115.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1310, in websocket_browse_media
    payload = await player.async_browse_media(media_content_type, media_content_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_player.py", line 494, in async_browse_media
    return await async_browse_media(self.hass, self.mass, media_content_id, media_content_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_browser.py", line 103, in async_browse_media
    return await build_album_items_listing(mass, media_content_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mass/media_browser.py", line 254, in build_album_items_listing
    tracks = await mass.music.get_album_tracks(album.item_id, album.provider)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/music.py", line 155, in get_album_tracks
    for item in await self.client.send_command(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/client/client.py", line 168, in send_command
    return await future
           ^^^^^^^^^^^^
music_assistant.common.models.errors.InvalidCommand: Invalid command: music/album/album_tracks
2024-01-19 21:35:2
```

### Additional information

_No response_

### What version of Home Assistant Core are your running

2024.1.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Also please update to the latest version of MA and the latest version of the integration

**Comment by Bram-diederik** [comment]
> e error?

@marcelveldt asked me to create this issue. 
```
Daft_dutch
 — 
19-01-2024 16:32
found a bug. on Both my systems. Cant browse to a album. Unknown error 
that is also a normal OS with mass addon.
marcelveldt
 — 
19-01-2024 16:59
browsing albums in the MA interface works fine on my end.
or do you mean the HA interface ? If so, do you see an error in the log ?
if you report bugs, please be as descriptive as possible. We are still in beta stage and working out the issues so we need complete issue reports and reproduce scenarios.
Daft_dutch
 — 
19-01-2024 17:02
Yeah. I try to be as clear as possible. @marcelveldt but if i mention lovelace that means its the main ha gui and not browsing trough the addon.
marcelveldt
 — 
19-01-2024 17:06
so the internal HA media browser. then ?
Daft_dutch
 — 
19-01-2024 17:06
Yes.
marcelveldt
 — 
19-01-2024 17:07
Yes, I see the same. Can you create an issue report as a reminder for me please ?
Afbeelding
Daft_dutch
 — 
19-01-2024 17:07
Sure thing.
marcelveldt
 — 
19-01-2024 17:07
thanks
```

**Comment by OzGav** [comment]
This should be fixed in beta 92 please advise if not

**Comment by WexCore** [comment]
Looks like it was not fixed. Browsing albums in Home Assistant shows Unknown error.
```
music-assistant-server  | 2024-02-14 21:16:49.209 INFO (MainThread) [music_assistant] Starting Music Assistant Server (13f166577f3c4c68895f77b0dfb88baf) version 2.0.0b94 - uvloop: False
music-assistant-server  | 2024-02-14 21:16:49.212 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
music-assistant-server  | 2024-02-14 21:16:49.222 INFO (MainThread) [music_assistant.webserver] Starting server on  0.0.0.0:8095 - base url: http://192.168.1.201:8095
music-assistant-server  | 2024-02-14 21:16:49.259 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
music-assistant-server  | 2024-02-14 21:16:49.380 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
music-assistant-server  | 2024-02-14 21:16:49.380 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.1.201:8096
music-assistant-server  | 2024-02-14 21:16:56.578 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
music-assistant-server  | 2024-02-14 21:16:56.578 INFO (MainThread) [music_assistant] Loaded music provider URL
music-assistant-server  | 2024-02-14 21:16:56.579 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
music-assistant-server  | 2024-02-14 21:16:56.579 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
music-assistant-server  | 2024-02-14 21:16:56.580 INFO (MainThread) [music_assistant] Loaded player provider UPnP wexServer
music-assistant-server  | 2024-02-14 21:16:56.580 INFO (MainThread) [music_assistant.music] Sync task for URL completed
music-assistant-server  | 2024-02-14 21:16:56.581 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
music-assistant-server  | 2024-02-14 21:16:56.629 INFO (MainThread) [music_assistant.providers.slimproto] Started SLIMProto server on port 3483
music-assistant-server  | 2024-02-14 21:16:56.629 INFO (MainThread) [music_assistant.providers.slimproto.cli] Registering jsonrpc endpoints on the webserver
music-assistant-server  | 2024-02-14 21:16:56.631 INFO (MainThread) [music_assistant.providers.slimproto.cli] Starting (telnet) CLI on port 9090
music-assistant-server  | 2024-02-14 21:16:56.632 INFO (MainThread) [music_assistant.players] Player registered: 496f58a9-f171-4411-92cc-9e9154e64a64/Chromium-Snapcast
music-assistant-server  | 2024-02-14 21:16:56.632 INFO (MainThread) [music_assistant.players] Player registered: 30:9c:23:43:8f:40/wexServer AUDIO
music-assistant-server  | 2024-02-14 21:16:56.633 INFO (MainThread) [music_assistant.providers.snapcast] Started Snapserver connection on:wexServer:1705
music-assistant-server  | 2024-02-14 21:16:56.633 INFO (MainThread) [music_assistant] Loaded player provider Snapcast
music-assistant-server  | 2024-02-14 21:16:56.635 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
music-assistant-server  | 2024-02-14 21:16:57.450 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
music-assistant-server  | 2024-02-14 21:16:58.309 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
music-assistant-server  | 2024-02-14 21:17:00.117 INFO (MainThread) [music_assistant.players] Player registered: 22:63:83:01:09:66/squeezeplay: 22:63:83:01:09:66
music-assistant-server  | 2024-02-14 21:17:26.600 WARNING (MainThread) [music_assistant.webserver] [140495415931152] Invalid command: music/album/album_tracks

```
