### ISSUE TITLE
v1.1.5: Only first track of album displayed

### ISSUE THREAD

**Issue by AvdWerfhorst** [music-assistant/hass-music-assistant#184]
Since I updated to version 1.1.5 I only see track 1 of each album.

**Comment by vk2him** [comment]
I have just seen a related issue - if you view albums from an Artist from the Artis tab, it displays more than 100 albums
![Screen Shot 281](https://user-images.githubusercontent.com/22878629/168995060-72701d47-3807-40f4-94f6-2606b743c87c.jpg)

**Comment by vk2him** [comment]
As a test - I just nuked my .db and I'm rebuilding it to see if that "fixes" it

**Comment by AvdWerfhorst** [comment]
> I have just seen a related issue - if you view albums from the Artists tab, it displays more than 100 albums that are not from that artist ![Screen Shot 281](https://user-images.githubusercontent.com/22878629/168995060-72701d47-3807-40f4-94f6-2606b743c87c.jpg)

I see the same, but not with every artist.

![Good](https://user-images.githubusercontent.com/35181252/169003890-d84a9c21-1c2b-4fab-9c94-8de7edcf19cd.PNG)
![Bad](https://user-images.githubusercontent.com/35181252/169003905-d141147a-06bc-4e19-b44a-78e5b62eea9a.PNG)

**Comment by vk2him** [comment]
The .db rebuild didn't fix the problem

**Comment by AvdWerfhorst** [comment]
It's not always the same selection of albums which are shown as extra.
![Bad2](https://user-images.githubusercontent.com/35181252/169022111-f5efc5ec-38ec-4d41-bc5f-282c6e7d4cf4.PNG)

**Comment by AvdWerfhorst** [comment]
> Since I updated to version 1.1.5 I only see track 1 of each album.

One additional thing. I am not even sure if it is always the first track of the album. As you can see in this case, the icon is different. What makes me think it grabs the track from a compilation album instead of the album itself. I see that as unwanted behaviour, as this potentially can result in mismash of different variations of songs/remasters/remixes when playing back an album.

![Wrong track](https://user-images.githubusercontent.com/35181252/169026557-1efc87ef-7fca-4fcc-8ff2-779d6c2d0f2e.PNG)

**Comment by marcelveldt** [comment]
I will reset my own test db to see if I can reproduce. Somehow you're getting results that should not be there.
As for your second question: While track matching is allowed (even between music providers) this happens only for exactly the same version. Just like you I am a music fan and hate it when some other version ends up in my playlist/queue than the one I intended ;-)

That's why you have the "versions" tab on both tracks and albums to spot the different versions of a track/album such live, remasters etc.

I think I know where things go south and that is on a fileprovider only setup.
There's an actual bug in the code that got hidden by the fact I am testing with multiple music providers so I did not spot the missing files at once.

To be continued ;-)

**Comment by AvdWerfhorst** [comment]
Is that version detection purely tag based or does it also do some detection in the actual audio data? I am asking as I wonder if I should improve my tagging at some points.

**Comment by marcelveldt** [comment]
It is tag based only but I did a sort of extra safety check on the duration.

**Comment by AvdWerfhorst** [comment]
I see. That means I really need to rethink my tagging in some ways. For instance, I have a version of Freddie Mercury & Monserat Caballé's Barcelona album, with a bunch of bonus cd's. One of them is an orchestral version without the vocals. Currently I see for the first song, what is Barcelona, a version selected that does have the vocals.

Would this work to differentiate? Fill in the VERSION tag with things like "live", "2022 remaster", "instrumental" etc?

**Comment by marcelveldt** [comment]
The version tag is not widely adopted so for best results I recommend to append the version to the title e.g. "Barcelona (2022 Remaster). The very best way to tag your tracks is by setting the isrc or musicbrainz id field. That way there is no auto matching needed at all because those are the unique identifiers we're looking for.

Maybe it would help if I copy the version of the album over to the track?
That would prevent the case where a track is matched as the same while it isn't.

I assume these other versions of the album all have the version in the name ?
So for example you have this structure:

Freddy Mercury\Barcelona\Track.flac
Freddy Mercury\Bercelona (Orchestra)\Track.flac

right ?

And what's set to the album of these tracks ? 

Looking at streaming providers (including Qobuz which have their metadata very well organized, kudos) they do it like this: 
Track artists: Freddy Mercury \ Monserat Caballé
Track Album: Barcelona (Orchestral version)
Track Title: Barcelona (Orchestral version) 

So you can always easily identify a specific track version. 
Spotify also has

**Comment by marcelveldt** [comment]
isrc is the best to identify unique tracks and is also what the streaming providers use.

The way you describe your preference is how it should already work but doesn't because of a bug.
Only thing is that a folder name is not used to identify the album name (only as last resort) but the "album" ID3 tag.
I suppose that the album tag is also set to "Barcelona Special Edition Orchestral Version" for the tracks in the above example?

**Comment by AvdWerfhorst** [comment]
The album tag and the folder name are the same.

**Comment by marcelveldt** [comment]
OK, managed to fix it. The fix will be included in next version.

**Comment by vk2him** [comment]
This looks to be fixed in 1.1.17 - well done!

**Comment by AvdWerfhorst** [comment]
Most albums seem to be complete now. But I still see some albums where tracks are missing. For instance, Michael Jackson's Bad is missing Bad.
![Bad start](https://user-images.githubusercontent.com/35181252/169290137-6ba160d2-7b0b-4801-ae2c-8d15d2174434.PNG)

**Comment by marcelveldt** [comment]
1.1.8 released. Can you check if the issue is resolved ?

**Comment by AvdWerfhorst** [comment]
I did remove Music Assistant and add it again, to make renew the database from zero. In the example of Michael Jackson's Bad I still get exactly the same selection of tracks unfortunately.

**Comment by marcelveldt** [comment]
So everything is fixed except for the strange issue that the track "Bad" is missing from the album "Bad" ?

**Comment by marcelveldt** [comment]
oh.... think I now know what the issue is. Could it be that you have the Bad album twice now ?
one with only the Bad track and the other with the rest of the tracks ?

**Comment by AvdWerfhorst** [comment]
I think it is even something different. I am right now reloading everything from scratch using v1.1.9. And I checked Michael Jackson's Bad again. Still missing the song Bad. Now I also looked at Michael Jackson as artist. And I see the song Bad listed as part of HIStory, what is correct, as the song is also on that album. But I also see for instance Beat it and Billy Jean as part of HIStory. If I check Thriller, where they originate from I am missing those songs... So it looks to me like there is an issue attributing songs to more than one album.
![mj](https://user-images.githubusercontent.com/35181252/169396893-9da7db6c-3d30-4a15-9c8c-f274802871dc.png)

**Comment by marcelveldt** [comment]
Somehow the songs get linked to the wrong album. The "bad" case I just reproduced.
Stupid mistake where Bad is parsed as the single instead of the parent album.
Thinking about that, both Thriller and Billy Jean also have a single release so maybe it's the same issue.

Do you have the MusicBrainzReleaseGroupID set on your ID3 tags ?
Or just the plain text tag for album ?

I'm going to adjust the code that's now causing "bad" to be treated as single release.
Somehow I hope that will also fix your other issue because I'm slowly getting out of options :-)

**Comment by marcelveldt** [comment]
Pushed version 1.1.0 with the (hopefully) final fix for this!
Just to be sure I've bumped the db schema so a full rescan is performed once you install the 1.1.10 update.

Please let me know if your issues are resolved with 1.1.0, thanks!

**Comment by AvdWerfhorst** [comment]
I have another issue now, for which I will open a new issue. The Music Assistant screen stays empty when I open it (instead of the screen with Artists, Albums etc.
But when I go through the Media menu to Music Assistant, it seems on first sight that the album content is right. 

Bad was not yet tagged with any id, musicbrainz or ISRC. But I did notice the same behavior with Barcelona, which I had tagged. Anyway, I think this issue is over now.

**Comment by marcelveldt** [comment]
Yeah, a dependency caused the frontend build to go corrupt. Released 1.1.11 to fix that.
Good news that the main issue is now resolved!

**Comment by AvdWerfhorst** [comment]
I have spoken too soon. As I also had missing tracks on Barcelona and Bad was not loaded in the database yet, I checked that one instead (all versions) and Barelona is complete. Now Bad is loaded into the database and missing those tracks. Can it be that another album containing tracks with identical title and length (the same version) overwrites the database record of the previously found copy? Or at least the album info.

Most stuff in my collection has no ISRC tags yet. I am planning to add that, but need to find the time for that.

**Comment by marcelveldt** [comment]
The issue is that the same recording can exist in multiple albums. Recording studios do not remaster or re-record it when they place it on another (compilation) album. For the streaming providers I just query which tracks belong to an album and I get the correct listing. In this case I make a query on the database (to prevent accessing disk) and that's what's causing this issue. A unique track (with same recording id) gets linked to the album that first comes in the db.

So it is in fact the isrc (or recording id) causing the issue that it should prevent in the first place :-)

Stupid I did not think about that earlier.
I am going to adjust the logic and either query disk to get the real listing or adjust the database model.

I think I'm going with the database model because some people just dump 

I'll let you know when there's something to test.

**Comment by marcelveldt** [comment]
OK, made some (hopefully now final!) changes to the data models. Now it's allowed that a unique recording gets linked to different albums while keeping the strictness in place.

I'm going to release a new patch release now

**Comment by AvdWerfhorst** [comment]
It feels like we are getting close to something that works. I think the albums are now complete again. But unfortunately I see that the track numbers are not always correct. For instance, this is what I see with the album Bad. The track Bad, should be track one, but is listed as track 6. It is track 6 on HIStory, so I guess that album is the source of that data.
![Badbad](https://user-images.githubusercontent.com/35181252/169645777-e015db4a-1d99-4fb0-b15d-3d65beb2396f.png)

**Comment by marcelveldt** [comment]
Yes, same issue. Somehow I got spoiled by the streaming providers that provide this info per album.
I wil make this final adjustment and then we're ready.

**Comment by marcelveldt** [comment]
@AvdWerfhorst I've just released 1.1.4 which should have it all fixed :-)

**Comment by AvdWerfhorst** [comment]
To me it looks like it works like it should. I get all tracks in the right order. Great work.
