### ISSUE TITLE
No players and no group players are visible under the Player tab in the MASS Settings

### ISSUE THREAD

**Issue by Mustreg** [music-assistant/hass-music-assistant#1846]
### What version of Music Assistant has the issue?

2024.1.0 (2.0.0b90)

### The problem

1. No players are visible under the "Players" tab in MASS (Current version: 2.0.0b90)
2. Unable to add players to Universal Group Player/Sonos groups as players are not available for selection.
3. Howerver, the players are visible on the "blue" icon selection list and under the devices list in HA.
4. I **can** play music from Tidal to those individual players in MASS without any problems
5. I have tried to reinstall/restart/reconfigure MASS many times to no avail 

### How to reproduce

1. Check the content (empty) displayed under the player tab in the Mass settings
2. Try to create new Universal or Sonos player group 

### Relevant log output

2024-01-29 19:43:54.356 INFO (MainThread) [music_assistant] Starting Music Assistant Server (*****************) version 2.0.0b90 - uvloop: False
2024-01-29 19:43:54.365 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-01-29 19:43:54.373 INFO (MainThread) [music_assistant.cache] Running automatic cleanup...
2024-01-29 19:43:54.380 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-01-29 19:43:54.440 INFO (MainThread) [music_assistant.cache] Automatic cleanup finished (cleaned up 0 records)
2024-01-29 19:43:54.592 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-01-29 19:43:54.784 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
2024-01-29 19:43:54.784 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8096 - base url: http://192.168.178.62:8096
2024-01-29 19:43:55.262 INFO (MainThread) [music_assistant] Loaded player provider UPnP/DLNA Player provider
2024-01-29 19:43:55.262 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-01-29 19:43:55.262 INFO (MainThread) [music_assistant] Loaded music provider URL
2024-01-29 19:43:55.264 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-01-29 19:43:55.264 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-01-29 19:43:55.266 INFO (MainThread) [music_assistant] Loaded player provider Universal Group Player
2024-01-29 19:43:55.272 INFO (MainThread) [music_assistant] Loaded player provider SONOS
2024-01-29 19:43:55.273 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-01-29 19:43:55.336 INFO (MainThread) [music_assistant] Loaded player provider Chromecast
2024-01-29 19:43:55.338 INFO (MainThread) [music_assistant.providers.slimproto--VHwwRtZB] Started SLIMProto server on port 3483
2024-01-29 19:43:55.339 INFO (MainThread) [music_assistant.providers.slimproto--VHwwRtZB.cli] Registering jsonrpc endpoints on the webserver
2024-01-29 19:43:55.348 INFO (MainThread) [music_assistant] Loaded music provider Filesystem (local disk)
2024-01-29 19:43:55.351 INFO (MainThread) [music_assistant.providers.slimproto--VHwwRtZB.cli] Starting (telnet) CLI on port 9090
2024-01-29 19:43:55.356 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2024-01-29 19:43:55.720 INFO (MainThread) [music_assistant.players] Player registered: uuid:**************/Denon Player Heos SLN
2024-01-29 19:43:55.869 INFO (MainThread) [music_assistant] Loaded music provider Tidal
2024-01-29 19:43:55.886 INFO (MainThread) [music_assistant.players] Player registered: RINCON_***********Sonos Roam 1
2024-01-29 19:43:55.890 WARNING (MainThread) [soco.events_asyncio] Could not bind to 192.168.178.62:1400: [Errno 98] Address already in use
2024-01-29 19:43:56.047 INFO (MainThread) [music_assistant.players] Player registered: RINCON_************/Bedroom
2024-01-29 19:43:56.273 INFO (MainThread) [music_assistant] Loaded player provider Airplay
2024-01-29 19:43:56.330 INFO (MainThread) [music_assistant.players] Player registered: aa:*******/Bedroom
2024-01-29 19:43:56.605 INFO (MainThread) [music_assistant.players] Player registered: aa:*******/Sonos Roam 1

### Additional information

![image](https://github.com/music-assistant/hass-music-assistant/assets/105296988/b67497eb-b588-4b1e-9596-e0c50b3578d0)
![image](https://github.com/music-assistant/hass-music-assistant/assets/105296988/4c4a02dd-a646-47c5-bc9a-0dac5f8b581b)
![image](https://github.com/music-assistant/hass-music-assistant/assets/105296988/e61195a2-9287-4003-975e-ffc343199820)
![image](https://github.com/music-assistant/hass-music-assistant/assets/105296988/af1b9b15-2615-4376-b344-f5ebd0e2d27a)

### What version of Home Assistant Core are your running

2024.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Are you sure there are no other errors in the log ?
Did you try to force refresh the browser to rule out some cache issue ?

**Comment by marcelveldt** [comment]
What a strange issue - I will do my best to try to reproduce this issue.

Can you go to the MA settings --> core tab and download the logfile there ?
Please attach it here so I can have a look. Please allow the server to start for 5 to 10 minutes before collecting the log

**Comment by marcelveldt** [comment]
I was able to reproduce this issue on a complete fresh installation. 
I'll prepare a fix for next release

**Comment by OzGav** [comment]
This should be fixed in beta 92 please advise if not

**Comment by Mustreg** [comment]
After applying the new version  2.0.0b92 to the existing installation the players were still missing. 
However, after I removed the MA addon and reinstalled the 2.0.0b92 addon from scratch my players reappeard on the players tab in the settings.
Therefore the issue has been solved. 
Thank you very much!

**Comment by Smarthome-Creator** [comment]
I had the same problem. The only solution is to reinstall the MA addon.

**Comment by charlesomer** [comment]
First time install here, running `2.0.0b98` and I can't see any devices in groups.

**Comment by marcelveldt** [comment]
This is fixed in beta 99

**Comment by charlesomer** [comment]
Excellent that worked thank you :)

**Comment by jimmythesnitch** [comment]
This is happen to me on a fresh install of Music Assistant today,  I'm on a Odroid C4  cleared browser... restarted device.. 

nadda.
