### ISSUE TITLE
Airplay playback does not work to Airport Express devices

### ISSUE THREAD

**Issue by lor74** [music-assistant/hass-music-assistant#1954]
### What version of Music Assistant has the issue?

2.0.0b103

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After latest update I cann'ot use my Aripplay device (Apple Airport). With the latest update the working player is marked as unavailable. There is a "new" Airplay Device but I can't stream music on it.

![Screenshot 2024-02-24 alle 08 51 31](https://github.com/music-assistant/hass-music-assistant/assets/151439172/6225befb-12a0-458b-8c95-c01ea38411b4)

Restarting both core and MA doesn't fix

Rollback to 2.0.0b94 fix the issue

![Screenshot 2024-02-24 alle 08 48 45](https://github.com/music-assistant/hass-music-assistant/assets/151439172/d3921eb5-5e6c-4dd0-8807-0002df876556)

### How to reproduce

Try to start play

### Music Providers

All

### Player Providers

Airplay

### Relevant log output

This is the logs entry after try to enable the "new" Airplay device and stream some music

```
2024-02-24 08:35:17.706 ERROR (MainThread) [music_assistant.webserver] [546527646416] Error handling message: CommandMessage(message_id=20, command='players/cmd/power', args={'player_id': 'apac7f3ee81fe7', 'powered': True})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 75, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/players.py", line 452, in cmd_power
    await self.mass.player_queues.resume(player_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 628, in resume
    raise QueueEmpty(msg)
music_assistant.common.models.errors.QueueEmpty: Resume queue requested but queue apac7f3ee81fe7 is empty
```

```
2024-02-24 08:35:25.285 ERROR (MainThread) [music_assistant.webserver] [546527646416] Error handling message: CommandMessage(message_id=21, command='players/queue/play_pause', args={'queue_id': 'apac7f3ee81fe7'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/webserver.py", line 374, in _run_handler
    result = await result
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 543, in play_pause
    await self.play(queue_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 515, in play
    await self.resume(queue_id)
  File "/usr/local/lib/python3.11/site-packages/music_assistant/server/controllers/player_queues.py", line 628, in resume
    raise QueueEmpty(msg)
music_assistant.common.models.errors.QueueEmpty: Resume queue requested but queue apac7f3ee81fe7 is empty
```

### Additional information

Details of "new" Ariplay device withe the new version of MA
![Screenshot 2024-02-24 alle 08 52 23](https://github.com/music-assistant/hass-music-assistant/assets/151439172/0dd87308-6d00-4985-82db-43f4da7e725d)

Details of working Ariplay device withe previous version of MA.
![Screenshot 2024-02-24 alle 08 55 43](https://github.com/music-assistant/hass-music-assistant/assets/151439172/a2ebfacf-7001-4811-a632-b42476eba2dc)

### What version of Home Assistant Core are your running

2024.2.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by lor74** [comment]
I have deleted both players as you suggested, after MA restart I can see "the new" Airplay but I still can't stream on it. 
I have also restarted HA... same issue.
I have uninstalled all and reinstalled from scratch... still not working even if in the logs is showed
```

2024-02-24 11:22:50.058 INFO (MainThread) [music_assistant] Loaded music provider Qobuz
2024-02-24 11:23:07.678 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue AirPort Express di Lorenzo - crossfade: False
2024-02-24 11:23:45.722 INFO (MainThread) [music_assistant.music] Sync task for Qobuz completed
2024-02-24 11:26:02.248 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue AirPort Express di Lorenzo - crossfade: False
```
If I use chrmecast device (salotto) it works.
My device is an Apple AirPort Express.

Quite annoying since now I have some trouble to restore from backup (maybe I will try to restore from e HA full backup).

**Comment by OzGav** [comment]
Ok the problem is the age of the player….support for it was not included in the recent Airplay rewrite. We have added it to the backlog but not sure of the priority for this at the moment.

**Comment by lor74** [comment]
Thanks. In the meantime I will skip any MA update until you’ll report here for the fix. 

Thanks

**Comment by drjjr2** [comment]
Also interesting in getting this working for Airport Express 802.11n (2nd Generation)

**Comment by marcelveldt** [comment]
Should be fixed in the next beta (b106) - let us know if its not working, I don't have an Airport express to verify.

**Comment by drjjr2** [comment]
> Should be fixed in the next beta (b106) - let us know if its not working, I don't have an Airport express to verify.

I am still seeing the same behavior after updating to b106.  The log just says
`2024-02-26 20:38:14.301 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Garage Airplay - crossfade: False`
But nothing plays. I can airplay to it using my phone so connectivity isn't an issue

**Comment by marcelveldt** [comment]
ah, we should filter out that loopback address. I'll fix that for the next update.
Maybe keep reloading the airplay provider until the adress lists correctly and then check if playback works ?

**Comment by bdtrocke** [comment]
I am also seeing this error in b106. HomePods and HomePod Mini's work just fine. But the Airport Express's that I have connected to the whole home audio do not work with MA.

**Comment by lor74** [comment]
> ah, we should filter out that APIPA address. I'll fix that for the next update. Maybe keep reloading the airplay provider until the adress lists correctly and then check if playback works ?

Hi @marcelveldt  the latest update include the Fix? Can we try to update or is still a bug? I havn't found a specific info on release notes... 

Thanks

**Comment by niteguide** [comment]
Installed 2.0.0b107 - problem persists! Can not stream to AirPort Express unfortunately.

**Comment by marcelveldt** [comment]
b107 contains the fix for the IP-address - so if you look at the device info, it should now show the correct device IP (and not an 169. address).

There may be other issues, the Airport Express is a very old device that needs some special treatments.
Unfortunately I do not own one so this is a bit trial and error.

Can you confirm that the IP is now correctly listed ?
Also, any other hints in the logs that may be helpful ?

**Comment by bdtrocke** [comment]
No go here. The IP now shows correctly but even after clearing out all players, and trying encryption and compression in different ways restarting after each time Music Assistant refuses to play to the Airport Expresses. If I try to AirPlay from my phone it works fine so I know the AirPort Express is functional. If I try to play to the Airport Express in MA, it seems to error out. The play button never turns into a pause button and if I change the source to a HomePod it plays. I've attached the log file. Around 20:49 I played music to a HomePod (Kitchen) and then once that was successful, I paused and changed the source to an AirPort Express (WholeHomeSource02) and that failed. 

2024-03-11 20:50:18.666 DEBUG (MainThread) [music_assistant.event] queue_updated apd4909cea0227
2024-03-11 20:50:18.667 DEBUG (MainThread) [music_assistant.event] player_updated apd4909cea0227
2024-03-11 20:50:19.704 DEBUG (MainThread) [music_assistant.providers.airplay.apd4909cea0227] CLIRaop process stopped with errorcode 0
2024-03-11 20:50:19.705 DEBUG (MainThread) [music_assistant.providers.airplay.apd4909cea0227] Audio reader finished
2024-03-11 20:50:19.860 DEBUG (MainThread) [music_assistant] Service D4909CEA0227@Kitchen._raop._tcp.local. of type _raop._tcp.local. state changed: ServiceStateChange.Updated
2024-03-11 20:50:19.978 DEBUG (MainThread) [music_assistant] Service D4909CEA0227@Kitchen._raop._tcp.local. of type _raop._tcp.local. state changed: ServiceStateChange.Updated
2024-03-11 20:50:27.647 DEBUG (MainThread) [music_assistant.webserver] [140083247599632] Handling command config/providers
2024-03-11 20:50:28.830 DEBUG (MainThread) [music_assistant.providers.airplay.ap34363bbb8048] Audio reader finished
2024-03-11 20:50:28.830 DEBUG (MainThread) [music_assistant.providers.airplay.ap34363bbb8048] CLIRaop process stopped with errorcode 0
2024-03-11 20:50:30.282 DEBUG (MainThread) [music_assistant.webserver] [140083247599632] Handling command config/core
2024-03-11 20:50:30.292 DEBUG (MainThread) [music_assistant.webserver] [140083247599632] Handling command music/artists/library_items
2024-03-11 20:50:30.302 DEBUG (MainThread) [music_assistant.webserver] [140083247599632] Handling command music/albums/library_items
2024-03-11 20:50:30.309 DEBUG (MainThread) [music_assistant.webserver] [140083247599632] Handling command music/tracks/library_items
2024-03-11 20:50:30.314 DEBUG (MainThread) [music_assistant.webserver] [140083247599632] Handling command music/playlists/library_items
2024-03-11 20:50:30.321 DEBUG (MainThread) [music_assistant.webserver] [140083247599632] Handling command music/radio/library_items

[MAlogFile.txt](https://github.com/music-assistant/hass-music-assistant/files/14566202/MAlogFile.txt)

**Comment by marcelveldt** [comment]
OK, I gave it another shot and may have found something. Still a bit trial and error without an actual device to test with...

Please give the next beta 108 a try, should be available within now and 30 minutes.

**Comment by lor74** [comment]
Hi,
seems still not working.
In the logs I have
`2024-03-13 07:37:30.840 ERROR (MainThread) [music_assistant.webserver] [546503150480] Error handling message: players/queue/play: Resume queue requested but queue apac7f3ee81fe7 is empty
2024-03-13 07:37:31.647 ERROR (MainThread) [music_assistant.webserver] [546503150480] Error handling message: players/queue/play: Resume queue requested but queue apac7f3ee81fe7 is empty
2024-03-13 07:37:32.118 ERROR (MainThread) [music_assistant.webserver] [546503150480] Error handling message: players/queue/play: Resume queue requested but queue apac7f3ee81fe7 is empty
`
Two ariplay players... the second is the working in the oldest version (IP address 127.0.0.1 as showed in mu first post)
![Screenshot 2024-03-13 alle 07 38 58](https://github.com/music-assistant/hass-music-assistant/assets/151439172/9d26ac11-e2a7-4384-aba2-b2b87d84a86d)

Configuration of "new" device
![Screenshot 2024-03-13 alle 07 39 18](https://github.com/music-assistant/hass-music-assistant/assets/151439172/c3ae55f1-f755-4d93-8a32-bd3a0fcb57d4)

Also enabling encruption doesn't work.

Since we have the device and you not own it can we give you more details? eg executing a trace with WireShark or debugging something else?

**Comment by marcelveldt** [comment]
Please read that error very carefully! It stated that you tried playback with no items in the queue. Please start playing a track or playlist or whatever

**Comment by lor74** [comment]
Yes I have also tried to start a track and a playlist... no error in logs... just the lines reported (occurs at the update)

**Comment by marcelveldt** [comment]
Tested with the airport express today and created a fix, playback is now working for me on that 15 years old device ;-)
please test b110 - its available within now and 30 minutes!

**Comment by lor74** [comment]
@marcelveldt super! It works!!!! Yeah on a 15 years old device (but this device after 15 years is still working fine)
Just a note the version installed is b111.
Great job really! 
Thanks!

**Comment by marcelveldt** [comment]
Great to hear! Enjoy the music.

**Comment by drjjr2** [comment]
Playback works but Music Assistant is showing the wrong information for the song that is playing. I am playing a Tidal Playlist to the Airport Express and it shows a different song as the one that's playing. What would cause that? Multiple browsers/devices show the same (incorrect) song as playing. I am on Version b115 with HA server 2024.3.2.
Airplay to a different player shows the correct song information.

**Comment by drjjr2** [comment]
> Playback works but Music Assistant is showing the wrong information for the song that is playing. I am playing a Tidal Playlist to the Airport Express and it shows a different song as the one that's playing. What would cause that? Multiple browsers/devices show the same (incorrect) song as playing. I am on Version b115 with HA server 2024.3.2. Airplay to a different player shows the correct song information.

Well, I restarted the add-on and it seems to be showing the correct information now.

**Comment by sergiosafer** [comment]
Hi, I'm still having problems. When I try to integrate with HA it is not possible.
![image](https://github.com/music-assistant/hass-music-assistant/assets/132413705/867f93aa-62a1-45f5-9811-79b2b90fff51)

The strangest thing is that MA appears to be installed but I can't integrate it.
![image](https://github.com/music-assistant/hass-music-assistant/assets/132413705/be092560-7e52-4b81-890c-8e6e3cb3609e)

**Comment by OzGav** [comment]
This doesn’t seem to have anything do with Airport express devices? Go through the troubleshooting steps in the docs then open a new discussion with all the required details.

**Comment by heinduik** [comment]
> I managed to purchase an Airport Express second hand - I should receive it within 2 days.
> 
> 
> 
> The Airport Express needs a bit of special treatment with the Airplay protocol (ironically enough) and without access to the actual device its a bit difficult for me to troubleshoot. So I ask for a couple of days patience until I sort this one out.


Did you use the first gen or second gen AirPort Express? I'm looking for buying one aswell for playing music from MA. But I want to be sure with generation AirPort Express I need to buy.

**Comment by niteguide** [comment]
I strongly presume that the developer bought a 2nd gen as we were never talking about 1st gen in this post. I myself have a 2nd gen and can confirm that it works.

**Comment by heinduik** [comment]
Thanks a lot! I'll buy a second gen. Cheers!

**Comment by iflyckt** [comment]
Has anyone got this to work with the 1st gen AirPort Express (A1264)?

I have two of those and I recently installed MA but cannot get them to work. The issue seems very similar to what @bdtrocke was experiencing with the play button never turning to a pause and playback doesn’t start.

**Comment by lor74** [comment]
I guess that your device support only Airplay V1 and could not be updated to version 2

[https://discussions.apple.com/thread/8523639?sortBy=rank](url)

If you check in MA doc (known issues) the support to protocol V1 is very limited... If is the first time that you try to use this device with MA I guess this means that it is not supported.

**Comment by iflyckt** [comment]
Yes, it only supports AirPlay 1. 

I’ve read the documentation and I interpret it differently. It seems that AirPlay 2 is causing more issues than AirPlay 1? 

Quote from documentation:

”_Music Assistant implements RAOP (Airplay 1) only, Airplay 2 devices should be backwards compatible by default. If a device has a bad implementation of Airplay 1 and/or only supports Airplay 2 then it won't work_”

And in this case it shouldn’t be a bad implementation when it’s an original Apple product. Even though it’s pretty old.
