### ISSUE TITLE
Disabling the player in HA does not close the ffmpeg process

### ISSUE THREAD

**Issue by melwinek** [music-assistant/hass-music-assistant#2038]
### What version of Music Assistant has the issue?

2.0.0b117

### What version of the Home Assistant Integration have you got installed?

2024.3.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If I turn off the playing player in HA. After enabling, a new ffmpeg process is started. After some time, this consumes all RAM and CPU.

### How to reproduce

Turn on playback in the player in the HA tab and turn off the player in HA without pressing pause.

### Music Providers

URL

### Player Providers

Slimproto

### Full log output

Log from MA:
```
2024-03-21 06:50:59.039 INFO (MainThread) [music_assistant] Starting Music Assistant Server (cb8ebee3e2e04fadace521e904883457) version 2.0.0b117 - uvloop: False
2024-03-21 06:50:59.079 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-03-21 06:50:59.095 INFO (MainThread) [music_assistant.webserver] Starting server on  192.168.3.3:8095 - base url: http://192.168.3.3
2024-03-21 06:50:59.179 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-03-21 06:50:59.507 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 5.1.4 with libsoxr support
2024-03-21 06:50:59.507 INFO (MainThread) [music_assistant.streams] Starting server on  192.168.3.3:8097 - base url: http://192.168.3.3:8097
2024-03-21 06:51:01.798 INFO (MainThread) [music_assistant] Loaded music provider URL
2024-03-21 06:51:01.799 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv Metadata provider
2024-03-21 06:51:01.800 INFO (MainThread) [music_assistant.music] Sync task for URL completed
2024-03-21 06:51:01.802 INFO (MainThread) [music_assistant] Loaded metadata provider TheAudioDB Metadata provider
2024-03-21 06:51:01.802 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz Metadata provider
2024-03-21 06:51:01.997 INFO (MainThread) [music_assistant] Loaded music provider Filesystem (local disk)
2024-03-21 06:51:02.003 INFO (MainThread) [music_assistant] Loaded player provider Slimproto
2024-03-21 06:51:02.008 INFO (MainThread) [music_assistant.music] Sync task for Filesystem (local disk) completed
2024-03-21 06:51:03.378 INFO (MainThread) [music_assistant] Loaded music provider YouTube Music
2024-03-21 06:51:06.065 INFO (MainThread) [music_assistant.providers.slimproto] Player squeezeplay: b8:27:eb:aa:35:03 connected
2024-03-21 06:51:06.066 INFO (MainThread) [music_assistant.players] Player registered: b8:27:eb:aa:35:03/squeezeplay: b8:27:eb:aa:35:03
2024-03-21 06:51:06.612 INFO (MainThread) [music_assistant.music] Sync task for YouTube Music completed
```

### Additional information

output of ps aux from host after multiple on/offs:
```
root        5781  0.8  0.6 301380 50560 ?        SLl  07:51   0:07 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
root        6038  0.9  0.6 301328 52940 ?        SLl  07:52   0:07 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
root        6255  0.8  0.6 301236 52492 ?        SLl  07:54   0:06 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -af afade=type=in:start_time=0:duration=3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
root        6568  0.8  0.6 301156 50688 ?        SLl  07:55   0:05 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -af afade=type=in:start_time=0:duration=3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
root        6632  0.9  0.6 301156 50688 ?        SLl  07:55   0:05 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -af afade=type=in:start_time=0:duration=3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
root        8336  3.3  0.7 307312 56056 ?        SLl  08:05   0:00 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -ar 48000 -f s16le -i - -acodec flac -f flac -ac 2 -ar 48000 -
root        8337  3.3  0.6 300524 49920 ?        SLl  08:05   0:00 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -af afade=type=in:start_time=0:duration=3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
```

### What version of Home Assistant Core are your running

2024.3.1

### What type of installation are you running?

Home Assistant Core

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
How are you running the server ? docker or the add-on ?

**Comment by marcelveldt** [comment]
These ffmpeg processes should be cleaned up after a few minutes. 
A few ffmpeg processes are not able to consume all memory and cpu, then something else must be going on.

**Comment by melwinek** [comment]
docker, not addon.

**Comment by marcelveldt** [comment]
OK, thanks for the additional info.
I will look into it.

**Comment by marcelveldt** [comment]
Found the issue - fixed in next release

**Comment by OzGav** [comment]
b118 is released

**Comment by melwinek** [comment]
Unfortunately, I still have the same problem. After a few clicks on the on/off button in HA. ffmpeg processes remain in memory and the RAM consumption of the container increases until the computer freezes.

![image](https://github.com/music-assistant/hass-music-assistant/assets/10649327/6afd5833-7a65-4795-a044-177bee99dc7e)

```
root      270931  0.0  0.7 307312 56884 ?        SLl  07:37   0:00 ffmpeg -hide_banner -loglevel quiet -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -ar 48000 -f s16le -i - -acodec flac -f flac -ac 2 -ar 48000 -
root      270932  0.9  0.6 301380 53008 ?        SLl  07:37   0:07 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
root      271035  0.0  0.7 307312 56952 ?        SLl  07:38   0:00 ffmpeg -hide_banner -loglevel quiet -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -ar 48000 -f s16le -i - -acodec flac -f flac -ac 2 -ar 48000 -
root      271036  0.9  0.6 301328 51712 ?        SLl  07:38   0:07 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -af afade=type=in:start_time=0:duration=3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
root      271047  0.0  0.7 307312 56624 ?        SLl  07:38   0:00 ffmpeg -hide_banner -loglevel quiet -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -ar 48000 -f s16le -i - -acodec flac -f flac -ac 2 -ar 48000 -
root      271048  0.9  0.6 301328 51456 ?        SLl  07:38   0:07 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
root      271087  1.3  0.7 308244 57844 ?        SLl  07:38   0:10 ffmpeg -hide_banner -loglevel quiet -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -ar 48000 -f s16le -i - -acodec flac -f flac -ac 2 -ar 48000 -
root      271088  0.9  0.6 301328 52096 ?        SLl  07:38   0:07 ffmpeg -hide_banner -loglevel info -ignore_unknown -protocol_whitelist file,http,https,tcp,tls,crypto,pipe,data,fd -ac 2 -channel_layout stereo -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 10 -reconnect_on_network_error 1 -reconnect_on_http_error 5xx -f mp3 -i http://ic2.smcdn.pl/2180-1.mp3 -acodec pcm_s16le -f s16le -ac 2 -ar 48000 -
```

**Comment by marcelveldt** [comment]
Am I correct that you ONLY use slimproto based players with radio streams ?
Or any music source ?

**Comment by melwinek** [comment]
Yes, exactly Slimproto + radio streams. Possibly also YouTube. But for now only radio.

**Comment by marcelveldt** [comment]
OK, I'm investigating the issue and update when its fixed

**Comment by OzGav** [comment]
Should be fixed in b119

**Comment by marcelveldt** [comment]
Can we leave this open until confirmed fixed?

**Comment by OzGav** [comment]
Giel tested and reported on discord but we can wait for more thumbs ups,

**Comment by marcelveldt** [comment]
Yes please, this issue is serious enough that we need to be 100% confident.
(I'm 100% confident I fixed it, but I'd like others to confirm)

**Comment by melwinek** [comment]
In 119, RAM usage did not increase dramatically. But the ffmpeg processes were not being closed. At 122 it looks like everything is fine.
