### ISSUE TITLE
No sound even though MA shows as playing

### ISSUE THREAD

**Issue by rVlad93** [music-assistant/hass-music-assistant#2072]
### What version of Music Assistant has the issue?

2.0.0b125

### What version of the Home Assistant Integration have you got installed?

2024.3.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

No soung through the speaker even though MA shows as playing from YT music. Local playback seems to work fine.

### How to reproduce

https://github.com/music-assistant/hass-music-assistant/assets/60452666/57d98786-f91d-423e-9679-75049934ed11

### Music Providers

YT Music

### Player Providers

Airplay

### Full log output

[d5369777_music_assistant_beta_2024-03-27T12-21-43.822Z.log](https://github.com/music-assistant/hass-music-assistant/files/14773309/d5369777_music_assistant_beta_2024-03-27T12-21-43.822Z.log)

### What version of Home Assistant Core are your running

2024.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
You have not indicated what you have tried from the troubleshooting page. For example, have you tried restarting the player?

**Comment by rVlad93** [comment]
I did. Restarted home assistant as well.

**Comment by OzGav** [comment]
Have you gone through this closed issue? https://github.com/music-assistant/hass-music-assistant/issues/2044

**Comment by OzGav** [comment]
And you haven't explained what is working

**Comment by marcelveldt** [comment]
Note that most non-apple hardware needs "encryption" enabled in the player settings.

**Comment by rVlad93** [comment]
I enabled that but still no go. It worked without any change until recently so I'm not sure that's the issue.

**Comment by marcelveldt** [comment]
Ah sorry, I missed the fact that it was working before. 
I will test here and get back to you

**Comment by marcelveldt** [comment]
this should be fixed in the latest beta 127

**Comment by OzGav** [comment]
Now up to b128 please check with that

**Comment by bj61251** [comment]
I'm having this issue as well, since I think b126, but I just updated to b128 and it is still happening. I'm using Media Extractor to load news segments from an rss xml url, and it worked fine for as long as I can remember. Now, the player shows the title of the episode, and the progress slider is moving, but there is no audio.

**Comment by michaeldufour** [comment]
I have this issue with YTM provider also with the version 2.0.0b129
I'm able to play 2-3 tracks of a playlist and suddently no more sound, the time progress continue but no sound. If I past to the next track the sound come back.

No error in the log for me.

**Comment by rVlad93** [comment]
I can confirm the music is playing. I'll report back if I encounter any issues. Thanks!

**Comment by marcelveldt** [comment]
We are looking into this - I'll update here later this weekend when there is news.

**Comment by marcelveldt** [comment]
Just to be very clear: this ONLY happens with music from Youtube Music right ?
Other providers like local files or online radio does work ?

Please collect the full log 5 minutes after music stopped and attach it here.

**Comment by michaeldufour** [comment]
> Just to be very clear: this ONLY happens with music from Youtube Music right ? Other providers like local files or online radio does work ?
> 
> Please collect the full log 5 minutes after music stopped and attach it here.

Yes I tried with File system and no problem, attached the debug log
[MASS.txt](https://github.com/music-assistant/hass-music-assistant/files/14809877/MASS.txt)

**Comment by Profex** [comment]
> Other providers like local files or online radio does work ?

I have a similar issue affecting certain TuneIn radio streams
Not sure when it started to happen, but it must have been with one of the latest beta versions, previously this was just working fine

One example stream is the one below:
https://tunein.com/radio/SUNSHINE-LIVE-1021-s10637/

Playing this from TuneIn web page directly it just works fine, and I get sound
When I play this from Music Assistant the player tells me that the radio stream is playing, but there is no sound
And in addition the music assistant player gets completely unresponsive, e.g. when I press pause or try to power off the player nothing happens, and I can see the following message in the logs after 10 seconds:

`2024-03-29 13:40:43.395 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/queue/play_pause: Execution of pause timed out after 10.0 s.`

In order to e.g. pause the player again I have to switch to another working radio stream. Once I do that I get sound, and I can again control the player.

**Comment by bj61251** [comment]
Deezer, Plex, and Twitch work for me; podcast urls from  news sites are having the issue.

**Comment by majbom** [comment]
As per request:
I'm not sure if it's related, but I see this error when trying to play some tracks
```
2024-03-31 19:12:48.564 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/item_by_uri: 'streamingData'
2024-03-31 19:12:50.589 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/queue/play_media: 'streamingData'
```

**Comment by marcelveldt** [comment]
This issue should be fixed in beta 130 !
Please test and report back, thanks!

**Comment by Profex** [comment]
> This issue should be fixed in beta 130 ! Please test and report back, thanks!

Many thanks!
After updating to beta 130 the TuneIn Radio stream issue I reported above is resolved, I can again play and hear the radio stream via music assistant

**Comment by michaeldufour** [comment]
So far no issue with the last release, thanks Marcel!
