### ISSUE TITLE
Local mp3 files called with media_play don't play, but they also hijack the player in a silent loop

### ISSUE THREAD

**Issue by arretx** [music-assistant/hass-music-assistant#2083]
### What version of Music Assistant has the issue?

2.0.0b129

### What version of the Home Assistant Integration have you got installed?

2024.3.5

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Prior to the most recent update, I was using NodeRED to call the following service:

```
service: media_player.play_media
data:
  media_content_type: audio/mpeg
  media_content_id: >-
    media-source://media_source/local/soundFx/sensor/tasks_completed_count/default/giggle.mp3
target:
  entity_id: media_player.picoreplayer2
```

When I do this now, either from NodeRED or from the Services tab in the developer tools, the PicorePlayer2 appears to play the correct file, but I hear nothing, and it replays the same thing over and over again, never stopping.

While monitoring the state of `media_player.picoreplayer2` in the states list, I see the following for `media_content_id` in the attributes:

```
media_content_id: url://track/http://192.168.1.101:8123/media/local/soundFx/sensor/tasks_completed_count/default/giggle.mp3?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1MWM3NWFiZWY1NDE0ZGU3YWRhZGM0NTNmMzJjMzkyYiIsInBhdGgiOiIvbWVkaWEvbG9jYWwvc291bmRGeC9zZW5zb3IvdGFza3NfY29tcGxldGVkX2NvdW50L2RlZmF1bHQvZ2lnZ2xlLm1wMyIsInBhcmFtcyI6W10sImlhdCI6MTcxMjAwNTc1OSwiZXhwIjoxNzEyMDkyMTU5fQ.CNmUv25AwrOGp08mTmBvr7FlY_cvWewx3IXJTC72HoM
```

However, if I open Music Assistant from the sidebar and browse the local folder tree to find this file (giggle.mp3), then select the PicorePlayer2 player, and play the file, it plays one time and stops like expected.

The state of the PicorePlayer2 shows a much different value for media_content_id:

```
media_content_id: library://track/554
```

I can't figure out how to replicate this using NodeRED or the Services tab, as I'm unable to figure out what services is being called, and I have no idea how to identify track numbers like this.  There's zero reference to the file having a track number.

What's the fix for this?

### How to reproduce

Play a local mp3 file using media_player.play_media

### Music Providers

PicorePlayer

### Player Providers

I've tried using media_player.play_media and the MA interface.

### What version of Home Assistant Core are your running

2024.3.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
No doubt Marcel will look at this further but you should only be playing back tracks that are in the MA library, the URI of which is shown as `library://track/554` Have you read the FaQs about this? https://music-assistant.io/faq/how-to/

**Comment by OzGav** [comment]
There will be all sorts of problems with this. Firstly, there is an open issue for trying to playback music files as an announcement. So if you are trying to do that it probably won’t work. Secondly, MA will not like it if you try to import a music file which isn’t tagged properly. So if you are just trying to playback this file then tag it, import it into the library and then play it like any other track.

**Comment by OzGav** [comment]
As for referencing the track number look at he mass.play_media service call

**Comment by arretx** [comment]
I'm still lost.  I can't figure out where library://track/544 came from.  How can I reference a track if I don't know the address to the track.  I only know the folder structure, and in this case, in HA terminal, it would be:

`/root/media/soundFx/...etc.`

I'm also not sure what the difference would be between playing an mp3 file that's a full song in a library of music and a short sound effect when an automation fires off.  In other words, what's the difference between just playing music and playing an "announcement?" 

I'm also not typically importing music files into MA.    I don't use MA for anything other than Spotify when it comes to playing music to listen to, so I don't have any local music files (i.e. library burned from old CD's or downloaded mp3 files.). The only use case scenario that I have is creating sound effects for various conditions and automations that play over my media player and then through the whole house audio matrix.  Each entity that I configure to be "audio enabled" creates a folder in the soundFx folder which is mapped using the storage feature in HA.  For example, I take an entity, like sensor.tasks_completed_count, and I automatically generate a folder structure for that entity.  In this case, it would be `/soundFx/sensor/tasks_completed_count/default/<files.mp3>`.

In that folder there may be one or many mp3 files which are chosen randomly and are played to media_player.picoreplayer2 whenever called as a result of an automation.

So, it doesn't seem to make sense to import all of these sound effects as tracks into MA when they're one-off "chimes" so to speak that don't require something like MA.  It seems like MA sort of takes over when it's installed.

Should I do a short screen capture of the struggles that I'm facing?  It's all very confusing at this point.

**Comment by OzGav** [comment]
If you look here https://music-assistant.io/faq/how-to/ there is a section on how to get the URI. In your case you could use the mass.search service call to find the library item_id and the full URI.

With an announcement, MA will pause the currently playing track, play the announcement and then resume the track. This works when sending a TTS message but not if trying to send an MP3 as an announcement. I can't tell from your original report what you are trying to do.

If you don't need the pause and resume feature of announcements with MA then don't send your sound effects to the MA players. Just send them to the HA players. If you do want to send them to the MA players then as I previously mentioned there is an issue with trying to send MP3 announcements at the moment.

**Comment by arretx** [comment]
Ahh...thanks.  I'm definitely not using it as an announcement.  I'm also not sure I understand which are the MA players and which are the HA players.  I've always called mp3 files using `media_player.play_media` then giving it a media-source://media_source/local/etc./etc./  to play the file.  I thought that _was_ using the HA players.  It used to be that I only had 3 google home speakers, but then I added a 6-Zone amp, and that needed input, so I added 2 picore players running on two independent RPi3s.  One is for music, and one is for playing sound effects.  When I installed MA, it assumed control of all of my media players, seemingly.  So I'm not exactly sure how to differentiate between HA media players and MA media players for the purpose of calling the services.  Thanks for your help on this.  I imagine once I get this all sorted out I'll do a write-up about how to make it easy to understand.

**Comment by OzGav** [comment]
You can see the MA players by going to HA SETTINGS>>DEVICES&SERVICES>>INTEGRATIONS>>MUSIC ASSISTANT

Anything else is a HA player and those are the entities that you should be targeting by the sound of it.

**Comment by marcelveldt** [comment]
We are working on issued playing local audio files from HA, this should be solved din the next beta

**Comment by grigi** [comment]
Would this be related to thousands of errors like so:
```
2024-04-02 20:28:21.065 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/controllers/webserver.py", line 209, in serve_preview_stream
    async for chunk in get_preview_stream(self.mass, provider_instance_id_or_domain, item_id):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 705, in get_preview_stream
    streamdetails = await music_prov.get_stream_details(track_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_stream_details'
```
when trying to play anything from a remote share filesystem?

**Comment by OzGav** [comment]
What beta version of the server are you on?

**Comment by grigi** [comment]
Server version: 2.0.0b129

**Comment by OzGav** [comment]
Your issue doesn’t appear to have anything to do with this one so open a new one if you are unable to play any local files. Make sure you cover everything the issue template and the troubleshooting page requires.

**Comment by arretx** [comment]
> We are working on issued playing local audio files from HA, this should be solved in the next beta

Thanks Marcel.  Greatly appreciate the project and how quickly you guys work and respond.  I'll hang tight.

**Comment by marcelveldt** [comment]
This one should be fixed in beta 130!

**Comment by arretx** [comment]
Sure enough, it works like a charm.  To clarify, when calling the following using a NodeRED service call node:

Domain: media_player
Service: play_media
Entity: piCorePlayer2

with the following data:

```
{
    "media_content_id": "{{{payload.sound}}}",
    "media_content_type": "audio/mpeg",
    "entity_id": "media_player.picoreplayer2" (not necessary defined in the node, but overrides if present in the msg.)
}
```

As long as the amp is on, the zone is active, and the input source is tuned to the media player playing the mp3 file, it fires off right away and no longer loops silently.

Thanks for the fix.

**Comment by arretx** [comment]
Greetings Marcel.  The problem is back with the most recent update.

**Comment by OzGav** [comment]
Please try again with beta136

**Comment by OzGav** [comment]
We will close this soon if there is no further follow up
