### ISSUE TITLE
Grouped players anomalies

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#2204]
### What version of Music Assistant has the issue?

b145

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I activated the MA integration with adoption of the players (3 chromecast and a group).
MA it’s casting to the CC everywhere group.
The individual Mass players in HA continue to state they are idle and not part of a group.
CC group:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/4ec6f742-cb46-4d34-9c30-fa9bc72cf05b)

CC player:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/fd328470-d441-475a-a6ed-b2df8f258612)

In MA UI they look as 4 independent players (although group volume works). I thought groups where graphically collapsed?!:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/f966e21e-779e-41c5-ac67-ba31c2c340fd)

### How to reproduce

As explained 

### Music Providers

Spotify

### Player Providers

CC

### Additional information

Mass Player states in HA:
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/84b6bbb9-4813-4af9-9071-7e5e1924c2d8)

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
In my player list in MA it is clear the child players are part of the group and they cannot be individually selected.

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/08e37be9-fef6-4d59-9945-dd3cac874f38)

That is the normal indications as you are able to individually control the child volumes. The hiding of child players I think occurs with other player types but not with Chromecast?

In terms of state HA shows what MA shows, that the individual players are idle. This does seem to be iin conflict with the HA docs which say that:

> IDLE: Entity is turned on and accepting commands, but currently not playing any media.

Will see what Marcel says about that.

**Comment by OzGav** [comment]
Another grouping anomaly

https://github.com/music-assistant/hass-music-assistant/assets/19848947/6c3d1873-0489-440b-9d95-616a75b7ae63

**Comment by erkr** [comment]
Issue still persists in 2.0.0rc1
![image](https://github.com/music-assistant/hass-music-assistant/assets/4363599/3af3e240-e716-4e08-b0d5-f50852633496)

**Comment by marcelveldt** [comment]
this one is fixed in 2.0.0

**Comment by OzGav** [comment]
I am still seeing the grouped suffix after ungrouping. Also it took a tab refresh to get the kodirumpus player to show the grouping was removed
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/94135071-c39d-4744-aa19-5f3169eefd2a)

**Comment by OzGav** [comment]
And then when I tried to group the other way (Kodirumpus to the amplifier) I get

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/79d4f472-b74c-4a2d-8e98-b0d6acc13159)

**Comment by erkr** [comment]
> this one is fixed in 2.0.0

I'm afraid not, as I tested against 2.0.0 yesterday.

**Comment by marcelveldt** [comment]
> I am still seeing the grouped suffix after ungrouping. 

Please create a new issue report for a new issue

**Comment by marcelveldt** [comment]
> Update: My mistake, I must have tested against 2.0.0rc1

OK great so its fixed now
