### ISSUE TITLE
Playlists managed by the music-assistant provider contain only 50 songs

### ISSUE THREAD

**Issue by UriaKesarii** [music-assistant/hass-music-assistant#2221]
### What version of Music Assistant has the issue?

2.0.0b148

### What version of the Home Assistant Integration have you got installed?

2024.5.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Playlists managed by the music-assistant provider inexplicably contain only 50 songs, despite the original playlist containing more than 50 songs. 

In my case the playlists contain songs from the filesystem (local disk) provider

If we go to the file that displays the playlist located at data/playlists/file, we can see more than 50 songs.

### How to reproduce

Go to the dashboard, find the playlist section, select a playlist managed by the music-assistant provider, and you'll see only 50 songs.

### Music Providers

Music Assistant provider

### Player Providers

Chromcast

### What version of Home Assistant Core are your running

2024.5.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Also the first track of the playlists have no track number

**Comment by UriaKesarii** [comment]
I noticed that even in playlists imported from Spotify there is a similar problem. That is, although there are more than 50 songs in the queue, after 52-51 songs, the songs start repeating themselves. For example, if the original playlist contains 200 songs, when it plays in the queue, there will only be about 50 songs, even though there are many more; it just keeps looping.

How to reproduce:

Play a playlist with songs from Spotify, enter the queue, and count 51 songs from there. You'll notice that the songs repeat themselves

**Comment by OzGav** [comment]
Just tested and songs do not get added to the playlist I have with fifty songs. It works with a smaller playlist. Errors are thrown 
[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15281713/log.txt)

**Comment by marcelveldt** [comment]
> Just tested and songs do not get added to the playlist I have with fifty songs. It works with a smaller playlist. Errors are thrown [log.txt](https://github.com/music-assistant/hass-music-assistant/files/15281713/log.txt)

This issue seems completely unrelated to the original issue mentioned in this ticket ?
The original issue from this ticket should be resolved in 2.0.1 but @UriaKesarii please confirm.

**Comment by OzGav** [comment]
Actually yes it looks like my playlist entries have been lost when it was truncated to 50 tracks and now I can’t add to that playlist but I see more than 50 in my Spotify playlist. I’ll close this and open a new issue

**Comment by jicka** [comment]
Hello,
Not the original poster, but I've been watching from the beggining as I have the same issue. It is not fixed for me in 2.0.1 running the 2024.5.1 integration.

To test the fix in 2.0.1 I have created a new .m3u playlist and opened it in MA (using the local filesystem provider). The playlist loads but only lists 49 songs. The .m3u file is as simple as possible (only relative file paths), contains 354 songs and opening the file in VLC shows all the files. 

If I can contribute more information, please let me know.

**Comment by OzGav** [comment]
The root cause of this has been identified. Expect a fix next update. Thanks for followup @jicka

**Comment by UriaKesarii** [comment]
Hey @marcelveldt , it's possible I'm missing something, but my server is version 2.0.1 and still, all the playlists managed through the music assistant provider contain no more than 50 songs. Additionally, the issue persists as there are only 52 songs, resulting in the same songs repeating.

Also, another thing, I entered a playlist managed by the music assistant and clicked refresh. What happened was that the number of songs doubled, but it was the same fifty songs that were there before. In other words, the first fifty songs remained the same, and songs 50 to 100 were the same fifty songs as before (in the same order).

**Comment by UriaKesarii** [comment]
Hi @marcelveldt with 2.0.2 the problem of only 50 songs in the playlist was resolved. thank you very much.
But note that from the Spotify and local file music providers (I have these providers but I assume that the problem is common for all providers) the queue contains only 50 different songs the songs in the 51 until 100 are the same as 1 unit 49.

**Comment by jicka** [comment]
Thank you for the fix in 2.02. MA now loads chunks of 50 songs when loading a playlist. At 149, it stops loading more. Still the same bug ?

I tested duplicating the playlist to ensure it was cleanly loaded in 2.02, with no success.

It's probably not a common use-case, but I have a playlist with 354 songs that just play in the background.

**Comment by OzGav** [comment]
I am watching this as there are a number of problems being identified. If need be I will ask for a new issue but just wait for now.
