### ISSUE TITLE
All albums tracks are listed twice with Plex music provider

### ISSUE THREAD

**Issue by SirJohnDoe** [music-assistant/hass-music-assistant#2319]
### What version of Music Assistant has the issue?

Stable 2.0.4, Beta 2.1.0b0

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

All albums tracks are listed twice: once with an icon of the original source, once as 'in library'. The consequence is that every album that is queued will be played twice as it also adds these duplicate tracks.

### How to reproduce

Sync a Plex music library. It looks like below. When sorting by track number it will show the 'in library' tracks at the top, and the Plex tracks at the bottom.

![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/6816bbbc-62e1-477d-84cf-863c2fa5b41e)

### Music Providers

Plex

### Player Providers

UPnP player provider

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15346980/log.txt)

### Additional information

I've added the Plex music provider again in Beta, and strarted from scratch in the stable release. In both cases it happened.

Unmarking the 'In library' tracks as favourite has no effect.

### What version of Home Assistant Core are your running

2024.5.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by jonrbloom** [comment]
I'm seeing this too (on HA Yellow). I am using Music Assistant for the first time and assumed I'd messed up my library while tinkering. So I did a clean reinstall of the Addon (not just the Plex component), with the same results.

**Comment by sfnis** [comment]
I had this issue as well, I removed Plex as a provider, and went to just filesystem.

**Comment by SirJohnDoe** [comment]
> I had this issue as well, I removed Plex as a provider, and went to just file system.
> 
> You can see the File system provider is not picking up the metadata correctly. Plex shows it as Disc 1 - Track 08, but MA shows it as 0/0.
> 
> The response here currently seems to be "fix your metadata" but I have many albums that work _fine_ in Plex, and are still incorrect in MA. There should be some sort of feature request to be able to disable MA Metatdata matching for a provider... but ... I am not sure how that would work.
> 
> Also, @SirJohnDoe if the file is tagged correctly, post a screen shot of that here. I use this for tagging: https://www.softpointer.com/tr.htm

Unfortunately that's not really a solution then, I rely on Plex for correct(ing) metadata, and don't want to start editing all the files and maintaining it with extra tools.

I got the impression that the built in music provider for some reason duplicates all tracks (and favourites them), and for some reason you're not allowed to disable it.

**Comment by OzGav** [comment]
> I got the impression that the built in music provider for some reason duplicates all tracks (and favourites them), and for some reason you're not allowed to disable it

The favouriting thing is subject to a separate issue report. Note sure what you mean by duplicating tracks?

Marcel has worked hard to ensure MA compies with established standards. Just because something works "fine" in Plex does not mean there is a problem with MA as perhaps Plex has implemented some hack workaround.

**Comment by sfnis** [comment]
Does requiring the folder name to match exactly the album name, ignore the id3 tag meet established standards?

**Comment by OzGav** [comment]
If you would like to contribute constructively to the project you can submit a PR

**Comment by OzGav** [comment]
> You can see the File system provider is not picking up the metadata correctly. Plex shows it as Disc 1 - Track 08, but MA shows it as 0/0.

That is not what is happening based on the reporters own words. 

> All albums tracks are listed twice: once with an icon of the original source, once as 'in library'. 

So the issue is as described by the OP that there appears to be a problem with the Plex provider duplicating the tracks (not the file system provider) but for some reason this is not widespread as this is the only report.

**Comment by jonrbloom** [comment]
Not the only report (as mentioned, I see the same thing), but it is fairly low report rate certaintly..

I will try updating to latest Plex server, but note that Bubble uPnP on Android doesn't duplicate. Not definitive proof that it's MA specific, but lends some weight.

What can we do to help isolate the cause?

**Comment by sfnis** [comment]
I experienced the duplicate file issue as well. 

I’d guess that part of the low report rate is that the Plex provider is listed as not being actively developed and users being encouraged to just use the file system provider.

**Comment by jonrbloom** [comment]
Ok, thanks. Yes, all albums that I tried exhibit the problem.

**Comment by Paul-Vdp** [comment]
I just noticed I am suffering from the same problem ...
As I guess all Plex users will (of which there must be many).

**Comment by vhsdream** [comment]
Seems to be fixed on 2.1.0b4, at least for me - whatever was done for this version has made using the Plex provider pretty damn awesome. Thank you!

**Comment by OzGav** [comment]
@SirJohnDoe please confirm this has been fixed in 2.1.0b4

**Comment by jonrbloom** [comment]
Strange, I tried the beta version of the addon (2.1.0b4), but it's not fixed for me.

**Comment by OzGav** [comment]
@jonrbloom Any chance you can remove the Plex provider to clear out all the duplicates and then try again?

**Comment by jonrbloom** [comment]
It's a clean install of BETA  (i was using the release version previously). So my library was already empty.

Note also that I see this when I use the Browse  folder to look directly at the Plex media assets.

**Comment by OzGav** [comment]
@Paul-Vdp if you can help out with optimising the DB that would be great.

**Comment by vhsdream** [comment]
I would like to rescind my previous comment about the duplication being fixed. It looks like I may have found the outlier that was not duplicated and thought it was fixed. I can't recall which album or artist did not have duplication at the time I checked, but will keep looking for it to see if there is anything different. But for now I am having the duplication issue with every album I've looked at so far (but want to be clear that the album entry is **not** duplicated, it is only when clicking into the album that the tracks themselves are).

**Comment by marcelveldt** [comment]
The Plex API for music items is.... not great... It misses info such as Album artists and disc and track numbers.
Important info that is needed for matching and presenting the right info. I'll see if I can patch some more bandaid into the Plex provider again but its getting harder and harder for me to recommend the Plex provider if you care about your music.

Don't get me wrong, I really like Plex and I use it daily but for music its just plain crap, its entire datamodel is based around movies and tv shows and they tried to squeeze music in there. Maybe it works ok-ish in their own apps (where they probbaly worked around the quirks) but for an external party talking to their api this is not so great.

If anybody wants to help with improving the Plex provider please contact us as we currently do not have an active maintainer on it and me and the other MA core devs are maintaining it on a best-effort base.

**Comment by marcelveldt** [comment]
> As a side note : as a developer I would take a long hard look at my database design when noticing it takes Hass so awful long to get rid of all the info associated with a certain music provider upon deleting the latter. I dare say that with an optimised design such operations could be almost instantaneous ...

Works is in the progress for further optimizing. The design is rather complex due to all the provider linking and relation so we choose the safe way on removals which is bad for speed. We're even hitting some sqlite limitations. We get some help from database experts but their time is also limited for contributing to an open source project. So unless you are willing to PR some optimizations I'm going to ignore your comment here ;-)

**Comment by jonrbloom** [comment]
@marcelveldt: Thank you for the summary on why this is much harder than it sounds. It seems that we should not hold out on Plex, if the API is such a poor fit for music, and look for alternatives. I'm going to switch to smb i think 

DLNA would be a better alternative for MASS, as it increases the reach beyond just Plex based music libraries, and is music savvy. It is  a very heavy lift though, and I hear you on maintainer shortages. But, I wonder, could you instead connect HASS's media sources (which already supports DLNA servers) to MASS in a similar way to the existing HASS Player provider? Of course that's still that's more work for another non-existant maintainer. Just throwing it out as an idea for the roadmap.

**Comment by marcelveldt** [comment]
> @marcelveldt: Thank you for the summary on why this is much harder than it sounds. It seems that we should not hold out on Plex, if the API is such a poor fit for music, and look for alternatives. I'm going to switch to smb i think

I think our own file providers are better than Plex atm as they read the ID3 tags as-is.
There may still be bugs in there bug that I can influence and fix. I can fix the Plex API if you know what I mean. 
Yet somebody with more knowledge of the Plex API may know better and maybe has a few more tricks.
I will at least put a patch in the code for the disc/track numbers (and just ignore the zero numbered ones) in Plex but there is only so little we can do.

> DLNA would be a better alternative for MASS, as it increases the reach beyond just Plex based music libraries, and is music savvy. It is a very heavy lift though, and I hear you on maintainer shortages. But, I wonder, could you instead connect HASS's media sources (which already supports DLNA servers) to MASS in a similar way to the existing HASS Player provider? Of course that's still that's more work for another non-existant maintainer. Just throwing it out as an idea for the roadmap.

The HA music sources lack even more metadata than the Plex api so while it may be tempting to use them, longer term it wont.

**Comment by jonrbloom** [comment]
Thank you, that all makes sense. I wondered why only the Players had a HASS connection.

... and thanks to the whole MASS team. It's an awesome piece of software. I am so pleased that I can finally kick Sonos into touch.

**Comment by marcelveldt** [comment]
Fixed the code to prevent the duplicate albumtracks listing. The fix will be available in the next version (2.0.7 stable or 2.1.0b6 beta)

**Comment by Paul-Vdp** [comment]
Well ... installed 2.1.0b6 beta, did the same steps as mentioned in my previous comment, only to find that the double tracks still were there.
Just to make sure : are there any additional steps to take, or another procedure to be followed to get it right ?
If not, then I'm afraid we have to conclude it is not yet fixed ...

**Comment by SirJohnDoe** [comment]
> @SirJohnDoe please confirm this has been fixed in 2.1.0b4

I was not able to test in the last 2 weeks. But I just tried in beta 2.1.0b8 and it did not seem to be fixed. It still happens even when removing and adding Plex again.

**Comment by dutchmendesign** [comment]
Same issue here. Double list and MA showing disc 0 song 0, ID3's are up to date.
I have HA and Plex on same PI5 system, so the music files are in /media.
Would prefer the Plex DB, because it gives a more clean result (VA albums), so i would rather disable the MA provider; MA is eating a lot of RAM. There is a DB already after all.

**Comment by marcelveldt** [comment]
> Would prefer the Plex DB, because it gives a more clean result (VA albums), so i would rather disable the MA provider; 

Can you give some insights what you mean here ? Note that the Plex API is super limited so some of our issues are caused by that, for instance its not returning the disc and track numbers and album artists which is really annoying. 

> MA is eating a lot of RAM too. There is a DB already after all.

Can you give some insights ? Memory usage should be minimal (except when initial scan is running.

> Anyway, will try MA without Plex and see what happens.

Please do so and let us know. I can have influence over the MA provider and optimize that but i cant fix the Plex API if you get what I mean.

**Comment by marcelveldt** [comment]
I've spend a bit of time with the plex api and MA provider for Plex and was able to reproduce and fix the issues.
The data from Plex API is still a bit limited compared to everything we can read from the tags but it will at least be correct/working with the changes.

The fixes are available in the next beta (2.1.0b12) but I'm afraid a fresh install is going to be required to cleanup the mess in the database (or at least re-add the plex provider)

**Comment by jonrbloom** [comment]
> The fixes are available in the next beta (2.1.0b12) but I'm afraid a fresh install is going to be required to cleanup the mess in the database (or at least re-add the plex provider)

Thank you, you're a star. Fresh install is a small price to pay 😁

**Comment by marcelveldt** [comment]
Please keep it open until confirmed solved

**Comment by SirJohnDoe** [comment]
Yay, it works! I only had to remove Plex as provider, wait for MA to clean up and then add it again. Thanks!

![image](https://github.com/music-assistant/hass-music-assistant/assets/11654657/9c1a1663-7965-4713-8d72-2e01ee612b70)
