### ISSUE TITLE
V1.1.15: relative paths playlists supported?

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#241]
Hi
This issue is not specific since v1.1.15. It is in from the beginning, but didn't have time to look into them earlier.

In my local collection I have several basic playlists. only the tracks, no paths. These playlists are located in the same folder as the tracks.

MA logs this error when parsing these playlists:
```
Logger: music_assistant.mass.music.file
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py:324 
First occurred: 14:48:38 (10 occurrences) 
Last logged: 15:02:21

Error while parsing playlist /media/MP3_normalized/Various/Hit History 1955-1985/63.m3u
Error while parsing playlist /media/MP3_normalized/Albums/Children Of Bodom/(2005) - Are You Dead Yet/Children Of Bodom - Are You Dead Yet.m3u
Error while parsing playlist /media/MP3_normalized/Albums/Guns N Roses/Greatest Hits/Greatest Hits.m3u
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 319, in get_playlist_tracks
    if track := await self._parse_track_from_uri(line):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 785, in _parse_track_from_uri
    return await self.get_track(uri)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 269, in get_track
    itempath = await self.get_filepath(MediaType.TRACK, prov_track_id)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/music/providers/filesystem.py", line 834, in get_filepath
    for db_row in await self.mass.database.get_rows_from_query(query):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/helpers/database.py", line 104, in get_rows_from_query
    return await _db.fetch_all(query, params)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 149, in fetch_all
    return await connection.fetch_all(query, values)
  File "/usr/local/lib/python3.9/site-packages/databases/core.py", line 271, in fetch_all
    return await self._connection.fetch_all(built_query)
  File "/usr/local/lib/python3.9/site-packages/databases/backends/sqlite.py", line 93, in fetch_all
    async with self._connection.execute(query_str, args) as cursor:
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/context.py", line 41, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 184, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/usr/local/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: near "m": syntax error
```

Although these playlists are added to the playlist tab, they are empty!

Content of one of these playlists mentioned in the log above: 'media/MP3_normalized/Albums/Guns N Roses/Greatest Hits/Greatest Hits.m3u':
```
01 - Welcome To The Jungle.mp3
02 - Sweet Child O' Mine.mp3
03 - Patience.mp3
04 - Paradise City.mp3
05 - Knockin' On Heaven's Door.mp3
06 - Civil War.mp3
07 - You Could Be Mine.mp3
08 - Don't Cry (Original).mp3
09 - November Rain.mp3
10 - Live And Let Die.mp3
11 - Yesterdays.mp3
12 - Ain't It Fun.mp3
13 - Since I Don't Have You.mp3
14 - Sympathy For The Devil.mp3
```

**Comment by marcelveldt** [comment]
It should be supported but I think something broke somewhere/somehow. I'll have a look

**Comment by erkr** [comment]
Thanks!

**Comment by marcelveldt** [comment]
stupid typo in the code. fixed it while doing the rework for multi artist albums

**Comment by marcelveldt** [comment]
Fix released in 1.1.17

**Comment by erkr** [comment]
Errors in the log are gone.  Playlist still doesn't load. Is the action refresh item enough to reload the playlist?

**Comment by marcelveldt** [comment]
Yeah refresh should be enough, I must be overlooking something. I'll do some more testing.
BTW: just to be sure you could try to make a small change in the playlist file so the checksum changes, which will trigger a fresh scan.

**Comment by erkr** [comment]
> BTW: just to be sure you could try to make a small change in the playlist file so the checksum changes

I tried that by changing the file from windows to inbox format and back. No diff.
Also verified : When adding the path to the tracks, it works fine

**Comment by erkr** [comment]
Small update:
Just re-opening a playlist is already enough to trigger a refresh
Windows and Unix format both supported.
relative paths don't work:
- works: `/media/MP3_normalized/Albums/Guns N Roses/Greatest Hits/01 - Welcome To The Jungle.mp3`
- doesn't work: `/01 - Welcome To The Jungle.mp3`
- doesn't work: `./01 - Welcome To The Jungle.mp3`
Playlist file is in the same folder as the tracks

**Comment by Clusters** [comment]
Can we reopen this issue, as this seems not to be fixed yet. Or have you got relatives paths working @erkr ?

I get this error within the logs, whenever using relative paths. 
`2022-12-09 13:08:54.614 WARNING (MainThread) [music_assistant.music.file] Could not parse uri/file ..\Various Artists\Bravo Hits 47\1-02 Blue Lagoon - Break My Stride.mp3 to track: Not a valid Music Assistant uri: ..\Various Artists\Bravo Hits 47\1-02 Blue Lagoon - Break My Stride.mp3`

I have a read only file system, that syncs from my NAS to my Home Assistant system. The file systems are different in structure and I can't have the playlists working on both systems because of that, unless I use relative paths.

**Comment by Clusters** [comment]
Thanks @erkr, it seems that my list got indexed after 2 days. I check this later and come back to this.
The issue could be, that lists in general can take a long time to index. Another proper (absolute paths) list with 512 items in it, took around 3 days to index.
