### ISSUE TITLE
Local files not visible in browse view

### ISSUE THREAD

**Issue by canedje** [music-assistant/hass-music-assistant#2411]
### What version of Music Assistant has the issue?

2.0.4

### What version of the Home Assistant Integration have you got installed?

docker standalone

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After my Unraid server crashing ans restart.
Music-=Assistant is not showing my local disk content.
THe directory is there but empty.
I did create a /media mount to the right local music directory
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/8b21e72d-8d6c-4836-836b-21da32026529)
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/82df02e8-8f4c-456e-8711-cfc109188253)
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/6617c22f-5e70-4bd7-b81e-3838b217b7f8)

EDIT: It is possible to play music from local disk by using the search function

### How to reproduce

It happens all the time

### Music Providers

![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/f0710c11-f969-48a7-a7fb-55070670333d)
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/4c4d65da-9d0c-4841-bed4-082377cbcd35)

### Player Providers

![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/ce63cc18-c2ea-46b3-a73a-b8740795dd85)

### Full log output

[musicassistant.log](https://github.com/user-attachments/files/15570676/musicassistant.log)

### What version of Home Assistant Core are your running

standalone

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
I think this is just a front end problem in browse view. You are reporting playback is working so that is all that really matters. Use the other views to find your music (or search). This will be looked at in due course.

**Comment by canedje** [comment]
> I think this is just a front end problem in browse view. You are reporting playback is working so that is all that really matters. Use the other views to find your music (or search). This will be looked at in due course.

I do not know what that means.
Not all music is available. If I do a search only a part of the localfiles are findable
I did remove everything and started over.
But still the local files are not visible

**Comment by OzGav** [comment]
Probably a tagging problem then. Check the logs and the docs

**Comment by mcarty2** [comment]
My behavior is that I  cant browse subfolders in filesystem (local files), only the files at the top folder are showed.

**Comment by Ay1tsMe** [comment]
This is also a problem with network storage devices. It only shows a few of the items rather than all the folders. The songs are getting imported and tagged correctly but not showing up in the browse section. Music Assistant is showing 13 items whereas there should be 288

![image](https://github.com/music-assistant/hass-music-assistant/assets/110982014/4c71f967-3470-41b8-9302-1534b0f52957)
![swappy-20240611-202420](https://github.com/music-assistant/hass-music-assistant/assets/110982014/b6062ee1-ebf8-4416-85a1-e82b281b1f1a)

**Comment by marcelveldt** [comment]
Does the music show up in the library (artists, albums, tracks ) ?

**Comment by OzGav** [comment]
> Does the music show up in the library (artists, albums, tracks)?

Everything else was working fine when I tried it but only one folder was visible.

**Comment by Ay1tsMe** [comment]
> Does the music show up in the library (artists, albums, tracks ) ?

Yes, the music's metadata is grabbed and is playable in all the views except the browse location.

**Comment by canedje** [comment]
Not for me. Only partitional

**Comment by canedje** [comment]
I did try again.
I think I can find all music bij using the search function.
This only works if I do search on the directory of the music.
For example:
Search Elvis presley (thats a directory in my music file system:
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/9b30d64c-3a30-4b09-a662-2b35e311f5ff)
then I do find the directory in the way:
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/abb8aa61-1b0d-4b2e-aa74-aaedc3d73cb8)
![image](https://github.com/music-assistant/hass-music-assistant/assets/23150947/a633496f-9e08-4cfc-93dc-385aaff2bc61)
Its not easy, but I can find at the end the localdisk music

**Comment by OzGav** [comment]
@canedje i think you are confused about how MA works. It doesn’t replicate your directory structure. In your second image you are viewing an alphabetical listing of all Elvia Presley tracks.

**Comment by OzGav** [comment]
The issue with browse now showing Al folder is fixed in the latest server versions

**Comment by Ay1tsMe** [comment]
Just updated and I still have the issue. 

While I can see more folders (it now shows 52), all the folders are still not visible. I've noticed some strange behaviour where some of the folders are not visible unless I change how the list is sorted.

Here is what MA detects
![image](https://github.com/music-assistant/hass-music-assistant/assets/110982014/49d29326-ad74-4794-a8fd-5b289a7053c4)

Here is the real folders:
![image](https://github.com/music-assistant/hass-music-assistant/assets/110982014/4ad33fed-4349-46dd-8242-fdea80df20ae)

If I sort the list alphabetical "Yes - The Yes Album (1971)" will not appear but if I sort by original it does:
https://picoshare.tuxtower.net/-fgzHFS7crK

And many other folders are not present at all but are detected and parsed in categories such as artists. For example this "Wham" folder:
https://picoshare.tuxtower.net/-CJq6RxLb4X

**Comment by OzGav** [comment]
Quite right I didn’t look closely enough and interestingly I also only see 52 folders so that will be a clue!

**Comment by canedje** [comment]
My directory structure is back again.
Thanks

**Comment by mcarty2** [comment]
Fixed for me too with the update. I can browse filesystem/local files folders now.

**Comment by MelHarbour** [comment]
@OzGav I see that behaviour too. If you look in the raw stream though, the number of data points returned is actually 50, not 52 (magic ones I suspect for up folder level). That, I think, points a finger of blame at something like this line:

https://github.com/music-assistant/frontend/blob/7553714d748b53ba29b52671586ab38108fa18be/src/components/ItemsListing.vue#L253

Defaults to a limit of 50 when fetching. I suspect a default like that needs overriding here.

**Comment by OzGav** [comment]
This has been fixed
