### ISSUE TITLE
Volume status bar doesn't update when changing volume with DLNA player

### ISSUE THREAD

**Issue by madbrain76** [music-assistant/hass-music-assistant#2514]
### What version of Music Assistant has the issue?

2.0 7

### What version of the Home Assistant Integration have you got installed?

2024.6.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When changing the volume on a WiiM DLNA device using the player controls, the volume does change, but the volume status bar does not.

### How to reproduce

1.Add DLNA player provider 
2. Select a WiiM DLNA player
3. Select content
4. Press play. Content starts playing
5. Use the volume control to change the volume
6. The playback volume changes, but the volume displayed remains the same
7. Start the WiiM app
8. Select the same player. The correct volume is displayed.
9. Change the volume..Both the level and screen view change
10. Go back to the MA player view
11. Observe that the volume bar has now updated

### Music Providers

Plex

### Player Providers

DLNA/UPNP

### Full log output

[log.txt](https://github.com/user-attachments/files/15906414/log.txt)

### Additional information

Will try with other DLNA players next.

### What version of Home Assistant Core are your running

2024 6 3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Windows

**Comment by madbrain76** [comment]
Same issue with Marantz SR7011 at step 6. I wasn't physically in the room, so didn't try to change the volume from the Marantz side using its remote.

**Comment by madbrain76** [comment]
Also tested this other DLNA remotes (JRemote2, MO4Media) and the problem does not occur there - volume changes updates the volume bar display too.

**Comment by JonathanKang** [comment]
My [ayino WR320](https://www.aoyint.com/english/wr320?v=b838b393d55f) has exactly the same issue.

**Comment by marcelveldt** [comment]
This is fixed in the current 2.1 beta of MA. The wait is now until we promote that version to stable

**Comment by JonathanKang** [comment]
The just released 2.1.0 version doesn't fix it for me. The volume bar still doesn't show the correct volume level.

**Comment by OzGav** [comment]
Have you tried clearing the MA cache?

**Comment by JonathanKang** [comment]
> Have you tried clearing the MA cache?

Nope. Do I need to do that for every update?

After clearing the cache, If I change volume in my DLNA speaker app(Legacy Player), it was instantly updated in MA web page and the MA media player(found in MA integration) info page. Thank you for the work!

But the volume doesn't sync between MA web page volume bar and media_player(created by MA integration) info page, if I change volume in either these two place.

Volume bar in MA webpage:
![Screenshot from 2024-07-24 15-43-53](https://github.com/user-attachments/assets/be8da0df-9b6d-4317-99eb-27c9046d3bf1)

volume bar in media_player info page:
![Screenshot from 2024-07-24 15-43-40](https://github.com/user-attachments/assets/d56d0163-c664-46d2-8969-33bbbf9c71d1)

If you need any further information, just let me know.

**Comment by OzGav** [comment]
Does the bar move at all between the two? DLNA has always been challenging due to poor standardisation of the protocol. Can you use Airplay with the Wiim?

**Comment by JonathanKang** [comment]
> Does the bar move at all between the two? DLNA has always been challenging due to poor standardisation of the protocol. 

Nope. There was no movement in the volume bar and the value didn't change as well.

> Can you use Airplay with the Wiim?

Actually I can. Using Airplay doesn't have this issue. I think I should use Airplay instead. Thank you for this information.

**Comment by OzGav** [comment]
I’ll just leave this open until @marcelveldt lets us know if this is something he wants to look at further.

**Comment by madbrain76** [comment]
I'm seeing slightly different behavior now with 2.1 .

In step 6, when I change the volume, the volume status temporarily displays the correct level. But a few seconds later, it reverts to showing the previous volume level.

**Comment by OzGav** [comment]
Whilst DLNA remains problematic due to poor standardisation there have been many changes since this report. Please confirm this is still an issue with 2.3.0 beta 25 or later

**Comment by madbrain76** [comment]
Yes, unfortunately, still an issue on b25.

**Comment by sunjaxx** [comment]
I have the same /similar issue (Jellyfin + DLNA player): the slider doesn't move when in "Now Playing View", although the volume does change...

![image](https://github.com/user-attachments/assets/986ae248-485c-4b7e-a914-00fe9015a478)

**Comment by marcelveldt** [comment]
DLNA is the crappiest protocol on earth. Issues like these are just part of the deal unless you try to workaround every single player specific issue. I do not have the time, nerves or patience to do that so DLNA comes at a best effort. Some players work great with it, some don't. Somewhere I regret a bit for even adding this provider to MA but at the same time for some people it does work....

I'm always open for PR's on the dlna provider to fix player specific issues but other than that I will not look at it.
Also note that in 80% of the cases it cant even be solved in software as its the hardware to blame (yeah the protocol is THAT bad).

OK, end of rant.
For WiiM owners I have some better news because the next major version of mA (2.4) will bring native Linkplay support so issues like this are gone.

**Comment by sunjaxx** [comment]
> DLNA is the crappiest protocol on earth. Issues like these are just part of the deal unless you try to workaround every single player specific issue. I do not have the time, nerves or patience to do that so DLNA comes at a best effort. Some players work great with it, some don't. Somewhere I regret a bit for even adding this provider to MA but at the same time for some people it does work....
> 
> I'm always open for PR's on the dlna provider to fix player specific issues but other than that I will not look at it. Also note that in 80% of the cases it cant even be solved in software as its the hardware to blame (yeah the protocol is THAT bad).

Please keep up the good work! how music assistant manages DLNA is actually the mean reason why I am using it (for example, it's the only program I found so far that can handle "scroll"/"search" *within* a track on my Yamaha DLNA).

But to be clear, the volume slider DOES work and DOES show correctly in the main "view" (see screenshot below), and DOES work - but DOES NOT show correctly - only in the "now playing view". Based on that, is that really a hardware / DLNA issue?

![image](https://github.com/user-attachments/assets/f1d84620-e849-4062-aa53-4e88123ba59b)

Thanks!

**Comment by marcelveldt** [comment]
> But to be clear, the volume slider DOES work and DOES show correctly in the main "view" (see screenshot below), and DOES work - but DOES NOT show correctly - only in the "now playing view". Based on that, is that really a hardware / DLNA issue?

Those 2 screens share the same data so that is not possible.
Maybe in the meanwhile a device update arrived and that was just coincidence ?
Did you test this with a recent version of MA (to rule out this is some old bug that has been solved already) ?

**Comment by sunjaxx** [comment]
> Did you test this with a recent version of MA (to rule out this is some old bug that has been solved already) ?

I updated MA and that solved it! Thanks.

**Comment by madbrain76** [comment]
Confirmed that this works as expected with a WiiM Pro Plus on 2.4.0b3 .
