### ISSUE TITLE
Main page "recently played" blank due to: "Field "track_number" of type int in Track has invalid value None"

### ISSUE THREAD

**Issue by ulflulfl** [music-assistant/hass-music-assistant#2593]
### What version of Music Assistant has the issue?

2.1.0.b13

### What version of the Home Assistant Integration have you got installed?

MASS is not (yet) connected to Home Assistant

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When opening the home page, the "recently played" portion of the main page remains empty and a short popup "Field "track_number" of type int in Track has invalid value None" appears for a moment.

![grafik](https://github.com/music-assistant/hass-music-assistant/assets/6313750/6c1f5a9c-6c85-4eb5-95e9-28d39b709287)

This is very likely related to issue #2585 

### How to reproduce

Play a track (very probably: That has no track number in the tags)
Open the home page: http://192.168.1.11:8095/#/home

### Music Providers

local disk provider

### Player Providers

Sonos

### Full log output

[log.txt](https://github.com/user-attachments/files/16119482/log.txt)

### Additional information

In the log line 9323 you'll find the corresponding issue/traceback.

### What version of Home Assistant Core are your running

none

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Confirmed

**Comment by OzGav** [comment]
As per the instructions can you please not include DEBUG logs unless requested. Looking through 9000+ lines is not helpful.

**Comment by ulflulfl** [comment]
Well, how do I NOT include the DEBUG messages? I took the docker image from ghcr.io/music-assistant/server:stable (in the meantime I switched to :beta) and never tweaked the log level settings. It seems DEBUG is the default and I don't even know how/where to change this ...

**Comment by OzGav** [comment]
Hmmm... that's interesting. I don't use the docker install so I will have to ask. The addon has it as an option within HA. You will find every provider has the ability to adjust the log level in the settings but don't do that as there are a lot.

**Comment by marcelveldt** [comment]
Do you have Youtube Music as (one of) your Music provider perhaps ?

**Comment by ulflulfl** [comment]
I cannot install the addon as I don't run HassOS but simply a collection of docker containers (beside other stuff on that machine). I connected MASS to HASS and I was expecting that there is an Integration to install, but that's not the case. Different story ...

No YouTube, I'm using local files (and sometimes the Radio Browser). Some of my local files are manually tagged (as Picard doesn't work with "one album in one file"). So I think what happens here is that I was playing a local file without a track_number tagged (which is perfectly possible) which then confuses the "recently_played" code parts.

**Comment by jicka** [comment]
Hello,
The same error message is happening with me, but I'm not the original author of the post. Feel free to ignore / remove if not relevant.

The error is shown for me when opening a local playlist (m3u file with only filenames). The logged error is:

``` log
2024-07-08 13:42:11.004 ERROR (MainThread) [music_assistant.webserver] Error handling message: music/playlists/playlist_tracks: Field "disc_number" of type int in PlaylistTrack has invalid value None
```

Nothing is logged prior or after.

Hope this helps narrow it down.
Thank you.

**Comment by OzGav** [comment]
Please check with beta 14 as this has resolved in my testing

**Comment by jicka** [comment]
After updating to b14 from an existing installation running b13, the issue persisted. I reinstalled the Music Assistant extension and everything works now for me.

Thank you !

**Comment by qupterra** [comment]
![Screenshot_20240709_231423_Home Assistant](https://github.com/music-assistant/hass-music-assistant/assets/61996247/f37f9ec4-8ffd-4514-a9d4-d4c330bb8a49)
I am still experiencing the same issue as @jicka, when trying to open a playlist .m3u file with just filenames.
My issue has also persisted with the upgrade to beta14 but I've not yet tried a reinstall.
@OzGav is it worth opening a new issue and dropping the logs in there?

**Comment by janstadt** [comment]
I also see this issue when making a request using the hass mass play service. 


Executed: July 9, 2024 at 8:28:10 PM
Error: Field "disc_number" of type int in Track has invalid value None
Result:
params:
  domain: mass
  service: play_media
  service_data:
    media_id: 10 HOURS BROWN NOISE Noise Blocker for Sleep, Study, Tinnitus , insomnia
    enqueue: replace
    entity_id:
      - media_player.gretas_room
      - media_player.noahs_room
  target:
    entity_id:
      - media_player.gretas_room
      - media_player.noahs_room
running_script: false

this is with the local file media provider.

**Comment by OzGav** [comment]
@qupterra It is a new issue
