### ISSUE TITLE
Skipping tracks in quick succession causes multiple streams to be sent to media player.

### ISSUE THREAD

**Issue by brian-maher** [music-assistant/hass-music-assistant#2612]
### What version of Music Assistant has the issue?

2.1.0b11

### What version of the Home Assistant Integration have you got installed?

2024.5.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When playing music using the Spotify provider, skipping multiple times in quick succession (before the next song is playing) will cause multiple streams to be sent to the player simultaneously. These multiple streams persist until MASS is restarted.

### How to reproduce

This is easily reproducible on my setup:

1. Play a Spotify playlist
2. Mash the "Next Track" button 3/4 times
3. There will be a short delay before multiple streams are sent to the player (using Airplay this manifests itself as 2 songs alternating every few seconds).

### Music Providers

Spotify

### Player Providers

Airplay

### Full log output

[mass.log](https://github.com/user-attachments/files/16181376/mass.log)

### Additional information

Whilst mashing the next button may seem rather obtuse, it's standard user behavior to skip a multiple tracks, and in my case it was triggered accidentally.

### What version of Home Assistant Core are your running

2024.5.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
This issue should be fixed in 2.1.0

**Comment by OzGav** [comment]
@brian-maher please update to 2.1.0 and confirm if this has been fixed

**Comment by brian-maher** [comment]
Thanks - have just tested and the behavior has changed, but it's still occurring. Now, instead of enqueuing 2 tracks, it's enqueuing every song that's skipped over in quick succession.  

I'll try do to some more digging.

**Comment by OzGav** [comment]
Any chance of a video to show what you mean?

**Comment by OzGav** [comment]
@brian-maher This should be fixed in 2.1.2 or 2.2.0b4 please confirm

**Comment by OzGav** [comment]
Closing assumed fixed
