### ISSUE TITLE
No playable items found error

### ISSUE THREAD

**Issue by nabahr** [music-assistant/hass-music-assistant#2631]
### What version of Music Assistant has the issue?

2.1.0rc2

### What version of the Home Assistant Integration have you got installed?

2024.7.1b0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I created a playlist with a track from Spotify. When I attempt to play the playlist on any speaker I get the following error.
`mass    | 2024-07-15 21:53:18.920 ERROR (MainThread) [music_assistant.webserver] Error handling message: player_queues/play_media: No playable items found`
This happens on google cast speakers as well as squeezelite speakers.
I tried creating the playlist as a music assistant playlist, as well as a spotify playlist from both within Music Assistant and in the spotify app.
The playlist still plays even with the error, although on the squeezelite speakers the track is added twice but that might be a separate issue.
If I play the same track directly, not via the playlist, there is no error.

### How to reproduce

Pick a spotify track (I don't know if it's specifically spotify, but that is the only music source I have) and add it to a new playlist. Play the playlist on the speaker. The error should be in the logs. When playing via a HA service call, the service call returns an error.

### Music Providers

Spotify

### Player Providers

chromecast
slimproto

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16240860/music-assistant.log)

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Linux

**Comment by OzGav** [comment]
Confirmed. This will be looked at in due course

**Comment by OzGav** [comment]
@nabahr Can you check again with the latest version as I can no longer recreate this

**Comment by OzGav** [comment]
Actually I do see this but not with all playlists?

**Comment by SiboutVanLoo** [comment]
I still have the issue using media in automations, but only when playing local media, YTm media is fine, somehow...
Playing the same media file thru MA works fine, so i'm puzzeled.
Use case: personal announcements in recorded MP3 files, (Dad's voice saying time to sleep, etc.)

Not shure if it's the same problem.
Updated, reinstalled,... (But did'nt dare to try the beta.)

error:
Fout bij uitvoeren actie
MediaNotFoundError: No playable items found

**Comment by marcelveldt** [comment]
fixed in 2.2.0 stable

**Comment by OzGav** [comment]
I no longer see the original issue. Closing.

**Comment by SiboutVanLoo** [comment]
Goodmorning, i still get the issue when using piper for tts.
Same with home assistant cloud.
Is it due to metadata not existing? Saw random metadate being added to prerecorded annoucements.
And piper generates audio stored locally, but just tags it with "longlistofwhateversymbols".
(The "annoucement - advanced" "service, or action" needs a pinpoint sound file, but my piper automation setup uses variables, for example, weather forecast.)

**Comment by OzGav** [comment]
@SiboutVanLoo you are posting about something different. The original post is about playlists. If you have an issue with playing announcements then open a new issue

**Comment by ZeFish** [comment]
Still have the issue here it seems... hard to know why but it worked before, like last week.

Gonne keep figuring this one out, can't play any music now, maybe a config somewhere. WIll keep posted if I find something
