### ISSUE TITLE
Two parallel Playlists: only the most recent one visible

### ISSUE THREAD

**Issue by ccoenen** [music-assistant/hass-music-assistant#2714]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I have two speakers in two rooms that I would like to be able to play different music at times. This *mostly* works, but here's one problem I came across: If I am playing two playlists, I can only see the most recently added playlist, the other one is _gone_ (even after selecting the other player!)

### How to reproduce

* Have a music provider (I use subsonic)
* Have at least two players set up (I am using one SONOS and one AirPlay), let's call them `Speaker A` and `Speaker B`.
* Select `Speaker A` and play something on it, in my example I'm playing a full album by some `Alternative Rock Artist`.
* Select `Spekaer B` and play something on it, in my example I'm playing a full album by some `Pop Artist`.
* Switch *back* to `Speaker A` and display its currently playing information. The currently playing track will be correct, but the playlist will be that of `Speaker B`.

![grafik](https://github.com/user-attachments/assets/d2606bd5-249e-4f68-accb-64b9e327e4fe)
![grafik](https://github.com/user-attachments/assets/5a3bfca2-0198-4144-8431-5e43bb2080f6)

### Music Providers

Subsonic

### Player Providers

AirPlay and SONOS

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16471295/music-assistant.log)
- I don't think anything in this particular log is of help.

### Additional information

All of the steps above were performed on the Music Assistant web client and *not* in HomeAssistant.

Home Assistant runs on x86_64 in a container
Music Assistant runs on a Raspberry Pi in a container

### What version of Home Assistant Core are your running

2024.7.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by ccoenen** [comment]
Interesting thing to note: once the second playlist is "done" playing, the first playlist will be displayed just fine.

**Comment by OzGav** [comment]
This is confirmed and will be addressed in due course.

**Comment by marcelveldt** [comment]
fixed in 2.2.0

**Comment by OzGav** [comment]
This is partially fixed. Whilst the different queues are displayed if you select between two players from the NOW PLAYING view the number of tracks shown changes. The number in the queue is always indicating correctly.

**Comment by marcelveldt** [comment]
try again with the 2.2.1 / 2.3.0b2

**Comment by OzGav** [comment]
Confirmed fixed.
