### ISSUE TITLE
Snapcast long delay - Snapserver buffer size setting appears to have no effect

### ISSUE THREAD

**Issue by TobiasLe** [music-assistant/hass-music-assistant#2763]
### What version of Music Assistant has the issue?

2.1.4

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When I play music via the built-in snapserver on my snapcast devices, it takes 8s before I hear any music after pressing the play button.

I tried to change the "Snapserver buffer size" in the Built-in Snapserver Settings, however, the delay always stays the same no matter if I set it to 500ms or 6000ms.

All that is not really problematic while listening to a playlist, but I also played around with some TTS announcements, and they also take 8s to start to play, and I would love them to be a bit more responsive. 

### How to reproduce

Play anything via the built-in snapserver and measure the time it takes

### Music Providers

radio-stream, YTMusic, HomeAssistant TTS

### Player Providers

Snapcast

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16624860/music-assistant.log)

### What version of Home Assistant Core are your running

2024.7.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by SantiagoSotoC** [comment]
@TobiasLe Have you tried using an external server?

**Comment by TobiasLe** [comment]
> @TobiasLe Have you tried using an external server?

@SantiagoSotoC  No, not yet. Is your setup more responsive? How long does it take in your case until music starts to play?

**Comment by SantiagoSotoC** [comment]
In general 2 seconds, but I am using the embedded server, how much ram do you have ?

**Comment by TobiasLe** [comment]
It's running on a Home Assistant Green, it has 4GB of ram.

**Comment by SantiagoSotoC** [comment]
There is only one optimization I can think of, it is to avoid using tcp sockets, in the embedded snapserver, it counts well and I have 4s delay

**Comment by TobiasLe** [comment]
Im a bit confused because you wrote "but I am using the embedded server". Is that something different than the built-in Snapserver that I am using?

And what about this setting:
<img width="598" alt="image" src="https://github.com/user-attachments/assets/eca102fe-fbf8-45e8-9e30-d3f4136a5c4d">
Shouldn't that affect the delay? No matter what I set it to the music always starts to play with the same delay.

**Comment by SantiagoSotoC** [comment]
It's not just that latency, there is also a delay between snapcast creating the socket where the audio is sent and also having to start ffmpeg, that's why I say that eliminating the TCP socket for a named pipe should reduce the delay a bit.

 

It is the same server I was referring to that server that is included in ma

But I will test if there is a difference with an external server, maybe it is a snapcast problem or that the documentation is not clear on how the parameter works.

**Comment by ReinhardPrix** [comment]
I'm seeing something very similar too since the latest MA upgrade (2.2.2).

Any TTS announcements to snapcast clients don't seem to produce any sound if the message is too short (a few words), but *does* (sometimes) output the full message (not truncated) when the message is long enough (10words) ... not quite reproducible though as after a successful announcement it won't work again ... very confusing.

The 'announcement sound' (if activated) will be played, but sounds distorted/truncated.

**Comment by OzGav** [comment]
We have added to the docs that short announcements do not work. @SantiagoSotoC Is there anything more that we do here?

**Comment by SantiagoSotoC** [comment]
Well I think both things have been fixed, there was a bug with the buffer size and the short audios, both things have been fixed.

**Comment by OzGav** [comment]
@TobiasLe please confirm your original issue has been resolved in 2.3.2/2.4.0b3

**Comment by OzGav** [comment]
We will close this soon due to no followup

**Comment by TobiasLe** [comment]
I just updated to 2.3.2. Unfortunately I still have the same Problems.
When I trigger a short TTS announcement (5 words) the music cuts out immediately,  then silence, and then after ~16 seconds the music comes back.
For longer TTS announcements. The music cuts out immediately, then after 8s the announcement plays from the beginning, however something is cut off at the end (I guess the last 8 seconds of the announcement are missing). Then again after 8s the music comes back.

**Comment by SantiagoSotoC** [comment]
> I just updated to 2.3.2. Unfortunately I still have the same Problems. When I trigger a short TTS announcement (5 words) the music cuts out immediately, then silence, and then after ~16 seconds the music comes back. For longer TTS announcements. The music cuts out immediately, then after 8s the announcement plays from the beginning, however something is cut off at the end (I guess the last 8 seconds of the announcement are missing). Then again after 8s the music comes back.

What settings do you have ? the most important parameters are idle treshold and buffer size.

**Comment by SantiagoSotoC** [comment]
Yes that's another bug, I'll check it later but it's not a priority, I'm trying to improve the snapcast library first.
