### ISSUE TITLE
Audio Drops While Streaming via UPnP from Raspberry Pi 5 to Arcam AVR390

### ISSUE THREAD

**Issue by Argeento** [music-assistant/hass-music-assistant#2791]
### What version of Music Assistant has the issue?

2.3.0b2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I am experiencing an issue while streaming audio using UPnP from my Raspberry Pi 5 to my Arcam AVR390. The audio intermittently cuts out, although the playback in the UI continues to show as playing.

## Details:

- The audio on my Arcam AVR390 drops out randomly; sometimes it happens after 10 seconds, sometimes after a minute, and other times after several minutes.
- When the audio stops in the middle of a song, the timer continues counting down and does not stop. For example, if a song is 3 minutes long and the audio cuts out, the timer may show 10 minutes out of 3.
- Volume control remains functional at all times.
- If I manually stop and start the playback or skip to the next track through the UI, the audio resumes.
- The Arcam AVR390 has an indicator icon that flashes when the stream is active. During the issue, the Arcam continues to show that it is receiving a stream, even though no sound is being produced.

## Troubleshooting Attempts:

- I tried streaming audio from my PC using foobar2000 to the Arcam AVR390 via UPnP, and everything worked perfectly (Also streaming from Music Assistant to my smartTV via UPnP works fine)
- Also experimented with different sample rates in the provider settings, but the issue persisted regardless of the sample rate configuration.
- I have tested both the stable and beta versions of the server, but the problem occurs on both versions.
- In the provider settings for the Arcam, I tried enabling and disabling the following options:
  - "Enable queue flow mode"
  - "Player supports enqueue next/gapless"
- I changed my router, but the issue persists.

### How to reproduce

 I am unable to provide a specific set of steps to reliably reproduce this issue.

### Music Providers

- Tidal (HI_RES)
- RadioBrowser

### Player Providers

I have only used the **UPnP/DLNA Player provider**, which results in the issue described. I am not using grouped players.

### Full log output

The logs are empty during the occurrence of the issue. No relevant entries are generated at the time of the audio dropouts.

### What version of Home Assistant Core are your running

2024.8.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
Sounds like a buffering issue. 

A couple of questions:

1) Did you also test with enforcing MA to transcode into MP3 ? Maybe the high quality FLAC stream MA sends by default is just enough to hit some bandwidth issue.

2) Does the Arcam also support other protocols like Airplay ?

3) Does the issue happen regardless of source ? So both with radio streams and e.g. Tidal or local tracks ?

4) Does the audio just stutter/hiccup and then continues or does it stop and just become silent ?

**Comment by Argeento** [comment]
Thank you for your suggestions. Here are my answers:

1. I tried transcoding to MP3, but in this case, the Arcam does not play any audio at all.
2. The Arcam only supports UPnP.
3. Yes, the issue occurs regardless of the source - whether it’s local files, radio streams, or Tidal.
4. The audio suddenly stops and does not resume on its own (I waited about 15 minutes).

Additionally, today I installed Home Assistant + Music Assistant on my old Raspberry Pi 3b. I went to a friend who also has an Arcam AVR390 to test whether the issue is specific to my unit. Unfortunately, the same problem occurs at my friend's place.

**Comment by marcelveldt** [comment]
So most likely this player can't deal with our chunked audio stream with no size specified, I've heard about that.
You'd be surprised to hear that multi thousand dollar streamers/receivers have 25 year old HTTP1 implementation omboard, its awful. Anyways, I will add a few options to the DLNA settings so you can select a profile for your device so we can test some options

**Comment by Argeento** [comment]
@marcelveldt Thanks! 

Also.. After switching log level to debug, I found some relevant [logs](https://gist.github.com/Argeento/0fe0404363fc041dc688515600c126fa#file-musicassistantlogs-txt), especially this line:
```
2024-08-24 12:56:48.015 DEBUG (MainThread) [music_assistant.dlna] Device unavailable: UpnpCommunicationError('ClientPayloadError("Response payload is not completed: <TransferEncodingError: 400, message=\'Not enough data for satisfy transfer length header.\'>. ConnectionResetError(104, \'Connection reset by peer\')")', None)
```

**Comment by marcelveldt** [comment]
I have published a beta version of the MA server which includes some fine grained control over the HTTP streaming.
Within the player settings, go to the advanced section and try the HTTP Profiles one by one, starting with the default chunked one.

Available in 2.3.0 beta 4 and above

**Comment by OzGav** [comment]
@Argeento this will be closed soon assuming fixed due to no followup

**Comment by Argeento** [comment]
I've checked every HTTP Profile - the issue still occurs. I'll provide MA logs this week

**Comment by Argeento** [comment]
@marcelveldt 
[profile 1 - chunked](https://gist.github.com/Argeento/8fad236474261c9349f5cdbb4ad60f8d)
[profile 2 - no content length](https://gist.github.com/Argeento/6c0dd41b462e19b919c04e7c7377dd1d)
[profile 3 - forced content length](https://gist.github.com/Argeento/245cb9c6ba3538061fe2e6435fb3fbd4)

**Comment by marcelveldt** [comment]
Without actual access to the device I'm afraid there is nothing I can do here. DLNA is a shitty protocol with shitty implementations by manufacturers that don't give a crap about standards/interoperability. Therefore I do not provide any support for DLNA other than best effort and if you may run into issues you'll have to submit a PR yourself.

Foobar2000 is an application that exists for 2 decades already and has all kind of special device-specific treatments.
In this case making this work would involve comparing wireshark traces of what foobar is sending against what MA sends, its that awful.

The best advise I can give in this situation is to use a streaming protocol other than DLNA. For example hook up a raspberry pi or esp32 board running squeezelite (slimproto), airplay or snapcast which also gives you the benefit of synced playback.
Or a less-DIY and better sounding option is something like a Wiim Pro Plus, Sonos Port or Bluesound Node. Anything other than crappy DLNA with all its quirks.

Don't get me wrong, we also have success stories with DLNA where people are incredible happy with it but looks like you are on the less lucky side.

**Comment by Argeento** [comment]
Thanks for taking the time to explain everything. I understand that the issue is likely due to DLNA limitations with my arcam.

I really appreciate your insights and the suggestions for other streaming options 🚀 

I’m fine with closing this issue. Thanks again for your support!
