### ISSUE TITLE
New Sonos provider - cannot play anything on Symfonisk bookshelf speaker

### ISSUE THREAD

**Issue by lexam79** [music-assistant/hass-music-assistant#2807]
### What version of Music Assistant has the issue?

2.3.0b3

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

After upgrading to the latest beta with the new Sonos provider, my Symfonisk Bookshelf speakers stopped working.

### How to reproduce

Just attempt to play any media

### Music Providers

Tunein, Apple Music, Filesystem (remote share): all show the same behavior

### Player Providers

Sonos (new)

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16739344/music-assistant.log)

### What version of Home Assistant Core are your running

2028.8.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Linux

**Comment by marcelveldt** [comment]
Looking at your log it will only fail at playing a radio station (we will fix that) but anything else should play

**Comment by marcelveldt** [comment]
I have just published 2.3.0 beta 5 - can you give that a try ?

**Comment by lexam79** [comment]
Unfortunately, still not working. Attaching new log.
[music-assistant.log](https://github.com/user-attachments/files/16744164/music-assistant.log)

I'm still getting errors, whatever I attempt to play, radio, Apple Music, or local (Samba share) files.

Thank you

**Comment by OzGav** [comment]
OK those errors are actually new in beta 5 which need to be addressed so keep an eye out for the next update and then try again please.

**Comment by lexam79** [comment]
Seems to work with beta 6! Thank you!

**Comment by OzGav** [comment]
OK beta 6 is now available. Please try again.
