### ISSUE TITLE
AIO "using chunked encoding is forbidden" & "500 Internal Server Error" errors prevent music playback to Slimproto player

### ISSUE THREAD

**Issue by Vacationland105** [music-assistant/hass-music-assistant#2809]
### What version of Music Assistant has the issue?

2.3.0b4

### What version of the Home Assistant Integration have you got installed?

2024.8.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

2.3.0b4 seems to break something with the Slimproto player provider.  Music will not play and a consistent error is produced every time one attempts to play music to a Slimproto player.  Playback works normally for other player providers (i.e. Sonos).  Full log attached but this is the pertinent bit.  Reverting back to 2.3.0b3 restores player functionality.  Slimproto player is not grouped with other players.
  
![image](https://github.com/user-attachments/assets/5bf7dd63-83d6-47d2-b50e-f60fe97e1fe1)

### How to reproduce

Attempt to play either Filesystem (remote share) or Spotify sourced music to a Slimproto player provider player.  There is an attempt to play the music but MA encounters an error and fails to start playback.

### Music Providers

Filesystem (remote share) and Spotify

### Player Providers

Slimproto, Sonos, Universal Group Player

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/16741224/music-assistant.log)

### Additional information

MA is deployed via Docker container and not HA.  Slimproto player is Windows Squeezelite x64 version 2.0.0.1480

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Is this a real squeezebox player ? It is very old as it only supports HTTP 1.0 and not even 1.1.
Anyways, I'll add a fix in the code but curious if also the software based slimproto players are based on HTTP 1.0

**Comment by Vacationland105** [comment]
This is a soft player, not a hardware based unit.  I am running Squeezelite x64 version 2.0.0.1480, which is the most recent version as far as I can tell.  I did not make any changes to the player between the two versions.  Perhaps I need to run it differently, I would need to see if anything like that is available for tweaking.

**Comment by Lateadapter** [comment]
I have the same issue running Squeezelite x64 version 1.9.9.1432 as provided by Music.Assistant.Companion_0.0.71_x64-setup.exe

**Comment by marcelveldt** [comment]
I have just published 2.3.0 beta 5 - can you give that a try ?

**Comment by Vacationland105** [comment]
Hello @marcelveldt.  Initial testing shows the Slimproto player provider (running squeezelite x64) works properly once again with 2.3.0b5.  Errors no longer show in the log as it did before and music plays as expected.

**Comment by vivobg** [comment]
I still see the above issue, when using a Group Player consisting of 2 slimproto software players. I tried both the stable 2.2.4 and beta  2.3.0b23 versions. Both slimproto players can play the music individually, but not when in a group.
