### ISSUE TITLE
Spotify streaming errors

### ISSUE THREAD

**Issue by niteguide** [music-assistant/hass-music-assistant#2863]
### What version of Music Assistant has the issue?

2.3.0b16

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Unfortunately Issue #2765 was marked as closed very fast. Because the problem persists in my setup I open this new entry. The problem still comes back after a non predictable amount of time - on Chromecast/Google Cast as well as on AirPlay. Arbitrarily (but usually only between songs) the sound-output stops and does not come back although music still appears to be playing within MA. I have both players also added via Apple-TV/Google Cast integration - these entities immediately go to idle when the sound-output stops. Music provider in use is Spotify only. 

### How to reproduce

Happens arbitrarily during playback (Spotify playlist). Usually between two songs (after one song ends). 

### Music Providers

Spotify only

### Player Providers

Happens on HomePod Mini, Google Home Mini

### Full log output

Log-entries from yesterday and today: 
[log.docx](https://github.com/user-attachments/files/16847753/log.docx)

### Additional information

As a workaround I have set up an automation that gets triggered when the entity from Apple-TV/Google Cast integration goes to Idle for 4 seconds - the automation then stops the MA-entity and restarts the playlist. But this however is of course far from what the system should be. 

Router in use: Synology MR2200ac
Did a lot of experimenting with router settings but nothing makes the situation better. I have not noticed any other issues within my network. 

### What version of Home Assistant Core are your running

2024.8.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by niteguide** [comment]
> Based on the log excerpt this appears to be a duplicate of #2860

The description of the problem over there is not very detailed, so I could not say, if we talk about the same issue. Nevertheless this one points out that also Apple-TV and Google Cast is affected.

**Comment by OzGav** [comment]
Yes but only because that is what you have tried. I expect that if you try Snapcast you will get the same thing because if you look in the log it is full of Spotify errors. To confirm you can try a radio station and see what happens

**Comment by marcelveldt** [comment]
please test if this is fixed in 2.3.0b18

**Comment by niteguide** [comment]
Unfortunately not fixed at all. 
[music-assistant (2).log](https://github.com/user-attachments/files/16887079/music-assistant.2.log)

**Comment by OzGav** [comment]
Please check if this is fixed in beta 21

**Comment by niteguide** [comment]
Thanks! 
Looked very promising at first. However after 2:48 hours playtime the chromecast player stopped - exactly at time 08:35:02
log: [music-assistant (3).log](https://github.com/user-attachments/files/16976010/music-assistant.3.log)

**Comment by niteguide** [comment]
Have recent beta 23 running. 
No problems for a very very long time. I started the playlist at time 13:37 and it kept running until time 20:49. At this point chromecast player suddenly stopped in the middle of a song. 
log: 
[music-assistant (4).log](https://github.com/user-attachments/files/17003505/music-assistant.4.log)

I might add that I have not yet installed 2024.9.0 that just came out.

**Comment by OzGav** [comment]
Ok this will continue to get investigated. The log is helpful.

**Comment by nikito** [comment]
Bit more logging as well for me, I also tried turning off shuffle and just letting the playlist go. For a while it worked but eventually ran into this:
`2024-09-16 08:20:33.431 WARNING (MainThread) [music_assistant.spotify] librespot failed to stream track, retrying... (attempt 1/3)
2024-09-16 08:20:34.175 WARNING (MainThread) [music_assistant.spotify] librespot failed to stream track, retrying... (attempt 2/3)
2024-09-16 08:20:34.680 WARNING (MainThread) [music_assistant.audio.media_stream] Stream error on spotify--jdi6zRXV://track/53va7kEIt0pn7tOhrTB99q
2024-09-16 08:20:34.706 ERROR (MainThread) [music_assistant.streams] Error streaming QueueItem Jesse Cook/Hampig Djavorian - Luna Llena (Live) (library://track/1849) to Workshop Music
2024-09-16 08:20:35.261 INFO (MainThread) [music_assistant.spotify] Attempt 1/5 failed: Token expired
2024-09-16 08:20:35.261 INFO (MainThread) [music_assistant.spotify] Retrying in 6 seconds...`

I am noticing that this seems to happen pretty consistently in my logs when the music just stops playing. Maybe related to the token expiring and not renewing before the next track is requested?

**Comment by OzGav** [comment]
Thanks. We can see what the problem is. No need for any more followup. When there is news of a fix you will hear it here first.

**Comment by niteguide** [comment]
Beta 24 came out. This time I first ran into a problem with Apple HomePod Mini: At exactly time 07:51:39 no sound output, while the music appears to be playing within MA (both Chromecast and Airplay started playing at time 06:36).
Log: [music-assistant (5).log](https://github.com/user-attachments/files/17024374/music-assistant.5.log)

**Comment by flexmatics** [comment]
I have the same issue as identified [here](https://github.com/music-assistant/hass-music-assistant/issues/2925#event-14274541640)

I've updated to 2.3.0b26. Not sure if that was suppossed to fix the issue, but I still get dropped playback of queued tracks.
1. I've noted that in all cases, it just stops playing and on front end it shows like in screenshot (few seconds from the end of track it gets stuck):
![image](https://github.com/user-attachments/assets/68c99922-b442-4b6d-ab5d-fcac7c605b7d)

2. The log with INFO level doesn't say anything relevant. At 09:09 playback was started, it stopped at ~09:30, but nothing noted.

> 2024-09-21 07:33:45.782 INFO (MainThread) [music_assistant] Starting Music Assistant Server (add8b535ce464403a2cdc585972e4c11) version 2.3.0b26 - HA add-on: True - Safe mode: False
2024-09-21 07:33:45.786 INFO (MainThread) [music_assistant.cache] Initializing cache controller...
2024-09-21 07:33:45.875 INFO (MainThread) [music_assistant.music] Using a sync interval of 180 minutes.
2024-09-21 07:33:45.912 INFO (MainThread) [music_assistant.streams] Detected ffmpeg version 6.1.1 with libsoxr support
2024-09-21 07:33:45.912 INFO (MainThread) [music_assistant.streams] Starting server on  0.0.0.0:8097 - base url: http://192.168.0.108:8097
2024-09-21 07:33:45.915 INFO (MainThread) [music_assistant.webserver] Starting server on  172.30.32.1:8095 - base url: http://172.30.32.1:8095
2024-09-21 07:33:48.465 INFO (MainThread) [music_assistant] Loaded music provider Music Assistant
2024-09-21 07:33:48.465 INFO (MainThread) [music_assistant] Loaded metadata provider The Audio DB
2024-09-21 07:33:48.466 INFO (MainThread) [music_assistant] Loaded metadata provider MusicBrainz
2024-09-21 07:33:48.466 INFO (MainThread) [music_assistant] Loaded metadata provider fanart.tv
2024-09-21 07:33:48.478 INFO (MainThread) [music_assistant] Loaded player provider Slimproto (Squeezebox players)
2024-09-21 07:33:48.577 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-09-21 07:33:48.578 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-09-21 07:33:48.579 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-09-21 07:33:48.825 INFO (MainThread) [music_assistant.spotify] Successfully logged in to Spotify as Inga
2024-09-21 07:33:48.825 INFO (MainThread) [music_assistant] Loaded music provider Spotify
2024-09-21 07:33:49.873 INFO (MainThread) [music_assistant.slimproto] Player squeezeplay: dc:a6:32:06:9e:c9 connected
2024-09-21 07:33:49.873 INFO (MainThread) [music_assistant.players] Player registered: dc:a6:32:06:9e:c9/squeezeplay: dc:a6:32:06:9e:c9
2024-09-21 07:33:49.876 INFO (MainThread) [music_assistant.slimproto] Player squeezeplay: 00:00:00:00:00:00 connected
2024-09-21 07:33:49.876 INFO (MainThread) [music_assistant.players] Player registered: 00:00:00:00:00:00/squeezeplay: 00:00:00:00:00:00
2024-09-21 07:34:00.806 INFO (MainThread) [music_assistant.music] Sync task for Spotify: Inga completed
2024-09-21 07:34:00.807 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-09-21 07:34:00.808 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-09-21 09:09:05.362 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue living_room - crossfade: False

**Comment by niteguide** [comment]
Also beta 26 here.
With beta 25 I mainly had problems with Chromecast. This beta it's AirPlay again. No sound exactly since time 9:53. Because in MA the playlist still appears as playing (in my case the track does not appear as stuck in the frontend, as @flexmatics points out), the missing sound output is not shown in the logs, as always, I attach it nevertheless: 
[music-assistant (6).log](https://github.com/user-attachments/files/17083458/music-assistant.6.log)

To bring the sound output back, I just have to click on the forward button in the frontend and the playlist continues with the next song.

**Comment by nikito** [comment]
Tried beta 26 as well. The same issue happens where it just stops playing after a few tracks, though i notice noting in the log now. Am I see are the sync task and metadata scan task, nothing else of note.

**Comment by nikito** [comment]
Just another update I noticed, seems inconsistent for me. Today for instance I've got through 22 tracks so far without a problem. Yesterday it got through something like 16 track before stopping without any error.

**Comment by marcelveldt** [comment]
I'm investigating this issue folks, just a bit if patience please. I have been busy with other (not MA related) stuff last weeks so this got sidetracked a bit. Keep an eye out for the updates if the issue gets fixed soon

**Comment by marcelveldt** [comment]
Please test beta 29 if the issue is fixed. Thanks!

**Comment by flexmatics** [comment]
Hey,

I've updated to b29. Started playlist, 1st song played fine, second has stopped. Log says as follows (not seen this before):

> 2024-10-01 20:57:34.834 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue living_room - crossfade: False
> 2024-10-01 21:04:02.558 ERROR (MainThread) [ffmpeg.267] Stream error:

**Comment by nikito** [comment]
Still occurring for me, here is what I could see in the log (had to turn on debug, otherwise I saw nothing noteworthy):
`2024-10-01 15:20:52.870 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for library://track/977
2024-10-01 15:20:53.036 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for library://track/977 in 165 milliseconds
2024-10-01 15:20:53.038 DEBUG (MainThread) [music_assistant.chromecast] Enqued next track (Don't Count on the Wicked) to player Workshop Music
2024-10-01 15:21:17.804 DEBUG (MainThread) [music_assistant.cache] Running automatic cleanup...
2024-10-01 15:21:17.851 DEBUG (MainThread) [music_assistant.cache] Automatic cleanup finished (cleaned up 0 records)
2024-10-01 15:22:44.376 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-49) [music_assistant.chromecast] Discovered new or updated chromecast CastInfo(services={HostServiceInfo(host='192.168.1.62', port=8009), MDNSServiceInfo(name='Chromecast-908c5dda70de5d25cbc7bda57992c94b._googlecast._tcp.local.')}, uuid=UUID('908c5dda-70de-5d25-cbc7-bda57992c94b'), model_name='Chromecast', friendly_name='Living Room TV', host='192.168.1.62', port=8009, cast_type='cast', manufacturer='Google Inc.')
2024-10-01 15:22:44.669 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-49) [music_assistant.chromecast] Discovered new or updated chromecast CastInfo(services={HostServiceInfo(host='192.168.1.62', port=8009), MDNSServiceInfo(name='Chromecast-908c5dda70de5d25cbc7bda57992c94b._googlecast._tcp.local.')}, uuid=UUID('908c5dda-70de-5d25-cbc7-bda57992c94b'), model_name='Chromecast', friendly_name='Living Room TV', host='192.168.1.62', port=8009, cast_type='cast', manufacturer='Google Inc.')
2024-10-01 15:23:00.660 DEBUG (MainThread) [music_assistant.audio.media_stream] stream finished (with code 0) for spotify--jdi6zRXV://track/6wbFgZwDP1KLfoNp2Jqa4m - seconds streamed: 200.53333333333333
2024-10-01 15:24:14.238 DEBUG (zeroconf-ServiceBrowser-_googlecast._tcp-49) [music_assistant.chromecast] Discovered new or updated chromecast CastInfo(services={MDNSServiceInfo(name='Google-Nest-Hub-1c82db84ad991b6902797c00ef2741ee._googlecast._tcp.local.'), HostServiceInfo(host='192.168.1.197', port=8009)}, uuid=UUID('1c82db84-ad99-1b69-0279-7c00ef2741ee'), model_name='Google Nest Hub', friendly_name='Workshop Hub', host='192.168.1.197', port=8009, cast_type='cast', manufacturer='Google Inc.')
2024-10-01 15:24:23.513 DEBUG (MainThread) [aiohttp.server] Ignored premature client disconnection.`

**Comment by flexmatics** [comment]
If it helps, there is another error after 1hr of playback today with b29. Not sure if it is related with this issue, or it is another one.

> 2024-10-02 16:02:03.843 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-10-02 16:02:03.844 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.
2024-10-02 18:00:26.867 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue living_room - crossfade: False
2024-10-02 19:01:42.115 ERROR (MainThread) [ffmpeg.604] Stream error: 
2024-10-02 19:01:53.872 INFO (MainThread) [music_assistant.music] Sync task for Music Assistant completed
2024-10-02 19:01:53.918 INFO (MainThread) [music_assistant.spotify] Attempt 1/5 failed: Token expired
2024-10-02 19:01:53.918 INFO (MainThread) [music_assistant.spotify] Retrying in 0.1 seconds...
2024-10-02 19:02:03.884 INFO (MainThread) [music_assistant.music] Sync task for Spotify: Inga completed
2024-10-02 19:02:03.885 INFO (MainThread) [music_assistant.metadata] Starting metadata scanner
2024-10-02 19:02:03.887 INFO (MainThread) [music_assistant.metadata] Metadata scanner finished.

**Comment by niteguide** [comment]
I 

> So far the problem (no sound) did not occur in my case since b29 came out. But I keep testing extensively. I see some errors in the logs too that are similar to those of the other posters, for reference here is the file: [music-assistant (7).log](https://github.com/user-attachments/files/17244697/music-assistant.7.log)

I take that back. Right now discovered that it also occurs with my setup unfortunately.

**Comment by nikito** [comment]
Small update, I also encountered the error someone else mentioned running into today:
2024-10-07 09:55:05.049 WARNING (MainThread) [music_assistant.audio.media_stream] Stream error on spotify--jdi6zRXV://track/0VlyGO38VGjVKn3VuXT04A
2024-10-07 09:55:05.049 ERROR (MainThread) [ffmpeg.1545] Stream error: 
2024-10-07 09:55:05.058 ERROR (MainThread) [music_assistant.streams] Error streaming QueueItem Faith No More - Epic (library://track/1831) to Workshop Music

**Comment by nikito** [comment]
Figured I'd update here, on the latest beta and so far today I don't think I have seen the issue happen. :)

**Comment by niteguide** [comment]
> Figured I'd update here, on the latest beta and so far today I don't think I have seen the issue happen. :)

can not confirm that for b33! for me nothing changed; sometimes playback stops after several hours and sometimes after a few songs; my experience with the past versions is that you only have to wait long enough for it to happen unfortunately; b34 i have not tried yet, but according to release notes this is not addressed;

**Comment by OzGav** [comment]
Correct, this is still on the todo list

**Comment by marcelveldt** [comment]
fixed in 2.3.0 rc 1 (yeah I found the root cause, finally)

**Comment by OzGav** [comment]
2.3.0rc1 is released. Please test again. Attach the full log if you experience a problem.

**Comment by niteguide** [comment]
> 2.3.0rc1 is released. Please test again. Attach the full log if you experience a problem.

Thank you for all your efforts! 
I have rc1 running; Still experiencing the problem; Here is the logfile: 

[music-assistant (8).log](https://github.com/user-attachments/files/17507327/music-assistant.8.log)

**Comment by OzGav** [comment]
@niteguide It would appear you might not be using your own CLIENT ID. Is that right?

**Comment by niteguide** [comment]
> And following up on that, @niteguide, please describe what you mean with "the issue". As you can see the spotify rate limiter is kicking in on your setup very often so it is advised to use your own client id (in the spotify provider settings) to prevent those. But, as you can see we retry a lot. So please explain WHAT is not working. Playback ?

Okay, I have just looked at the spotify-player documentation for MA again regarding client id; will re-authenticate with a client id and then come back here again with a report!

**Comment by marcelveldt** [comment]
and what about my question ?

**Comment by niteguide** [comment]
> and what about my question ?

i don't want to bother you with not valid error reporting; let me check everything again conscientiously and with client id; then i will report in detail; thank you!

**Comment by nikito** [comment]
Running 2.3.0rc2 and so far haven't seen the issue. Playback in general seems better as well; Maybe a placebo effect of sorts, but it feels faster to cast the music. :)
I am using my own ClientID as mentioned as well.

**Comment by niteguide** [comment]
> and what about my question ?

I now use a Client ID as described in the documentation. 

Here is what happens in my case with rc3: 

Start two different Playlists manually at time 19:49 on Google Home Mini and HomePod Mini
Suddenly no sound output at 22:04 on Goodle Home Mini; HomePod still playing
According to HA-entity Google Home Mini is on buffering
According to MA-entity Google Home Mini is playing 
Within MA I can see that the playlist got stuck - notice the time data on the screenshot (song is 04:23 minutes long but it counts above 5:00 and then goes back to 04:15; repeats indefinitely); 

![IMG_2595](https://github.com/user-attachments/assets/fd8d8e0c-14c8-4af7-afe0-3928f82e79c5)
es back to 04:15; repeats indefinitely); 
![IMG_2596](https://github.com/user-attachments/assets/0d794db2-ef07-4baa-8dac-fcdb765c2b0f)
![IMG_2597](https://github.com/user-attachments/assets/d78be099-7ceb-4203-8251-734ffd1c3dbd)
[music-assistant (9).log](https://github.com/user-attachments/files/17512371/music-assistant.9.log)

**Comment by marcelveldt** [comment]
This seems to be some sort of issue with your cast player - there is also a cast socket error being reported. Is it possible that it simply lost network connection at some some point ? Did you try with another (cast) player as well ?

**Comment by niteguide** [comment]
> This seems to be some sort of issue with your cast player - there is also a cast socket error being reported. Is it possible that it simply lost network connection at some some point ? Did you try with another (cast) player as well ?

I only have this one device but could of course order a new unit. However I will say this: with the last betas before rc1 it was the HomePod that stopped playing while Chromecast continued; now Google Cast always shows the behaviour I described; If there would be a network issue, wouldnt the entity get  status unavailable?

**Comment by marcelveldt** [comment]
If the outage was just super short, it would be enough to stop music (as in: the cast player itself aborts playback) but not serious enough to mark the player as unavailable.

One idea could be that you enforce the mp3 codec on the cast player (its an option in the player settings) so it consumes less bandwidth

**Comment by niteguide** [comment]
> If the outage was just super short, it would be enough to stop music (as in: the cast player itself aborts playback) but not serious enough to mark the player as unavailable.
> 
> One idea could be that you enforce the mp3 codec on the cast player (its an option in the player settings) so it consumes less bandwidth

Thanks! 
I have selected this option. Furthermore I have turned off 5 GHz Wifi altogether and all devices now run on 2.4 GHz. Then I set up Tidal as another source. It's always the same problem (as described in my second to last post) - and it happens with Chromecast as well as with HomePod Mini. So I do not think that it is one device that makes the problems, it's obviously not even Spotify-specific. It might be the network - but I simply have no idea left what else I could try ... I am slowly giving up :( 

[music-assistant (11).log](https://github.com/user-attachments/files/17530803/music-assistant.11.log)

**Comment by OzGav** [comment]
Ok if this is happening with Tidal as well then I propose closing this as no one is reporting Spotify problems which is what this issue is originally about. You can open a Q&A about this as it doesn’t seem to be a MA problem based one what I am reading. Please advise.

**Comment by OzGav** [comment]
Clsoing as the Spotify problems are resolved.
