### ISSUE TITLE
Playback stops after playing one song (Chromecast)

### ISSUE THREAD

**Issue by de666** [music-assistant/hass-music-assistant#2887]
### What version of Music Assistant has the issue?

2.3.0b20

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Playback on Chromecast stops after playing one or two track (two at most) on a google home mini device
No errors in the logfile

### How to reproduce

- Start playing a playlist on a chromecast device (google  home mini)
- Playback stops after playing the first or the second track

### Music Providers

Filesystem

### Player Providers

Chromecast (single player/device)

### Additional information

No error present in the logfile
Worked well with the previous version (2.3.0b19), so it seems something related to version 2.3.0b20

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by nikito** [comment]
Seeing the exact same here.

**Comment by SCBionicle** [comment]
Same here. Home Assistant OS, Generic x86-64, Hyper-V.

**Comment by jnleyva816** [comment]
Seeing the same thing. Came here to see if others were having a similar issue

**Comment by OzGav** [comment]
Please confirm this is fixed in the next update

**Comment by OzGav** [comment]
beta 21 has been released

**Comment by de666** [comment]
Solved in beta 21

**Comment by nikito** [comment]
Unfortunately still happening for me on the latest beta 21. It gets through more songs than before, but eventually just stops itself just as before, with nothing in the log indicating a problem. Think this time it got through 3-4 songs before it stopped, versus before where it'd stop after 1-2.

**Comment by senderbell** [comment]
In my case playback stops always after 1 or 2 songs, then I need to hit play. Just like before.
Log is clear.

**Comment by nikito** [comment]
Have been testing a bit here and there throughout the day and it seems inconsistent for me. Sometimes several songs will go by before it stops, just now it stopped after a single song. Each time there's no errors in the log. The only thing I can see to correlate is that when it happens, there's a sync being shown in the log:
![image](https://github.com/user-attachments/assets/aada977f-d43a-47f3-a094-d17cd680dfb2)

**Comment by drjjr2** [comment]
I am having the same problem with a Spotify playlist and a DLNA player. 2 songs then stops and I have to hit play to get it to continue. There is nothing in the logs when set to INFO level.

**Comment by nikito** [comment]
So just had it happen now after playing a bunch of songs, saw this in the log this time:
![image](https://github.com/user-attachments/assets/2545157e-08d8-4d3f-9352-b822b0b7181e)

Gonna keep testing to see if I can run into the scenario where it stops without any log error again, and see if I can spot anything useful.

**Comment by nikito** [comment]
Ok, got it to happen again where it stops with no error in the log. Here's what I noticed:
![image](https://github.com/user-attachments/assets/88a8fb4d-8808-439f-a10e-39235a254039)
It seems it goes to play the next song, but it doesn't get anywhere and appears in this state, as if it seems to think it already played?
Opening it up more, it looks like this:
![image](https://github.com/user-attachments/assets/f0a9dda3-5ac4-4f55-ad54-ab5a4231de46)
What's odd is on the song's timeline, on the left it is showing 10:50, but on the right it is showing 03:49. The actual length of the song is 03:49, so think it is getting confused. the 10:50 is actually the length of the song that had played previously. I also notice if I go to the Played tab and try to see the last song, when I scroll to the bottom it resets the view back to the top, not letting me see the last song. Not sure if these are all related, but this is all the behavior I could observe. Hope this is helpful!

**Comment by senderbell** [comment]
I listened to music for a few hours and I think everything is fine, but only with sound normalization turned off. With it turned on, it still stutters, but I feel like it's a bit less frequent than before.

**Comment by nikito** [comment]
Went fine for a while, then stopped again unfortunately. See this new message in the logs now:
2024-09-14 12:52:34.208 WARNING (MainThread) [music_assistant.spotify] librespot failed to stream track, retrying... (attempt 1/3)

**Comment by nikito** [comment]
Some more logging from another occurrence:
2024-09-14 14:40:41.941 WARNING (MainThread) [music_assistant.spotify] librespot failed to stream track, retrying... (attempt 1/3) 2024-09-14 14:40:42.693 WARNING (MainThread) [music_assistant.spotify] librespot failed to stream track, retrying... (attempt 2/3) 2024-09-14 14:40:43.198 WARNING (MainThread) [music_assistant.audio.media_stream] Stream error on spotify--jdi6zRXV://track/4Fyab3mqEyw5fcROY5sWve 2024-09-14 14:40:43.224 ERROR (MainThread) [music_assistant.streams] Error streaming QueueItem Serj Tankian - The Unthinking Majority (library://track/1765) to Workshop Music 2024-09-14 14:40:43.738 INFO (MainThread) [music_assistant.spotify] Attempt 1/5 failed: Token expired 2024-09-14 14:40:43.739 INFO (MainThread) [music_assistant.spotify] Retrying in 6 seconds...

**Comment by OzGav** [comment]
@nikito your issue is being tracked here https://github.com/music-assistant/hass-music-assistant/issues/2863

@senderbell please don’t introduce new problems to this issue. If the streaming doesn’t stop then this is resolved for you. 

As the OP reports this as fixed this is being closed.
