### ISSUE TITLE
Music Stops playing periodically

### ISSUE THREAD

**Issue by johnboiles** [music-assistant/hass-music-assistant#2893]
### What version of Music Assistant has the issue?

2.2.3

### What version of the Home Assistant Integration have you got installed?

2024.8.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Several times today my media has stopped playing. The log showed the following when the disconnect happened:

```
2024-09-09 16:56:08.769 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
```

### How to reproduce

Try to play music all day with Music Assistant because Music Assistant is awesome. Music does not play all day.

Today is the first time I noticed it, though it has happened three times today.

### Music Providers

Apple Music

### Player Providers

ESPHome Media Player (using https://github.com/gnumpi/esphome_audio)

### Full log output

[music-assistant (1).log](https://github.com/user-attachments/files/16937704/music-assistant.1.log)

### What version of Home Assistant Core are your running

2024.9.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
@MarvinSchenkel can you please have a look at this log as there are some Apple music errors that may lead to the stop of music. Thanks!

**Comment by johnboiles** [comment]
I'd be surprised if it's the metadata errors leading to music stopping. From some quick googling it seems like `Received non-Text message.` might be related to a bad message on a websocket. Do you happen to know which logs I should set to verbose to investigate further?

**Comment by johnboiles** [comment]
I've started watching my ESPHome logs today to watch for more details on this. I got the `Received non-Text message` thing before a disconnect but 30 minutes before the disconnect. Yesterday that message happens at about the same time as media stopping but I wasn't watching closely. I suppose it's possible `Received non-Text message` could be a red herring.

Here's my MA log for this morning:
```
2024-09-10 09:02:43.799 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Main Stereo - crossfade: False
2024-09-10 09:02:46.692 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Main Stereo - crossfade: False
2024-09-10 09:03:47.450 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Main Stereo - crossfade: False
2024-09-10 09:03:50.453 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Main Stereo - crossfade: False
2024-09-10 09:13:47.769 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
2024-09-10 09:24:43.465 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Main Stereo - crossfade: False
2024-09-10 09:24:46.972 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue Main Stereo - crossfade: False
```

And here's the ESPHome logs when playback stopped:
```
[09:46:55][D][esp-idf:000][http]: W (87106236) HTTP_STREAM: No more data,errno:0, total_bytes:50593005, rlen = 0
[09:46:55][I][esp_audio_sources:033][http]: Receive http event: 7
```

In esp-adf, event 7 this [corresponds](https://github.com/gnumpi/esphome_audio/blob/dcd96c73718cfa4d269618d0377aa44f155a6e02/esphome/components/adf_pipeline/adf_audio_sources.cpp#L33) to [`HTTP_STREAM_FINISH_TRACK`](https://github.com/espressif/esp-adf/blob/302f9a2c113d302776b896149fbcdd6d718438da/components/audio_stream/include/http_stream.h#L54)

Seems like [this event fires](https://github.com/espressif/esp-adf/blob/302f9a2c113d302776b896149fbcdd6d718438da/components/audio_stream/http_stream.c#L676) when we stop being able to read `http` data.

So perhaps it's a momentary MA server hiccup, or a network hiccup? I'll bump the streamserver log level to DEBUG and see if I can find anything new.

**Comment by johnboiles** [comment]
Stopped again. No interesting `streamserver` logs from MA at ~14:23 when it stopped streaming

```
2024-09-10 14:17:06.436 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
2024-09-10 14:20:54.978 DEBUG (MainThread) [music_assistant.streams.media_stream] stream finished (with code 0) for apple_music--JubAtrEv://track/912263297 - seconds streamed: 215.29541666666665
2024-09-10 14:20:54.978 DEBUG (MainThread) [music_assistant.streams.media_stream] Loudness measurement for apple_music--JubAtrEv://track/912263297: LoudnessMeasurement(integrated=-7.27, true_peak=0.38, lra=2.5, threshold=-17.39, target_offset=-0.04)
2024-09-10 14:20:55.050 DEBUG (MainThread) [music_assistant.streams] Finished Streaming queue track: apple_music--JubAtrEv://track/912263297 (Dreadsquad - Sweet & Nice (feat. El Fata)) on queue Main Stereo
2024-09-10 14:20:55.050 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1659724117
2024-09-10 14:20:56.629 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1659724117 in 1578 milliseconds
2024-09-10 14:20:56.634 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: apple_music--JubAtrEv://track/1659724117 (Kevin Morby - Mando Theme) for queue Main Stereo
2024-09-10 14:20:56.634 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--JubAtrEv://track/1659724117
2024-09-10 14:20:57.548 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
```

Same thing on ESPHome (stops receiving data at 14:23:00 and then times out a minute later):

```
[14:22:12][D][spdif:231][spdif_out]: 2880192 samples in 60.00s (48000.02Hz)
[14:23:00][E][spdif:112][i2s_event_task]: I2S_EVENT_TX_Q_OVF
[14:24:00][D][esp-idf:000][http]: W (13558355) HTTP_STREAM: No more data,errno:0, total_bytes:198874605, rlen = 0
[14:24:00][I][esp_audio_sources:033][http]: Receive http event: 7
```

**Comment by MarvinSchenkel** [comment]
Just had a look at the logs and all errors / warnings related to Apple Music seem to be caused by your library. You seem to have a lot of manually uploaded music without proper tags (e.g. albums without artists). The most interesting one that stands out is an artist with the id (!) (not the name) of "Yusuf / Cat Stevens". The Apple music API does not like the 'ID' and throws an error. However, not much I can do here because this again seems like a weird outlier in your library.

Stupid question, but is your ESP device in a clunky wifi location? I can also imagine that is causing drop outs.

@marcelveldt What does it mean when the webserver reports "Received non-text message" ?,

**Comment by johnboiles** [comment]
Yeah MA with Apple Music mixes and matches artists and songs on Apple Music for some reason. The artist name is wrong in the 'currently playing' display most of the time. This doesn't happen when I only use local filesystem. It's not a big deal since the playlists play the right songs, it's just the metadata display that's messed up.

The ESP32 has line of sight to the AP and I'm able stream logs from it without dropouts so I'm pretty confident it has a solid connection. I might swap in a board with Ethernet at some point.

I wonder what I can do to test the MA side of things. Maybe I stream the mp3 stream to VLC and see if that hiccups too? I have noticed MA is pretty taxing on my HA box (HA Yellow + CM4 4GB RAM + NVMe SSD) so perhaps the server gets stuck once in a while?

**Comment by special-k-uk** [comment]
I'm having the same issue, streaming stops after a few track and a couple of times a day. I'm using Spotify rather than apple, and synced squeeze lite players, but I am getting a different error message so not sure if it's related or a different issue.

For me this started yesterday after I upgraded from MA V2.1.4 to v2.2.3. 

```
2024-09-11 12:23:37.370 ERROR (MainThread) [music_assistant.streams.media_stream] Failed to stream spotify://track:2e07fhXF5JEEzvgpcC0gI5 - error: 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/helpers/audio.py", line 192, in _feed_stdin
    async for chunk in self.audio_input:
  File "/usr/local/lib/python3.12/site-packages/music_assistant/server/providers/spotify/__init__.py", line 601, in get_audio_stream
    raise AudioError(
music_assistant.common.models.errors.AudioError: Failed to stream spotify://track:2e07fhXF5JEEzvgpcC0gI5 - error: 1
```

**Comment by OzGav** [comment]
@special-k-uk youndo t have the same issue. That is fixed in the beta

**Comment by OzGav** [comment]
> Yeah MA with Apple Music mixes and matches artists and songs on Apple Music for some reason.

The reason Marvin has indicated is because the metadata in the uploaded tracks to Apple Music is incorrect.

Please confirm you have enabled the mp3 option for the player in MA settimgs

**Comment by johnboiles** [comment]
> the metadata in the uploaded tracks to Apple Music is incorrect.

I don't think that's true. Here's my MA right now. In this case it had the right artist, but it also had a bunch of other random artists:
<img width="380" alt="image" src="https://github.com/user-attachments/assets/ee3f0a57-0483-4cc9-9c53-be856b893b19">
<img width="790" alt="image" src="https://github.com/user-attachments/assets/e5cdcc2b-ec48-4669-ae12-88b63f4ff8df">
Should I open a separate issue for this metadata mismatching?

> Please confirm you have enabled the mp3 option for the player in MA settimgs

Confirmed, this is enabled by default for ESPHome media players I think.
<img width="756" alt="image" src="https://github.com/user-attachments/assets/4bbea69d-774d-447a-92a8-6f06cea62a9a">

**Comment by OzGav** [comment]
On the first point that was fixed in the latest beta. Do a db reset. MA SETTINGS>>CORE>>MUSIC CONTROLLER>>ADVANCED

Marvin pointed out some clear examples in the Apple Music errors which you need to fix.

**Comment by johnboiles** [comment]
I'll run a DB reset end of day after everyone is out of the office. Thanks for the idea!

Here's the metadata on the one `Yusuf / Cat Stevens` song that's in my library. This track is both on this `Quest - EP` and on the `Rushmore` soundtrack. The `Rushmore` soundtrack in one of the linked libraries, but it also shows up in this `Yusuf / Cat Stevens` EP I assume because it's the same track. What should I do to fix it? Regardless I'm betting these metadata errors on sync are a different issue than the music stopping periodically.
![Screenshot 2024-09-11 at 4 20 18 PM (1)](https://github.com/user-attachments/assets/cbfbef25-5e9b-4c74-bde4-41039e7c685c)

I opened the mp3 stream in Chrome and it ran for 1h 21m then stopped so it seems likely to me the mp3 stream is going  away sometimes. I'm going to try disabling `queue flow mode` and see if the mid-playlist stops still happen.

**Comment by OzGav** [comment]
I haven't looked at the log in detail but if the music is stopping between tracks then the metadata errors can cause the stoppage as the next track is fetched.

**Comment by johnboiles** [comment]
Two stream stops so far today. Both with `queue flow mode` enabled and disabled.

With `queue flow mode` enabled, the logs make it look like it just stops trying to play more tracks:
```
2024-09-12 09:56:30.889 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--4hmSTk5D://track/1584203629
2024-09-12 09:56:33.510 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
2024-09-12 09:59:56.985 DEBUG (MainThread) [music_assistant.streams.media_stream] stream finished (with code 0) for apple_music--4hmSTk5D://track/1584203629 - seconds streamed: 209.23502083333332
2024-09-12 09:59:56.985 DEBUG (MainThread) [music_assistant.streams.media_stream] Loudness measurement for apple_music--4hmSTk5D://track/1584203629: LoudnessMeasurement(integrated=-10.99, true_peak=0.01, lra=7.8, threshold=-21.45, target_offset=-0.98)
2024-09-12 09:59:57.082 DEBUG (MainThread) [music_assistant.streams] Finished Streaming queue track: apple_music--4hmSTk5D://track/1584203629 (Magic City Hippies - Limestone) on queue Main Stereo
2024-09-12 09:59:57.082 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1452906369
2024-09-12 09:59:58.678 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1452906369 in 1595 milliseconds
2024-09-12 09:59:58.699 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: apple_music--4hmSTk5D://track/1452906369 (Wet - Old Bone (Jim-E Stack Remix)) for queue Main Stereo
2024-09-12 09:59:58.700 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--4hmSTk5D://track/1452906369
2024-09-12 10:00:01.050 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
2024-09-12 10:03:24.903 DEBUG (MainThread) [music_assistant.streams.media_stream] stream finished (with code 0) for apple_music--4hmSTk5D://track/1452906369 - seconds streamed: 207.8418125
2024-09-12 10:03:24.903 DEBUG (MainThread) [music_assistant.streams.media_stream] Loudness measurement for apple_music--4hmSTk5D://track/1452906369: LoudnessMeasurement(integrated=-7.86, true_peak=0.39, lra=1.7, threshold=-18.07, target_offset=-0.24)
2024-09-12 10:03:25.017 DEBUG (MainThread) [music_assistant.streams] Finished Streaming queue track: apple_music--4hmSTk5D://track/1452906369 (Wet - Old Bone (Jim-E Stack Remix)) on queue Main Stereo
2024-09-12 10:03:25.017 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/696237539
2024-09-12 10:03:26.326 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/696237539 in 1308 milliseconds
2024-09-12 10:03:26.352 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: apple_music--JubAtrEv://track/696237539 (Dmitri Alexeev - Waltz No. 3 in A Minor, Op. 34 No. 2) for queue Main Stereo
2024-09-12 10:03:26.353 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--JubAtrEv://track/696237539
2024-09-12 10:03:30.405 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
2024-09-12 10:09:29.613 DEBUG (MainThread) [music_assistant.streams.media_stream] stream finished (with code 0) for apple_music--JubAtrEv://track/696237539 - seconds streamed: 369.0579583333333
2024-09-12 10:09:29.614 DEBUG (MainThread) [music_assistant.streams.media_stream] Loudness measurement for apple_music--JubAtrEv://track/696237539: LoudnessMeasurement(integrated=-26.74, true_peak=-7.88, lra=13.7, threshold=-37.45, target_offset=-0.25)
2024-09-12 10:09:29.696 DEBUG (MainThread) [music_assistant.streams] Finished Streaming queue track: apple_music--JubAtrEv://track/696237539 (Dmitri Alexeev - Waltz No. 3 in A Minor, Op. 34 No. 2) on queue Main Stereo
2024-09-12 10:09:29.696 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1533898831
2024-09-12 10:09:31.116 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1533898831 in 1419 milliseconds
2024-09-12 10:09:31.138 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: apple_music--4hmSTk5D://track/1533898831 (Rhye - Beautiful) for queue Main Stereo
2024-09-12 10:09:31.139 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--4hmSTk5D://track/1533898831
2024-09-12 10:09:33.641 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
2024-09-12 10:13:49.707 DEBUG (MainThread) [music_assistant.streams.media_stream] stream finished (with code 0) for apple_music--4hmSTk5D://track/1533898831 - seconds streamed: 261.99075
2024-09-12 10:13:49.707 DEBUG (MainThread) [music_assistant.streams.media_stream] Loudness measurement for apple_music--4hmSTk5D://track/1533898831: LoudnessMeasurement(integrated=-11.83, true_peak=0.15, lra=2.5, threshold=-22.05, target_offset=-0.3)
2024-09-12 10:13:49.863 DEBUG (MainThread) [music_assistant.streams] Finished Streaming queue track: apple_music--4hmSTk5D://track/1533898831 (Rhye - Beautiful) on queue Main Stereo
2024-09-12 10:13:49.863 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/480159189
2024-09-12 10:13:51.938 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/480159189 in 2074 milliseconds
2024-09-12 10:13:51.960 DEBUG (MainThread) [music_assistant.streams] Start Streaming queue track: apple_music--4hmSTk5D://track/480159189 (Do Make Say Think - Goodbye Enemy Airship) for queue Main Stereo
2024-09-12 10:13:51.961 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--4hmSTk5D://track/480159189
2024-09-12 10:14:00.710 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
```

Then the transcoding buffer empties out sometime later and the playback stops (in this case ~14 mins later)

```
[10:28:31][D][esp-idf:000][http]: W (172228197) HTTP_STREAM: No more data,errno:0, total_bytes:133214445, rlen = 0
```

With `queue flow mode` disabled. It looks like it stopped playing tracks around 11:32a.

```
2024-09-12 11:27:54.934 DEBUG (MainThread) [music_assistant.streams.media_stream] Loudness measurement for apple_music--4hmSTk5D://track/1647921831: LoudnessMeasurement(integrated=-15.3, true_peak=-1.16, lra=8.0, threshold=-25.84, target_offset=-0.88)
2024-09-12 11:29:10.255 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1577944652
2024-09-12 11:29:11.762 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1577944652 in 1507 milliseconds
2024-09-12 11:29:11.785 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1577944652
2024-09-12 11:29:12.063 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1577944652 in 278 milliseconds
2024-09-12 11:29:12.513 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem apple_music://track/1577944652 to Main Stereo
2024-09-12 11:29:12.519 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--4hmSTk5D://track/1577944652
2024-09-12 11:29:14.102 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
2024-09-12 11:29:14.803 DEBUG (MainThread) [music_assistant.streams.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1577944652 - seconds streamed: 2.0
2024-09-12 11:29:14.885 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem apple_music://track/1577944652 to Main Stereo
2024-09-12 11:29:14.891 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--4hmSTk5D://track/1577944652
2024-09-12 11:31:53.448 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/308750201
2024-09-12 11:31:55.279 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/308750201 in 1831 milliseconds
2024-09-12 11:31:55.302 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/308750201
2024-09-12 11:31:55.628 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/308750201 in 325 milliseconds
2024-09-12 11:31:56.073 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem apple_music://track/308750201 to Main Stereo
2024-09-12 11:31:56.080 DEBUG (MainThread) [music_assistant.streams.media_stream] start media stream for: apple_music--4hmSTk5D://track/308750201
2024-09-12 11:32:11.631 DEBUG (MainThread) [music_assistant.streams.media_stream] Detected (input) content type: aac (aac)
2024-09-12 11:32:12.277 DEBUG (MainThread) [music_assistant.streams.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/308750201 - seconds streamed: 2.0
2024-09-12 11:44:46.770 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
```

Then the player stopped at 11:43 (I also got that `Disconnected: Received non-Text message.` around that time, seems potentially related.

```
[11:43:27][D][esp-idf:000][http]: W (175866238) HTTP_STREAM: No more data,errno:0, total_bytes:5593383, rlen = 0
```

Is there something the media player could be neglecting to do that could cause MA to stop playing tracks (e.g. reporting timestamps correctly)? There are 628 songs on this playlist so there's plenty of media. Any ideas what other logs I could enable to keep digging here?

**Comment by OzGav** [comment]
Please try again with beta 23

**Comment by nikito** [comment]
Went fine for a while, then stopped again unfortunately. See this new message in the logs now: 
`2024-09-14 12:52:34.208 WARNING (MainThread) [music_assistant.spotify] librespot failed to stream track, retrying... (attempt 1/3)`

**Comment by nikito** [comment]
Some more logging from another occurrence: 
`2024-09-14 14:40:41.941 WARNING (MainThread) [music_assistant.spotify] librespot failed to stream track, retrying... (attempt 1/3)
2024-09-14 14:40:42.693 WARNING (MainThread) [music_assistant.spotify] librespot failed to stream track, retrying... (attempt 2/3)
2024-09-14 14:40:43.198 WARNING (MainThread) [music_assistant.audio.media_stream] Stream error on spotify--jdi6zRXV://track/4Fyab3mqEyw5fcROY5sWve
2024-09-14 14:40:43.224 ERROR (MainThread) [music_assistant.streams] Error streaming QueueItem Serj Tankian - The Unthinking Majority (library://track/1765) to Workshop Music`

**Comment by OzGav** [comment]
Well at least we can see the problem is an inability to get the next track from Spotify. Investigation will continue

**Comment by nikito** [comment]
Ah sorry thought i was in the Chromecast one! I'll try to repost these there and remove from here

**Comment by OzGav** [comment]
@johnboiles how did you go with beta 23?

**Comment by johnboiles** [comment]
@OzGav I'll try today (I mostly run MA at my office). Is there a recommended way of copying the config from my non-beta addon in HASSOS to my beta addon so that I'm recreating the same config?

**Comment by johnboiles** [comment]
Huh, haven't bumped to the beta yet, but I got a new issue this morning on 2.2.4 when I arrived to the office: It played the playlist that starts via automation, but it would only play about 3s of each song before switching to the next one. Should I file a new issue for this? Hitting pause didn't even stop it -- this continued until I stopped the container.

<details><summary>Log</summary>
<p>

    ```
    2024-09-16 09:04:38.790 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem Mondo Loops/Bcalm - Fragments (library://track/17602) to Main Stereo
    2024-09-16 09:04:38.797 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: apple_music--4hmSTk5D://track/1705967342
    2024-09-16 09:04:38.901 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1630225790 in 796 milliseconds
    2024-09-16 09:04:40.792 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for library://track/18850
    2024-09-16 09:04:41.081 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for library://track/18850 in 289 milliseconds
    2024-09-16 09:04:41.184 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1705967342 - seconds streamed: 2.0
    2024-09-16 09:04:41.495 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem Bcalm/Purrple Cat - Sunflowers (library://track/18850) to Main Stereo
    2024-09-16 09:04:41.502 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: apple_music--4hmSTk5D://track/1630225790
    2024-09-16 09:04:42.725 DEBUG (MainThread) [ffmpeg.1167] Detected (input) content type: aac (aac)
    2024-09-16 09:04:43.498 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1615738544
    2024-09-16 09:04:43.968 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1630225790 - seconds streamed: 3.0
    2024-09-16 09:04:43.984 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem Bcalm/Purrple Cat - Sunflowers (library://track/18850) to Main Stereo
    2024-09-16 09:04:43.991 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: apple_music--4hmSTk5D://track/1630225790
    2024-09-16 09:04:44.575 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1615738544 in 1076 milliseconds
    2024-09-16 09:04:45.986 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for library://track/17135
    2024-09-16 09:04:46.126 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1630225790 - seconds streamed: 2.0
    2024-09-16 09:04:46.186 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for library://track/17135 in 200 milliseconds
    2024-09-16 09:04:46.358 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem Pearldiver - Better Days (library://track/17135) to Main Stereo
    2024-09-16 09:04:46.368 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: apple_music--4hmSTk5D://track/1615738544
    2024-09-16 09:04:47.561 DEBUG (MainThread) [ffmpeg.1199] Detected (input) content type: aac (aac)
    2024-09-16 09:04:47.723 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1615738544 - seconds streamed: 4.0
    2024-09-16 09:04:48.049 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem Pearldiver - Better Days (library://track/17135) to Main Stereo
    2024-09-16 09:04:48.056 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: apple_music--4hmSTk5D://track/1615738544
    2024-09-16 09:04:49.287 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1615738544 - seconds streamed: 4.0
    2024-09-16 09:04:49.466 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem Pearldiver - Better Days (library://track/17135) to Main Stereo
    2024-09-16 09:04:49.473 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: apple_music--4hmSTk5D://track/1615738544
    2024-09-16 09:04:51.469 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1728775245
    2024-09-16 09:04:52.060 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1728775245 in 591 milliseconds
    2024-09-16 09:04:52.223 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1615738544 - seconds streamed: 21.0
    2024-09-16 09:04:52.471 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem cleh - mellow (library://track/18223) to Main Stereo
    2024-09-16 09:04:52.478 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: apple_music--4hmSTk5D://track/1728775245
    2024-09-16 09:04:53.737 DEBUG (MainThread) [ffmpeg.1247] Detected (input) content type: aac (aac)
    2024-09-16 09:04:54.474 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1671305376
    2024-09-16 09:04:54.972 DEBUG (MainThread) [music_assistant.streams] Start serving audio stream for QueueItem cleh - mellow (library://track/18223) to Main Stereo
    2024-09-16 09:04:54.978 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1728775245 - seconds streamed: 3.0
    2024-09-16 09:04:54.980 DEBUG (MainThread) [music_assistant.audio.media_stream] start media stream for: apple_music--4hmSTk5D://track/1728775245
    2024-09-16 09:04:55.107 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1671305376 in 632 milliseconds
    ```

</p>
</details>

**Comment by marcelveldt** [comment]
@johnboiles I released a patch for the issue you discovered in 2.2.5.
Can you give that a try ?

**Comment by johnboiles** [comment]
@marcelveldt after I deleted and recreated my players on 2.2.4 the issue didn't happen again. I didn't make a 2.2.3 backup so I don't have an easy way to downgrade and try the upgrade again sorry! I'll make backups next time.

**Comment by johnboiles** [comment]
Ok I'm seeing a pattern in the logs. Usually after a song finishes I get this log:
```
2024-09-17 13:23:50.571 DEBUG (MainThread) [music_assistant.audio.media_stream] stream finished (with code 0) for apple_music--JubAtrEv://track/1526653349 - seconds streamed: 368.4310208333333
```
But when the music stops I don't get that log. That means I'm never getting to [this line](https://github.com/music-assistant/server/blob/dffdcfe644776c8f0dad728d91e988ad58eba987/music_assistant/server/helpers/audio.py#L370). From a quick read of the code this could be caused by the ffmpeg [iterator getting stuck](https://github.com/music-assistant/server/blob/dffdcfe644776c8f0dad728d91e988ad58eba987/music_assistant/server/helpers/audio.py#L299), the ffmpeg process [never closing](https://github.com/music-assistant/server/blob/dffdcfe644776c8f0dad728d91e988ad58eba987/music_assistant/server/helpers/audio.py#L366). Or [`strip_silence` getting stuck](https://github.com/music-assistant/server/blob/dffdcfe644776c8f0dad728d91e988ad58eba987/music_assistant/server/helpers/audio.py#L342), 

Here's an example where that line is omitted. According to my ESPHome log we ran out of audio at 13:29:04.
```
2024-09-17 13:23:54.185 VERBOSE (MainThread) [ffmpeg.776] handler_name    : Core Media Audio
2024-09-17 13:23:54.186 VERBOSE (MainThread) [ffmpeg.776] vendor_id       : [0][0][0][0]
2024-09-17 13:23:54.186 VERBOSE (MainThread) [ffmpeg.776] encoder         : Lavc60.31.102 pcm_f32le
2024-09-17 13:37:20.898 DEBUG (MainThread) [music_assistant.audio] Getting streamdetails for apple_music://track/1603019071
2024-09-17 13:37:21.652 DEBUG (MainThread) [music_assistant.audio] retrieved streamdetails for apple_music://track/1603019071 in 753 milliseconds
```

Is the best way to develop and deploy for testing on my Home Assistant box to build the `server` [Dockerfile](https://github.com/music-assistant/server/blob/main/Dockerfile), and set up a HASS [add-on repo](https://developers.home-assistant.io/docs/add-ons/) to point to my new image?

**Comment by marcelveldt** [comment]
> Is the best way to develop and deploy for testing on my Home Assistant box to build the server [Dockerfile]

No the only way to develop is by using a mac or linux machine with Python 3.11 or 3.12 and run the setup script.
See development instructions. There is a dev container but in general that does not work as well as a venv.

**Comment by marcelveldt** [comment]
> But when the music stops I don't get that log. That means I'm never getting to [this line](https://github.com/music-assistant/server/blob/dffdcfe644776c8f0dad728d91e988ad58eba987/music_assistant/server/helpers/audio.py#L370). From a quick read of the code this could be caused by the ffmpeg [iterator getting stuck](https://github.com/music-assistant/server/blob/dffdcfe644776c8f0dad728d91e988ad58eba987/music_assistant/server/helpers/audio.py#L299), the ffmpeg process [never closing](https://github.com/music-assistant/server/blob/dffdcfe644776c8f0dad728d91e988ad58eba987/music_assistant/server/helpers/audio.py#L366). Or [strip_silence getting stuck](https://github.com/music-assistant/server/blob/dffdcfe644776c8f0dad728d91e988ad58eba987/music_assistant/server/helpers/audio.py#L342),

No, the code is all guarded for that. Especially since 2.3.0b26 where I fixed one more small edge case.
So, in any case, please test with that version first before going any further. 

It seems you are only reporting this for Apple Music, right ? Did you also test other sources ?

**Comment by special-k-uk** [comment]
So I'm still having the same issue.  Stream stops after about 10 minutes of playing.

MA v2024.9.1

I have 3 squeezelite players using the slimproto player provider, and one slimproto sync group. Playing to individual players appears to be ok, playing to the sync group generates this error

```
2024-09-29 15:31:25.909 INFO (MainThread) [music_assistant.streams] Start Queue Flow stream for Queue House - crossfade: False
2024-09-29 15:42:08.809 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
```

I'm aware of this issue which could be related https://github.com/music-assistant/hass-music-assistant/issues/2852 but as the error message is the same I thought best to post here.

**Comment by johnboiles** [comment]
> It seems you are only reporting this for Apple Music, right? Did you also test other sources?

Correct, only Apple Music right now. I don't have any other sources set up.

I was out of town for the week so no new data from me. I've downloaded 2.2.6. I'll try that version and report back.

**Comment by johnboiles** [comment]
Well that was quick today; the music stopped already. Exact same symptoms: the log doesn't show `stream finished`/`stream aborted`/`Stream error` but music stops.

@marcelveldt you say the code is all guarded from that, but can you explain why I wouldn't get either a [`Stream error`](https://github.com/music-assistant/server/blob/ad7541fcd7bfbb23b4a9a1e0032c543fe4f133fb/music_assistant/server/helpers/audio.py#L361) log or a [`stream finished`/`stream aborted`](https://github.com/music-assistant/server/blob/ad7541fcd7bfbb23b4a9a1e0032c543fe4f133fb/music_assistant/server/helpers/audio.py#L366) log? Looks like to me the _only_ way for those logs to not happen is if something is getting stuck in `get_media_stream` (e.g. the [iterator](https://github.com/music-assistant/server/blob/ad7541fcd7bfbb23b4a9a1e0032c543fe4f133fb/music_assistant/server/helpers/audio.py#L299), [`strip_silence`](https://github.com/music-assistant/server/blob/ad7541fcd7bfbb23b4a9a1e0032c543fe4f133fb/music_assistant/server/helpers/audio.py#L325), or [`ffmpeg_proc.close()`](https://github.com/music-assistant/server/blob/ad7541fcd7bfbb23b4a9a1e0032c543fe4f133fb/music_assistant/server/helpers/audio.py#L355).

My coworkers unplugged the MA player while I was gone because it didn't work reliably enough :(

**Comment by marcelveldt** [comment]
I am still investigating this issue but been a bit busy with other stuff last week so not enough time left. Just a bit patience is what's required here. Was able to reproduce it a couple of times now so that is a good start.

Well, the code is guarded (or I already ruled out) the examples you mentioned but that doesn't mean there is something else left. It indeed smells like something "silently crashing" and the exception swallowed. That or just some os-level buffer blocking. I have been monitoring the code with a lot of breakpoints in the debugger and indeed it just does never finish, it just blocks forever. Anyways, I will have bit more time to properly look at this issue (and another nasty issue) so keep an eye on the changelog of (beta) updates for info. I'll also try to update here but due to the high number of incoming bug/feature requests I can not always follow it all personally

**Comment by johnboiles** [comment]
I'm glad to hear you were able to repro. And yes, it does take some patience! Sometimes the issue doesn't happen for hours. Thanks for working on it!

**Comment by johnboiles** [comment]
Not sure if it's a related issue or a different issue, but this morning I'm getting an issue where the queue flow mode is cycling through my playlist but only playing 2-15 seconds each song. Here's the relevant part of the log:

```
2024-10-01 09:12:42.245 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1651724072 - seconds streamed: 4.0
2024-10-01 09:12:42.254 VERBOSE (MainThread) [ffmpeg.4182] Process ffmpeg with PID 4182 stopped with returncode 255
```

Sometimes I get messages about multiple processes stopped (perhaps the stuck ones finally exiting?)

```
2024-10-01 09:12:05.888 VERBOSE (MainThread) [ffmpeg.3942] Process ffmpeg with PID 3942 stopped with returncode 255
2024-10-01 09:12:05.889 VERBOSE (MainThread) [ffmpeg.3943] Process ffmpeg with PID 3943 stopped with returncode 255
2024-10-01 09:12:05.889 DEBUG (MainThread) [music_assistant.audio.media_stream] stream aborted (with code 255) for apple_music--4hmSTk5D://track/1703037761 - seconds streamed: 21.0
```

@marcelveldt should I open a separate issue for this or do you suspect it's the same root cause?

**Comment by OzGav** [comment]
Keeping open

**Comment by T3chArmy** [comment]
Just wanted to chime in, this has been occurring for me as well. This latest occurrence was while playing a local mp3 to a Chromecast speaker group. I am running the latest beta, 2.3.0b29, in a standalone docker container.

**Comment by T3chArmy** [comment]
> Please look at the original report before posting a +1. The OP is about Apple Music + ESP Home Player.

I posted here because I was also getting the 
`WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.` posted above that @marcelveldt mentioned he was looking into. I just wanted to provide another set of player/provider combination on that issue.

**Comment by OzGav** [comment]
We dont need combinations of things that aren’t working we need to narrow down what is causing the problem specifically, hence why the troubleshooting docs specify that we want to know what does work.

**Comment by T3chArmy** [comment]
I don't see the need for such hostility. 

Saying what doesn't work doesn't narrow down the issue? As a developer that would tell me that would most likely mean it's something that's common between those items such as a base class, and that it's likely not an issue with an individual provider.

Yes the initial report was that apple music playing on ESPHome, but that same issue is occurring in other platforms both on the music source side and on the player side. So it's a wider scale issue than just a single player provider or music source.

**Comment by johnboiles** [comment]
My Home Assistant Voice PE came in today so I decided to give it a try with MA. This issue persists. Here's the log from the Voice PE. Neat that we can do FLAC now at least. LMK if there's anything else I should pull to diagnose further:

```
[16:59:12][D][media_player:080]: 'Media Player' - Setting
[16:59:12][D][media_player:087]:   Media URL: http://192.168.1.2:8097/flow/media_player.home_assitant_voice_media_player/f4c4f9f2c22a44f19726a734493b53c3.flac?ts=1736557152
[16:59:12][D][nabu_media_player.pipeline:173]: Reading FLAC file type
[16:59:12][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[16:59:12][D][esp32.preferences:114]: Saving 1 preferences to flash...
[16:59:12][D][esp32.preferences:142]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[16:59:15][D][nabu_media_player.pipeline:184]: Decoded audio has 2 channels, 48000 Hz sample rate, and 16 bits per sample
[17:03:52][E][nabu_media_player:297]: The media pipeline's file reader encountered an error.
```

And the log from MA:

```
2025-01-10 16:59:56.886 VERBOSE (MainThread) [ffmpeg.592] Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://aod-ssl.itunes.apple.com/itunes-assets/Music116/v4/83/d9/f6/83d9f61e-f855-0d05-9544-7948362116d0/mzaf_A1608200705.rmhq.aac.wa.mp4':
2025-01-10 16:59:56.887 VERBOSE (MainThread) [ffmpeg.592] Metadata:
2025-01-10 16:59:56.887 VERBOSE (MainThread) [ffmpeg.592] major_brand     : mp42
2025-01-10 16:59:56.887 VERBOSE (MainThread) [ffmpeg.592] minor_version   : 1
2025-01-10 16:59:56.887 VERBOSE (MainThread) [ffmpeg.592] compatible_brands: mp41mp42isomhlsf
2025-01-10 16:59:56.887 VERBOSE (MainThread) [ffmpeg.592] creation_time   : 2022-02-02T16:05:20.000000Z
2025-01-10 16:59:56.888 VERBOSE (MainThread) [ffmpeg.592] Duration: 00:03:41.01, start: 0.000000, bitrate: 281 kb/s
2025-01-10 16:59:56.888 VERBOSE (MainThread) [ffmpeg.592] Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 276 kb/s (default)
2025-01-10 16:59:56.888 DEBUG (MainThread) [ffmpeg.592] Detected (input) content type: aac (aac)
2025-01-10 16:59:56.889 VERBOSE (MainThread) [ffmpeg.592] Metadata:
2025-01-10 16:59:56.889 VERBOSE (MainThread) [ffmpeg.592] creation_time   : 2022-02-02T16:05:20.000000Z
2025-01-10 16:59:56.889 VERBOSE (MainThread) [ffmpeg.592] handler_name    : Core Media Audio
2025-01-10 16:59:56.889 VERBOSE (MainThread) [ffmpeg.592] vendor_id       : [0][0][0][0]
2025-01-10 16:59:56.890 VERBOSE (MainThread) [ffmpeg.592] Side data:
2025-01-10 16:59:56.890 VERBOSE (MainThread) [ffmpeg.592] unknown side data type 24 (488 bytes)
2025-01-10 16:59:56.899 VERBOSE (MainThread) [ffmpeg.592] Stream mapping:
2025-01-10 16:59:56.900 VERBOSE (MainThread) [ffmpeg.592] Stream #0:0 -> #0:0 (aac (native) -> pcm_f32le (native))
2025-01-10 16:59:56.900 VERBOSE (MainThread) [ffmpeg.592] Press [q] to stop, [?] for help
2025-01-10 16:59:57.149 VERBOSE (MainThread) [ffmpeg.592] Output #0, f32le, to 'pipe:':
2025-01-10 16:59:57.150 VERBOSE (MainThread) [ffmpeg.592] Metadata:
2025-01-10 16:59:57.150 VERBOSE (MainThread) [ffmpeg.592] major_brand     : mp42
2025-01-10 16:59:57.150 VERBOSE (MainThread) [ffmpeg.592] minor_version   : 1
2025-01-10 16:59:57.150 VERBOSE (MainThread) [ffmpeg.592] compatible_brands: mp41mp42isomhlsf
2025-01-10 16:59:57.150 VERBOSE (MainThread) [ffmpeg.592] encoder         : Lavf60.16.100
2025-01-10 16:59:57.150 VERBOSE (MainThread) [ffmpeg.592] Stream #0:0(und): Audio: pcm_f32le, 48000 Hz, stereo, flt, 3072 kb/s (default)
2025-01-10 16:59:57.150 VERBOSE (MainThread) [ffmpeg.592] Metadata:
2025-01-10 16:59:57.151 VERBOSE (MainThread) [ffmpeg.592] creation_time   : 2022-02-02T16:05:20.000000Z
2025-01-10 16:59:57.151 VERBOSE (MainThread) [ffmpeg.592] handler_name    : Core Media Audio
2025-01-10 16:59:57.151 VERBOSE (MainThread) [ffmpeg.592] vendor_id       : [0][0][0][0]
2025-01-10 16:59:57.151 VERBOSE (MainThread) [ffmpeg.592] encoder         : Lavc60.31.102 pcm_f32le
2025-01-10 16:59:57.151 VERBOSE (MainThread) [ffmpeg.592] Side data:
2025-01-10 16:59:57.151 VERBOSE (MainThread) [ffmpeg.592] unknown side data type 24 (488 bytes)
2025-01-10 17:06:10.715 WARNING (MainThread) [music_assistant.webserver] Disconnected: Received non-Text message.
```

Same issue [as before](https://github.com/music-assistant/support/issues/2893#issuecomment-2356948099), the 'stream finished` log never happens, which maybe means the ffmpeg process got stuck.

**Comment by johnboiles** [comment]
Some interesting investigation into FFMPEG hangs [here](https://github.com/music-assistant/support/issues/3257) that might be relevant.

**Comment by johnboiles** [comment]
Sure enough when audio gets stuck I see the two FFMPEG processes running forever:

```
/app/venv # ps aux
PID   USER     TIME  COMMAND
    1 root      6:12 {mass} /app/venv/bin/python3 /app/venv/bin/mass --config /data
   42 root      3:12 snapserver --server.datadir=/data --http.enabled=true --http.port=1780 --http.doc_root=/app/venv/lib/python3.12/site-packages/music_
   52 root      8:44 ffmpeg -hide_banner -loglevel info -nostats -ignore_unknown -protocol_whitelist file,hls,http,https,tcp,tls,crypto,pipe,data,fd,rtp,
  154 root      0:00 /bin/sh
  170 root      1:01 ffmpeg -hide_banner -loglevel info -nostats -ignore_unknown -protocol_whitelist file,hls,http,https,tcp,tls,crypto,pipe,data,fd,rtp,
  180 root      0:00 ps aux
```
