### ISSUE TITLE
Playback stops after a single track when playing on chromecast group

### ISSUE THREAD

**Issue by hundredfire** [music-assistant/hass-music-assistant#3078]
### What version of Music Assistant has the issue?

2.4.0b0

### What version of the Home Assistant Integration have you got installed?

2024.10.3

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When enqueuing a playlist to a **chromecast audio group**, a single track plays then playback stops. The next track does not play (see screenshot attached). If I press 'next' in Music assistant's web interface, the next track plays, then stops.   
(not sure if it's related, but the progress bar stops at 3/4)

**Everything works normally when I cast to a single chromecast device.** 
 
![Screenshot 2024-10-25 112025](https://github.com/user-attachments/assets/47bde244-24e7-4eed-9ae4-3dfd5ad05d98)

### How to reproduce

Enqueue playlist to chromecast group
Let track play and finish
Playback stops

### Music Providers

Youtube music

### Player Providers

Problematic player: Chromecast audio group (containing a google nest mini and a chromecast audio puck)

Non-problematic player: Single chromecast devices

### Full log output

Logs when I cast to chromecast group: [casting to group.log](https://github.com/user-attachments/files/17519827/casting.to.group.log)

Logs when I cast to single chromecast device (chromecast audio puck): 
[casting to single chromecast.log](https://github.com/user-attachments/files/17519838/casting.to.single.chromecast.log)

### Additional information

Tried restarting HAOS, clearing cache. Bug appears when enqueuing playlists or albums, from web-interface or automation indifferently.
Repeat modes don't help (bug appears even when choosing "repeat single track") 

To be clear, this didn't happen in 2.3b. The bug started after updating to 2.4b0

### What version of Home Assistant Core are your running

2024.10.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Confirmed. This will be looked at soon.

**Comment by OzGav** [comment]
@hundredfire please confirm this is fixed in 2.3.1/2.4.0b1

**Comment by bengthu** [comment]
I'm also having the same trouble. I can confirm that rolling back to 2.2.7 fixes this issue.

After updating to Server version is 2.3.1, I started playing my first track, then Home A "lost connection" for longer than I would expect - about 3-4 minutes. After restarting it took a minute to refresh Music A. Played the 500 Random playlist, and the file stops the player at the end of the song.

**Comment by hundredfire** [comment]
@OzGav Sorry for replying so late. Just updated to 2.4.0b2, cleared cache and restarted HAOS (just in case), but the bug persists. Here's a log:
[music-assistant.log](https://github.com/user-attachments/files/17529818/music-assistant.log)

**Comment by hundredfire** [comment]
@bengthu The queue flow mode did temporarily solve the issue, thanks for the suggestion. I feel a bit dumb because I did read this step in the Troubleshooting guide, but couldn't find this setting...
We lose some functionality though, so I think I shouldn't close the issue

**Comment by Panoramiac** [comment]
Same for me using DLNA and a Denon AV receiver as player. Stops playing after the first track. When I press next in the UI and play it starts the next track.

**Comment by bengthu** [comment]
Updated to Server 2.3.2.
Turned OFF **Enable queue flow mode**.
Played **500 random tracks** playlist.
Player now doesn't stop after one song! I'm on my third now with no interruption.

Thank you!

**Comment by hundredfire** [comment]
Great job, this is fixed. Thanks a lot
