### ISSUE TITLE
TTS not working

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#315]
For me TTS didn't work yet. If one of the players is running with the volume on 100%, TTS attempt failed. This was the screen:
![image](https://user-images.githubusercontent.com/4363599/172453413-1ead7a8e-cb64-4408-8683-b8b596f3c642.jpeg)
When als players have their volume below 90%, the current queue is interrupted, but no announcement is played, and shortly later the music continues.

I noticed errors in the log:

``` 
Logger: homeassistant.components.websoc ket_api.http.connection
Source: components/cast/ media_player.py:502
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:25:14 (1 occurrences)
Last logged: 20:25:14
[547652456560] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/ homeassistant/components/ websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/ mass/websockets.py", line 98, in async_get_mass_func
await orig_func(hass, connection, msg, mass)
File "/config/custom_components/ mass/websockets.py", line 909, in websocket_playerqueue_command
await player_queue.player.volume_set(int( msg[COMMAND_ARG]))
File "/config/custom_components/ mass/player_controls.py", line 300, in volume_set
await self.hass.services.async_call(
File "/usr/src/homeassistant/

homeassistant/core.py", line 1704, in async_call
task.result()
File "/usr/src/homeassistant/
homeassistant/core.py", line 1741, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/ homeassistant/helpers/ entity_component.py", line 204, in handle_service
await service.entity_service_call( File "/usr/src/homeassistant/
homeassistant/helpers/service.py", line 680, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/ homeassistant/helpers/entity.py", line 964, in async_request_call
await coro
File "/usr/src/homeassistant/
homeassistant/helpers/service.py", line 717, in _handle_entity_call
await result
File "/usr/src/homeassistant/
homeassistant/components/ media_player/__init__.py", line 712, in async_set_volume_level
await self.hass.async_add_executor_ job( self.set_volume_level, volume)
File "/usr/local/lib/python3.9/ concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)

File "/usr/src/homeassistant/ homeassistant/components/cast/ media_player.py", line 502, in set_volume_level
self._chromecast.set_volume(volum e)
File "/usr/local/lib/python3.9/site- packages/pychromecast/ controllers/receiver.py", line 181, in set_volume
self.send_message({MESSAGE_TYP E: "SET_VOLUME", "volume": {"level": volume}})
File "/usr/local/lib/python3.9/site- packages/pychromecast/ controllers/__init__.py", line 121, in send_message
self.send_message_nocheck( File "/usr/local/lib/python3.9/site-
packages/pychromecast/ controllers/__init__.py", line 133, in send_message_nocheck
self._message_func(
File "/usr/local/lib/python3.9/site-
packages/pychromecast/ socket_client.py", line 938, in send_platform_message
return self.send_message(
File "/usr/local/lib/python3.9/site-
packages/pychromecast/ socket_client.py", line 927, in send_message
raise NotConnected(f"Chromecast {self.host}:{self.port} is connecting...") pychromecast.error.NotConnected:

Chromecast 192.168.178.38:8009 is connecting...
```

**Comment by erkr** [comment]
Update v06b3. Noticed this error in the log after a tts attempt:
``` 
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/mass/player_controls.py:448 
Integration: Music Assistant (documentation, issues) 
First occurred: 20:55:48 (1 occurrences) 
Last logged: 20:55:48

Error executing service: <ServiceCall media_player.play_media (c:01G5A1YB9Z8W85AGTT62NTVRS2): entity_id=['media_player.mass_everywhere_57'], extra=, media_type=provider, media_id=media-source://tts/google_translate?message=Freij+is+doing+nice+things>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1722, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/mass/media_player.py", line 393, in async_play_media
    await self.player.active_queue.play_alert(media_id, announce_sound)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 309, in play_alert
    await self.load(queue_items)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 493, in load
    await self.play_index(0, passive=passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 451, in play_index
    await self.queue_stream_start(index, int(seek_position), fade_in, passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 662, in queue_stream_start
    await self.player.play_url(stream.url)
  File "/config/custom_components/mass/player_controls.py", line 448, in play_url
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/quick_play.py", line 77, in quick_play
    controller.quick_play(**data)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/media.py", line 544, in quick_play
    raise PyChromecastError()
pychromecast.error.PyChromecastError
```

**Comment by erkr** [comment]
Same test with one CC:
``` 
This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/mass/player_controls.py:448 
Integration: Music Assistant (documentation, issues) 
First occurred: 21:25:59 (1 occurrences) 
Last logged: 21:25:59

Error executing service: <ServiceCall media_player.play_media (c:01G5A3NM7N425NCT5PT3YKR1X1): entity_id=['media_player.mass_audio57serre'], extra=, media_type=provider, media_id=media-source://tts/google_translate?message=Dit+is+een+test>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1722, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/mass/media_player.py", line 393, in async_play_media
    await self.player.active_queue.play_alert(media_id, announce_sound)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 309, in play_alert
    await self.load(queue_items)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 493, in load
    await self.play_index(0, passive=passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 451, in play_index
    await self.queue_stream_start(index, int(seek_position), fade_in, passive)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 662, in queue_stream_start
    await self.player.play_url(stream.url)
  File "/config/custom_components/mass/player_controls.py", line 448, in play_url
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/quick_play.py", line 77, in quick_play
    controller.quick_play(**data)
  File "/usr/local/lib/python3.9/site-packages/pychromecast/controllers/media.py", line 544, in quick_play
    raise PyChromecastError()
pychromecast.error.PyChromecastError
```

**Comment by Mariusthvdb** [comment]
hopping over from the Sonos issue, Marcel I can confirm that returning to the core media_players for TTS messages, takes away the intermittent stops in the messages, and the delay.
Moreover, when playing to a group of active players, either by using an actual group entity, or by using a template listing the individual media_player entities, also works as before using the core media_players for GoogleHome's.

Using the mass_players in an identical setting causes huge delays and stops. And I am not ye talking about the additional 'Bell' sound (which I should file a FR for to make that optional...)

for reference, the template:
```
{{expand('media_player.broadcast')
                          |rejectattr('state','in',['unknown','unavailable'])
                          |map(attribute='entity_id')|list|join(',')}}
```

so it only streams to available players. The group I mention is auto created like:
```
      - service: group.set
        data:
          object_id: media_players_available
          name: Media players available
          entities: >
            {{expand('media_player.broadcast')
               |rejectattr('state','in',['unknown','unavailable'])
               |map(attribute='entity_id')|join(',')}}
```

and works perfectly in core Ha and with core HA medias_players.

hope this helps.

**Comment by erkr** [comment]
Additional info: When using the mass players only kind of works  (stuttering remains) for longer messages over 10 seconds as discussed over discord earlier.

**Comment by Mariusthvdb** [comment]
not sure if this was discussed before,  but could it have to do with saving to cache of the tts mp3 messages?

**Comment by erkr** [comment]
V06b5 is working much better. Chapeau! Birth long and short announcements are working now. Errors in the log are gone. I only noticed a warning. Not sure if it's relevant for now:
``` 
Logger: music_assistant.stream
Source: /usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py:147 
First occurred: 15:57:17 (2 occurrences) 
Last logged: 15:57:28

Got stream request for unknown id: 23905382df99419b8c9190d6cba23a0b
Got stream request for unknown id: 1e3621d6c27c4c86962b302f46869269
```

**Comment by marcelveldt** [comment]
That stream request log is interesting because that means that the player is reconnecting while it already stopped.

**Comment by marcelveldt** [comment]
I think we should leave this issue open because it should also work with grouped media players.

**Comment by erkr** [comment]
Yep, completed but not fully tested.
I just tried a TTS related scenario, using the play_media service to announce a prerecorded mp3 (skipping the TTS part):
```
service: media_player.play_media
data:
  media_content_id: /media/local/Door-Bell-Ding-A2-www.fesliyanstudios.com.mp3
  media_content_type: Music
  announce: true
target:
  entity_id: media_player.mass_everywhere_57
``` 

That amazingly works as well (ping, mp3 and the radio nicely resumed)
But there where these two errors in the log:
``` 
Failed to cast media http://192.168.178.47:8095/a53a4dbe4e384ce7bda3dcc4c3741d83.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
16:39:31 – (ERROR) Google Cast
Error handling request
16:39:31 – (ERROR) /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py
``` 
Detailed:
```
Logger: homeassistant.components.cast.media_player
Source: components/cast/media_player.py:388 
Integration: Google Cast (documentation, issues) 
First occurred: 16:39:31 (1 occurrences) 
Last logged: 16:39:31

Failed to cast media http://192.168.178.47:8095/a53a4dbe4e384ce7bda3dcc4c3741d83.flac. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
```
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405 
First occurred: 16:39:31 (1 occurrences) 
Last logged: 16:39:31

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 160, in serve_queue_stream
    await queue_stream.subscribe(client_id, resp.write)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 302, in subscribe
    assert not self.done.is_set(), "Stream task is already finished"
AssertionError: Stream task is already finished
```

After several announcement's it broke (radio didn't resume).
That happens when I invoke the requests to fast after each other!

**Comment by erkr** [comment]
Same errors can occure when using TTS via the media browser

**Comment by erkr** [comment]
Verified this issue for beta7 and for me it;s totally broken. Sometimes a ping, sometimes hanging UI. Reload of MA needed to recover. Several errors ion the log:
```
[547393010608] Error handling message: Unknown error (unknown_error)
20:37:59 – (ERROR) Home Assistant WebSocket API (custom integration)
Error doing job: Task exception was never retrieved
20:37:45 – (ERROR) /usr/src/homeassistant/homeassistant/runner.py - message first occurred at 20:37:45 and shows up 3 times
Error doing job: Task exception was never retrieved
20:37:45 – (ERROR) Music Assistant (custom integration)
[547393010608] Error handling message: Unknown error (unknown_error)
20:37:45 – (ERROR) Home Assistant WebSocket API (custom integration) - message first occurred at 20:37:41 and shows up 4 times
Error doing job: Task exception was never retrieved
20:37:45 – (ERROR) /usr/src/homeassistant/homeassistant/runner.py - message first occurred at 20:37:41 and shows up 3 times
```

**Comment by marcelveldt** [comment]
please test this with 2022.6.0/2022.6.1, it should be fixed

**Comment by erkr** [comment]
Will test today

**Comment by erkr** [comment]
TTS still not robust. Fisrt attempt:  Misc paused, TTS played, but no resume
The queue of the player was corrent and these messages in the log:
```
[547128774608] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/mass/websockets.py", line 101, in async_get_mass_func
    await orig_func(hass, connection, msg, mass)
  File "/config/custom_components/mass/websockets.py", line 873, in websocket_playerqueue_items
    result = [x.to_dict() for x in queue.items]
  File "/config/custom_components/mass/websockets.py", line 873, in <listcomp>
    result = [x.to_dict() for x in queue.items]
AttributeError: 'NoneType' object has no attribute 'to_dict'
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:96
First occurred: 19:33:58 (2 occurrences)
Last logged: 19:33:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 796, in _save_items
    "items": [x.to_dict() for x in self._items],
  File "/usr/local/lib/python3.9/site-packages/music_assistant/models/player_queue.py", line 796, in <listcomp>
    "items": [x.to_dict() for x in self._items],
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

Second try (after a reload) crashed earlier, before the ping, queue corrupt. Now these errors:
```
Error doing job: Task exception was never retrieved
19:47:28 – (ERROR) /usr/src/homeassistant/homeassistant/runner.py - message first occurred at 19:47:28 and shows up 2 times
[Everywhere_57(192.168.178.38):32034] Failed to connect to service ServiceInfo(type='host', data=('192.168.178.38', 32034)), retrying in 5.0s
19:47:28 – (ERROR) /usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py
[Everywhere_57(192.168.178.32):32034] Error communicating with socket, resetting connection
19:47:28 – (WARNING) /usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py
```

**Comment by erkr** [comment]
I think it's an add tracks to queue relate issue, as that doesn't work properly anymore as well (issue #392)

**Comment by erkr** [comment]
Update on testing with v2022.6.2:
The function works. I triggered the TTS several times.

Some things I noticed, are probably worth looking into before closing:
- Noticeable longer delays, more than the version that worked for me a few beta's before (the one I made are recording)
- Players have a lot of state changes, Also the MA player and player cards start flickering for seconds (see logbook image)
- The volume of TTS was intentionally a little louder in the past, Now it's about half the volume of my music ?!

The state changes for one player, when running a TTS:
![image](https://user-images.githubusercontent.com/4363599/174443838-975e488c-b279-4763-97d8-761cbec97c33.png)

**Comment by marcelveldt** [comment]
Can you please retest with 2022.6.4 ? I've adjusted the buffer a bit so the CC shouldn't be buffering that much (hence all the state changes)

**Comment by erkr** [comment]
I can do that today, just installed 6.4

**Comment by erkr** [comment]
I see one idle state less only. 
It's a little faster I think
If the volume is supposed to be louder, its still below the music volume
![image](https://user-images.githubusercontent.com/4363599/174588869-ae14e779-dee2-4ec3-a112-f698e4abdba0.png)

**Comment by marcelveldt** [comment]
are you testing this against a CC group or single player ?
what's your volume normalization setting ?

Note that the alert sound is leveled at (more or less) 0db while the regular music is leveled at the value set in the player settings. The whole idea is that your volume normalization leaves headroom for peaks in music so the baseline will be less loud than the alert sound.

Alternative is that MA adjusts the actual volume of the player but that means additional calls to the player

**Comment by erkr** [comment]
This was using a group cast. The logbook was just filtering one player to have a more concise view on the state changes.
As discussed on discord, I run with default normalization, now -14 LUFS, 
When going to the old -23 value the TTS is louder

**Comment by erkr** [comment]
We decided to document the volume relation
