### ISSUE TITLE
Playback not working on Kodi/OSMC

### ISSUE THREAD

**Issue by jeroenterheerdt** [music-assistant/hass-music-assistant#358]
I have a whole-house audio system using OSMC - It is showing up as player in Home Assistant, and I can control it from there (i.e. pause playback once it is playing). However, music assistant does not actually start playback on OSMC. 
The OSMC is online and fully functional.

Whenever I try to play something from music assistant to OSMC, I see this in the logs:
```
2022-06-16 10:08:59 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 160, in serve_queue_stream
await queue_stream.subscribe(client_id, resp.write)
File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 311, in subscribe
assert not self.done.is_set(), "Stream task is already finished"
AssertionError: Stream task is already finished
2022-06-16 10:09:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 160, in serve_queue_stream
await queue_stream.subscribe(client_id, resp.write)
File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 311, in subscribe
assert not self.done.is_set(), "Stream task is already finished"
AssertionError: Stream task is already finished
2022-06-16 10:09:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 160, in serve_queue_stream
await queue_stream.subscribe(client_id, resp.write)
File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 311, in subscribe
assert not self.done.is_set(), "Stream task is already finished"
AssertionError: Stream task is already finished
2022-06-16 10:09:00 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 160, in serve_queue_stream
await queue_stream.subscribe(client_id, resp.write)
File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 311, in subscribe
assert not self.done.is_set(), "Stream task is already finished"
AssertionError: Stream task is already finished
```

and
```
2022-06-16 10:03:03 ERROR (MainThread) [homeassistant.components.kodi.media_player] Error calling async_update on entity media_player.osmc: TransportError("Error calling method 'Player.GetActivePlayers': Transport Error", TimeoutError())
2022-06-16 10:03:17 ERROR (MainThread) [homeassistant.components.kodi.media_player] Error calling async_update on entity media_player.osmc: TransportError("Error calling method 'Player.GetActivePlayers': Transport Error", ClientConnectorError(ConnectionKey(host='192.168.1.49', port=80, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=1996882747), ConnectionRefusedError(111, "Connect call failed ('192.168.1.49', 80)")))
```

is this supposed to work? anything I can do to help?

**Comment by erkr** [comment]
Hi Jeroen

I'm not familiar with OSMC, but it is a media center by itself. not sec a media player (speaker alike). The players that are confirmed to work with MA are these (readme):
[Google Cast players](https://www.home-assistant.io/integrations/cast/)
[Kodi](https://www.home-assistant.io/integrations/kodi/)
[Slimproto Squeezebox players](https://www.home-assistant.io/integrations/slimproto/)
[Sonos](https://www.home-assistant.io/integrations/sonos/)
[Linkplay](https://github.com/nagyrobi/home-assistant-custom-components-linkplay)

As OSMC claims to be able to stream from other devices, it most likely is possible, but you are the first one trying these players with MA. I propose to change this issue into a Feature Request if you like.

I guess Marcel will have a look at the loggings as well. Thanks !!!
Best Eric

**Comment by marcelveldt** [comment]
Kodi = OSMC and that used to work once. Looking at the log it's connecting and disconnecting again.
I will try a Kodi player later this week

**Comment by erkr** [comment]
Ok a bug instead :-)

**Comment by marcelveldt** [comment]
I checked in a small fix that might be related to this issue. I noticed some players do an HTTP HEAD request before they fetch the actual audio data (GET request). The streamer was already launched on the HEAD request and that's what I fixed. Maybe this issue is now fixed (I did not test it yet) ?

**Comment by marcelveldt** [comment]
Cool, my mistake confirms that it's indeed a head request being made. So if I fix the sloppy assignment issue I think it should work. Fingers crossed for next release ;-)

**Comment by marcelveldt** [comment]
@jeroenterheerdt can you check if this issue is resolved with the 2022.6.2 version ?

**Comment by jeroenterheerdt** [comment]
unfortunately it is not. The assignment error is gone, but the stream problem is the same:

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py:405
First occurred: 4:53:53 PM (4 occurrences)
Last logged: 5:08:05 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 168, in serve_queue_stream
    await queue_stream.subscribe(client_id, resp.write)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 318, in subscribe
    assert not self.done.is_set(), "Stream task is already finished"
AssertionError: Stream task is already finished
```

I want to note that if OSMC is already playing the playback is stopped, so it's definitely communicating with music assistant, but unfortunately the playback never starts (regardless if OSMC was idle or not before trying to play from music assistant).

**Comment by marcelveldt** [comment]
Problem is that the player does a duplicate request. Once to do a metadata lookup and then the real request.
By that time the streamsession is already closed. I'll try if I can auto detect this and if not introduce a small toggle.

**Comment by marcelveldt** [comment]
Added Kodi to the title because it is practically the same as OSMC and has this same issue.

**Comment by marcelveldt** [comment]
Looked at this issue today. Kodi is doing 4 (!!) requests to the stream (HEAD request twice and 2 GET's) which is why it fails.
I have no idea why Kodi is doing that or what it expects from Music Assistant to answer. I could write a very ugly workaround to simply ignore the first disconnecting requests but I'd rather want to fix it at its roots.

@koying this looks similar to the issue with [Mopidy](https://github.com/music-assistant/hass-music-assistant/discussions/439) - do you by any chance have such an advanced trick for Kodi too ?
Or is there something I can do at the MA side with headers or such to let Kodi back off with the additional requests ?

**Comment by koying** [comment]
I don't know, sorry.
Probably best asked on the Kodi forum how those "single-use url" are/should be handled.

I suspect Kodi might open the stream the 1st time to analyse and create the proper playback path, as it typically doesn't rely on filenames...

**Comment by marcelveldt** [comment]
Been testing for a few hours and Kodi behaves really strange when it comes to connecting to a FLAC stream (without duration) and keeps connecting over and over completely ignoring the fact that there is no content length. It even fails to detect the content type from the headers even though it is literally set to "audio/flac".

Even when I ignore the duplicate GET request and get it playing it keeps connecting over and over with multiple requests for no reason. Only when I serve a file with an actual duration it calms down and it accepts the request. Point is that a FLAC stream of no duration is served, just like an online radio stream. So I decided to monitor Kodi (debug log turned on) while connecting to a random radio stream from internet. Guess what, same behavior. Duplicate HEAD request, GET request and a final GET request including a request for ICY metadata. So there is an implementation error in Kodi undetected. The details should have been grabbed in the first HEAD request. 

Anyways.... If somebody want to discuss that with the Kodi devs that's probably the best solution as it is a broader issue and not just with MA. Difference is that MA disconnects the stream on that second GET request.

I'll implement a (hopefully temporary) workaround in the code. If the user agent matches Kodi/OSMC I will ignore the first GET request and only start the stream on the second. I'll pass in some silence in the first request just to not upset the whole thing.

My feeling of what is wrong is that Kodi is trying to fetch the duration from the actual stream, hence the first GET request.
That duration is not going to be there because it is an "endless" FLAC stream. I even tried instructing ffmpeg to write a duration of 48 hours but that is not possible as it seems.

Please test the fix/workaround in next 2022.6.5 patch release.
Thanks!

**Comment by marcelveldt** [comment]
Oh btw also some good news from this. I actually implemented ICY metadata now in the stream so that Kodi actually displays whatever is playing.

**Comment by marcelveldt** [comment]
fix released in 2022.6.5. Thanks!

**Comment by OliPassey** [comment]
Still not working here im afraid, on latest version.
Seems to load / play for 1 / 3 secs then stops as before.

Im on latest HA, MA & Kodi

**Comment by marcelveldt** [comment]
Did you test it from the Music Assistant panel itself ?

**Comment by OliPassey** [comment]
Yes.
Tried a Spotify Track from a playlist and a local file - both fail to play here.

**Comment by marcelveldt** [comment]
If it does still fail there's nothing I can do anymore and Kodi/OSMC will move to the "unsupported" section until they fix their bugs.

**Comment by OliPassey** [comment]
![image](https://user-images.githubusercontent.com/7745805/175502018-9767531e-04b7-424f-b97b-06ef259b8d63.png)
Yes, i confirm im using Music Assistant and not the media browser.

**Comment by OliPassey** [comment]
1.) Yes & Yes. If you tell me where i can copy this info out of HA to prove it to you i'll take a screenshot.
MA:  2022.6.5 (from HACS)
HA: 
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

2.)
```
2022-06-24 10:09:19 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.
2022-06-24 10:09:20 ERROR (MainThread) [homeassistant.components.automation.hasp_p_8_b_all_page_8_displays_media_controls] Error rendering variables: ValueError: Template error: int got invalid input 'None' when rendering template '{%- set color = namespace() -%} {%- for entity in device_entities(haspdevice) -%}
  {%- if entity|regex_search("^light\..*_selected_foreground_color(?:_\d+|)$") -%}
    {%- set color.source=entity -%}
  {%- endif -%}
{%- endfor -%} {%- set brightness = state_attr(color.source, "brightness")|int / 255 -%} {%- set red=(state_attr(color.source, "rgb_color")[0] * brightness)|int -%} {%- set green=(state_attr(color.source, "rgb_color")[1] * brightness)|int -%} {%- set blue=(state_attr(color.source, "rgb_color")[2] * brightness)|int -%} {{ (red|bitwise_and(248)*256) + (green|bitwise_and(252)*8) + (blue|bitwise_and(248)/8)|int }}' but no default was specified
2022-06-24 10:09:20 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.
2022-06-24 10:09:20 WARNING (MainThread) [music_assistant.players.stream] Reconnect of player 10.0.0.7 detected, playback may be disturbed
2022-06-24 10:09:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 225, in serve_queue_stream
    await queue_stream.subscribe(client_id, audio_callback)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 378, in subscribe
    assert client_id not in self.connected_clients, "Client is already connected"
AssertionError: Client is already connected
2022-06-24 10:09:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 225, in serve_queue_stream
    await queue_stream.subscribe(client_id, audio_callback)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 378, in subscribe
    assert client_id not in self.connected_clients, "Client is already connected"
AssertionError: Client is already connected
2022-06-24 10:09:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 225, in serve_queue_stream
    await queue_stream.subscribe(client_id, audio_callback)
  File "/usr/local/lib/python3.9/site-packages/music_assistant/controllers/streams.py", line 378, in subscribe
    assert client_id not in self.connected_clients, "Client is already connected"
AssertionError: Client is already connected
2022-06-24 10:09:21 ERROR (MainThread) [homeassistant.components.automation.hasp_p_8_b_all_page_8_displays_media_controls] Error rendering variables: ValueError: Template error: int got invalid input 'None' when rendering template '{%- set color = namespace() -%} {%- for entity in device_entities(haspdevice) -%}
  {%- if entity|regex_search("^light\..*_selected_foreground_color(?:_\d+|)$") -%}
    {%- set color.source=entity -%}
  {%- endif -%}
{%- endfor -%} {%- set brightness = state_attr(color.source, "brightness")|int / 255 -%} {%- set red=(state_attr(color.source, "rgb_color")[0] * brightness)|int -%} {%- set green=(state_attr(color.source, "rgb_color")[1] * brightness)|int -%} {%- set blue=(state_attr(color.source, "rgb_color")[2] * brightness)|int -%} {{ (red|bitwise_and(248)*256) + (green|bitwise_and(252)*8) + (blue|bitwise_and(248)/8)|int }}' but no default was specified
2022-06-24 10:09:21 ERROR (MainThread) [homeassistant.components.automation.hasp_p_8_b_all_page_8_displays_media_controls] Error rendering variables: ValueError: Template error: int got invalid input 'None' when rendering template '{%- set color = namespace() -%} {%- for entity in device_entities(haspdevice) -%}
  {%- if entity|regex_search("^light\..*_selected_foreground_color(?:_\d+|)$") -%}
    {%- set color.source=entity -%}
  {%- endif -%}
{%- endfor -%} {%- set brightness = state_attr(color.source, "brightness")|int / 255 -%} {%- set red=(state_attr(color.source, "rgb_color")[0] * brightness)|int -%} {%- set green=(state_attr(color.source, "rgb_color")[1] * brightness)|int -%} {%- set blue=(state_attr(color.source, "rgb_color")[2] * brightness)|int -%} {{ (red|bitwise_and(248)*256) + (green|bitwise_and(252)*8) + (blue|bitwise_and(248)/8)|int }}' but no default was specified
2022-06-24 10:09:21 WARNING (SyncWorker_0) [pycec] Not initialized. Waiting for init.
```

**Comment by koying** [comment]
Keep in mind OSMC has > 60 patches over Kodi: https://github.com/osmc/osmc/tree/master/package/mediacenter-osmc/patches
It might be worth for the OP to test with a plain Kodi, and open an issue on the OSMC side if it actually works.

**Comment by marcelveldt** [comment]
You can see the issue clearly in your log. The player connects multiple times

**Comment by marcelveldt** [comment]
> Keep in mind OSMC has > 60 patches over Kodi: https://github.com/osmc/osmc/tree/master/package/mediacenter-osmc/patches It might be worth for the OP to test with a plain Kodi, and open an issue on the OSMC side if it actually works.

That is indeed a good suggestion. I have been testing with a plain Kodi install on my Mac.

**Comment by OliPassey** [comment]
> Keep in mind OSMC has > 60 patches over Kodi: https://github.com/osmc/osmc/tree/master/package/mediacenter-osmc/patches It might be worth for the OP to test with a plain Kodi, and open an issue on the OSMC side if it actually works.

This is stock kodi, not OSMC

**Comment by koying** [comment]
You might want to exchange your Kodi versions as well ;)

**Comment by marcelveldt** [comment]
Ah yes, now I remember you being a part of Kodi devs and your fork SPMC!
I have a history in the "Kodi world" too years ago haha with a lot of helper add-ons and Skins.

I will check my version

**Comment by marcelveldt** [comment]
`2022-06-22 19:55:22.890 T:18388296    INFO <general>: Starting Kodi (19.4 (19.4.0) Git:20220302-e12e66e019). Platform: macOS x86 64-bit
2022-06-22 19:55:22.890 T:18388296    INFO <general>: Using Release Kodi x64
2022-06-22 19:55:22.890 T:18388296    INFO <general>: Kodi compiled 2022-03-03 by Clang 10.0.1 (clang-1001.0.46.4) for macOS x86 64-bit version 10.13 (101300)
2022-06-22 19:55:22.890 T:18388296    INFO <general>: Running on Apple Inc. MacBookPro16,2 with macOS 12.4 (Version 12.4 (Build 21F79)), kernel: Darwin x86 64-bit version 21.5.0
2022-06-22 19:55:22.890 T:18388296    INFO <general>: FFmpeg version/source: 4.3.2-Kodi`

**Comment by koying** [comment]
Doesn't work form me, either.

This is likely relevant

```
2022-06-24 13:28:17.922 T:15082   DEBUG <general>: CCurlFile::Open - File <http://192.168.3.244:8095/3e07dc52d8524db19b029cdf99c02937.flac> is a shoutcast stream. Re-opening
```

**Comment by marcelveldt** [comment]
This is the behavior I observed with Kodi clients:
head request
head request
get request without icy metadata header
get request without icy metadata header
get request with icy metadata header

The client "sticks" at the last request and keeps playing but this all happens within 2 seconds so it's all very time sensitive.

Music Assistant want to start the stream once the client is connected (or multiple clients if multiple should receive the stream). The existing behavior (that works with all players except Kodi) is that it starts streaming audio chunks once the client is connected (GET request). In the HEAD request only the contenttype is shared.

Kodi tries to probe the file to receive additional details it is not going to get.
It should have read the headers telling it is content-type "audio-flac" and the fact that there's a chunked header tells Kodi not to do any range requests (which it does).
I'm assuming here Kodi wants to know more (duration perhaps?) and tries to fetch the file once to grab those details.

Once it actually gets through all hurdles and is playing, it plays amazingly well and even display what is playing thanks to the ICY metadata.

I don't know if this probing thingie is something only happening once. If so I could create a special static endpoint for the Kodi clients instead of the current randomly generate stream url (to invalidate any cache).
Another option is to be even more forgiving on the number of requests and timeout.

Big problem here is I can't differentiate between a misbehaving client and Kodi.
I don't want to delay the start of chunks streaming too much as it ill delay the entire experience. Imagine you have to wait seconds when you're seeking in a file etc.

**Comment by marcelveldt** [comment]
The machine I'm testing with is local on my dev machine together with MA so very low latency. Maybe I should also test the additional latency of a Kodi client connected over the network

**Comment by marcelveldt** [comment]
> That's actually because ICY was added ;)

Yeah, I added it while I was fighting the Kodi issue. It was fun to do ;-)

**Comment by koying** [comment]
> so very low latency

On my lan, there is ~1sec between the first call and Kodi actually trying to play the stream

**Comment by marcelveldt** [comment]
Oh well that is a lot. 

What I also find strange is that we seem to hit the case where the old stream was not disconnected yet and the new request already came in:
https://github.com/music-assistant/music-assistant-lib/blob/master/music_assistant/controllers/streams.py#L378

Do you by any change know/remember if Kodi does the probing once for each file/url or at every request ?

**Comment by koying** [comment]
If it doesn't come from library (as is the case here), it will probe each time, as far as I remember.

**Comment by marcelveldt** [comment]
OK, thanks. So creating a static URL for the Kodi players makes no sense then.

I'm going to try one last workaround and that is to disconnect the previous session and accept a new incoming one when I receive duplicate requests from the same IP. Now it just throws an exception there causing Kodi to even retry more. Now I'll just feed the chunks that are ready for that client (I keep the previous chunk in memory)

**Comment by marcelveldt** [comment]
OK, fingers crossed, last workaround implemented. I'm not happy with it but can live with it ;-)
For real I think the issue should be fixed in Kodi itself but if this workaround works its fine.

2022.6.6 just released with my final attempt to workaround the reconnecting Kodi player.

Please let me know if it works for you.

BTW: Do not expect fast response times. With all the reconnecting the Kodi player is really slow to respond on a new stream. If it is streaming, it works flawless and including metadata.

**Comment by OliPassey** [comment]
Working here!

Thanks so much for your work here!

**Comment by jeroenterheerdt** [comment]
it works just fine over here as well! thanks a lot!

**Comment by marcelveldt** [comment]
Great!

**Comment by da-anda** [comment]
@marcelveldt I'm still a KODI team member (not a dev though) and could forward the issue at hand of nobody else has by now. If I got it right, the main issue is that KODI does way too many requests to the URL even though the initial HEAD request indicated that this might not be possible. Is this somewhat correct?
