### ISSUE TITLE
Selecting "Hide source players in the Home Assistant UI." does not hide existing media players

### ISSUE THREAD

**Issue by toby-griffiths** [music-assistant/hass-music-assistant#370]
Thanks for all the hard work on this.  I have a few bugs with this initial release, so hoping these reports help provide you with useful feedback.

I have 3 Sonos speakers that I've added to Music Assistant, as well as a Chromecast Audio.  The all appear as entities with the `mass_` prefix in their Id, however even though I selected the "Hide source players in the Home Assistant UI." option, I am now seeing 2 of each speaker in HA.

How can I help diagnose this problem?  I cannot find any logs for Music Assistant within my HA logs section.

Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

**Comment by erkr** [comment]
Thanks for reporting!

**Comment by erkr** [comment]
Hi, which version are you on? In beta 7 this was not working. But the latest works fine for me.
But don't forget to go through the configuration flow and enable hiding in the last page

**Comment by marcelveldt** [comment]
Fix available in 2022.6.1

**Comment by erkr** [comment]
@toby-griffiths ; can you confirm it is solved?

**Comment by toby-griffiths** [comment]
Wow!  That was quick!  Just restarted now, having upgraded but I'm sorry to say I'm still seeing my original media players.

If it helps, my 'speakers' consist of some Sonos speakers, a Chromecast Audio and a few helper groups for 'Upstairs' & 'Downstairs', all of which are still appearing.

I have tried toggling the setting and saving in between, but no joy, I'm afraid.  Sorry.

**Comment by marcelveldt** [comment]
Yeah, it won't pick up the change once you are already installed I'm afraid.
Thinking out loud it might be enough to simply remove one player, save the config and then add that player back in the Music Assistant config.

**Comment by erkr** [comment]
Toggling worked fine for me. Just as guess: not just toggle, but change,complete the configuration flow, enter again and change it back could work

**Comment by toby-griffiths** [comment]
It appears that they are hidden, although i realise now that it's possible that they were hidden before, as I was checking a dashboard that has them, and I realise now that hidden entities can appear on the dashboard.  But this is resolved for me.

As a side note … I was unable to remove entries from the list in the config. I had to change one for one I'd previously not included, complete the flow, then revert the change. But will raise a separate ticket for that.

**Comment by toby-griffiths** [comment]
Thank you for your help, btw.
