### ISSUE TITLE
Repeat not working

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#675]
### What version of Music Assistant has the issue?

2022.7b7

### The problem

Repeat entire queue setting not working.
When the queue is finished, it doesn’t repeat.

### How to reproduce

These where the queue settings:
![2CA6C771-0525-447B-B497-A05475A65F98](https://user-images.githubusercontent.com/4363599/179293022-88a4bf0a-5c77-40b7-b634-817c8065d656.jpeg)

### Relevant log output

None

### What version of Home Assistant Core are your running

2022.7.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
fixed in beta9

**Comment by erkr** [comment]
Hi,
Not really fixed. Although the setting is to repeat the entire queue, it repeats the last track after the first run!

**Comment by marcelveldt** [comment]
Fix available in the 2022.7 release!
Please reopen (or create a new issue) if you still may experience issues. Thanks!
