### ISSUE TITLE
Radio stations already sorted by name

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#74]
Small feature request: The radio list retrieved from TuneIn is always sorted by name, and the menu option to sort by name can not be deselected either. I would like to add the option to select the original order as provided by TuneIn.
![image](https://user-images.githubusercontent.com/4363599/167272572-85c7f461-bb5e-41b0-84a9-484562ad8784.jpeg)
By the way, I'm impressed wrt the functional completeness of this new integration. You clearly polished it before releasing 👍

**Comment by marcelveldt** [comment]
Well, actually I've been working on this for 3 years now (not full time of course) and the backend is pretty feature complete.
I'm now focusing on the frontend and HA integration and some nice to have stuff like recommendations etc.

I never noticed Tune In actually having a sort order, I'll take a look.

**Comment by marcelveldt** [comment]
fixed in 1.0.9

**Comment by erkr** [comment]
Hi Marcel, 
Just installed v1.0.9 and it is not fixed for me.  Now both the radio and the playlists only have the sort by name option. 
In the previous version the playlist menu was offering at least 3 options for sorting
Best
Eric

**Comment by marcelveldt** [comment]
Sorry, something got messed up in the previous release. The fix is next release (1.0.10). I've just confirmed it's working.
Sort options for both radio and playlists are no longer visible (as only the default is available there). I think you mean playlist tracks which has 3 sort options.
