### ISSUE TITLE
DNLA Player not showing

### ISSUE THREAD

**Issue by Emmettfl** [music-assistant/hass-music-assistant#914]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

Hi,

I have a problem with Music Assistant not showing my media players. It only currently shows one. This had worked in the past but it stopped working at some stage.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/68098778/190606311-3473380a-56b6-46b0-806d-26359536f3f4.png">

Here's a list of some of my media players:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/68098778/190606580-f3c096c0-29d7-4210-8b0e-264874d8979d.png">

Thanks!

### How to reproduce

I tried uninstalling and reinstalling the Integration.

### Relevant log output

This error originated from a custom integration.

Logger: custom_components.mass
Source: custom_components/mass/__init__.py:182
Integration: Music Assistant (documentation, issues)
First occurred: 14 September 2022 at 13:07:03 (5 occurrences)
Last logged: 11:37:35

Unable to retrieve the internal URL from Home Assistant, this may cause issues resolving the correct internal stream ip. Please set a valid internal url in the Home Assistant configuration

### What version of Home Assistant Core are your running

2022.9.4

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux

**Comment by erkr** [comment]
Hi
Thanks for filling your issue. Not seeing the players maybe doesn't relate to the error in your log. So maybe two issues.

Not seeing the players often simply resolved by refreshing your browser cache 

The logging indicates that MA can't retrieve your internal ip. That one is used for streaming.
Most likely it's not configured. 

Best Eric

**Comment by Emmettfl** [comment]
@erkr thanks for your answer. I completely cleared my cache, uninstalled Music Assistant and reinstalled but it didn't solve the problem. Any other ideas?

**Comment by erkr** [comment]
Hi @Emmettfl 

You wrote it worked before, but the screenshot above shows many Alexa media players. Those players where never supported. 
I only see one DLNA player at the bottom. Is that the missing player?
If so, we have to look specifically what is changed there. Or did you have other players that worked?

Best Eric

**Comment by Emmettfl** [comment]
> Have you been through the steps here #709

I checked there. No luck

**Comment by Emmettfl** [comment]
> Hi @Emmettfl
> 
> You wrote it worked before, but the screenshot above shows many Alexa media players. Those players where never supported. I only see one DLNA player at the bottom. Is that the missing player? If so, we have to look specifically what is changed there. Or did you have other players that worked?
> 
> Best Eric
![image](https://user-images.githubusercontent.com/68098778/190669511-ee70c817-ca42-461b-93f0-18b3d022d458.png)

That was only the top of the list. I didnt actually realise the alexa devices didnt work before. I dont really use them to listen to music.

**Comment by erkr** [comment]
MA doesn't show players that are known to be incompatible, like the Alexa players. 
In the readme the compatible players are listed:

- Google Cast players
- Slimproto Squeezebox players
- Sonos
- Linkplay
- Bose Soundtouch
- All players supporting DLNA

I guess most players in your list are not compatible. 
Latest versions on MA don't show the incompatibele players any more!
You mentioned:
> This had worked in the past but it stopped working at some stage

So could you please indicate which player that was working in MA before, is missing now?

If you refer an old MA version, it is possible more players where available, but those doesn't work!

**Comment by OzGav** [comment]
So what happened when you did the test Eric described in situation 1 here https://github.com/music-assistant/hass-music-assistant/discussions/622

**Comment by Emmettfl** [comment]
> MA doesn't show players that are known to be incompatible, like the Alexa players. In the readme the compatible players are listed:
> 
> * Google Cast players
> * Slimproto Squeezebox players
> * Sonos
> * Linkplay
> * Bose Soundtouch
> * All players supporting DLNA
> 
> I guess most players in your list are not compatible. Latest versions on MA don't show the incompatibele players any more! You mentioned:
> 
> > This had worked in the past but it stopped working at some stage
> 
> So could you please indicate which player that was working in MA before, is missing now?
> 
> If you refer an really older MA version, it is possible more players where available, but those never worked!
> 
> Best Eric

Hi Eric,

the player I use mostly is the soundbar which I can currently use in Home Assisstant with spotify:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/68098778/190849344-eb3f9572-1770-4e25-b89e-b424084fec88.png">

<img width="710" alt="image" src="https://user-images.githubusercontent.com/68098778/190849428-4a543475-1586-4dc5-9ea2-d8f3496b7075.png">

**Comment by erkr** [comment]
Hi

The soundbar looks like a DLNA player, and therefore should be available MA.

In order to allow @marcelveldt to look into that, it would like help if you share the soundbar player entity properties. You can easily look then up in de development tools.
Should look similar to this:
``` 
device_class: speaker
friendly_name: Woonkamer
supported_features: 456639
is_volume_muted: false
media_content_type: music
media_position: 0
media_position_updated_at: '2022-09-15T13:48:01.075405+00:00'
app_id: media_player.audio57woonkmr
app_name: Audio57WoonKmr
shuffle: false
repeat: false
active_child: media_player.mass_audio57woonkmr
```

**Comment by Emmettfl** [comment]
> Hi
> 
> The soundbar looks like a DLNA player, and therefore should be available MA.
> 
> In order to allow @marcelveldt to look into that, it would help if you share the soundbar player entity properties. You can easily look them up in de development tools. Should look similar to this:
> 
> ```
> device_class: speaker
> friendly_name: Woonkamer
> supported_features: 456639
> is_volume_muted: false
> media_content_type: music
> media_position: 0
> media_position_updated_at: '2022-09-15T13:48:01.075405+00:00'
> app_id: media_player.audio57woonkmr
> app_name: Audio57WoonKmr
> shuffle: false
> repeat: false
> active_child: media_player.mass_audio57woonkmr
> ```
> 
> Additionally we would like to know which integration provides that player to HA.
> 
> Best Eric

Hi Eric, is this what you need:

sound_mode_list:
  - FactoryDefaults
volume_level: 0.12
is_volume_muted: false
media_content_id: ''
media_duration: 0
media_track: 0
shuffle: false
repeat: 'off'
friendly_name: '[AV] Soundbar'
supported_features: 197132



![Screenshot_20220917-113953_Edge](https://user-images.githubusercontent.com/68098778/190850514-bcb891d0-23f7-47ea-9878-0f9c4c150dfb.jpg)

![Screenshot_20220917-114115_Edge](https://user-images.githubusercontent.com/68098778/190850575-74e86445-64bb-4348-8729-a8a620a22717.jpg)

**Comment by erkr** [comment]
Yes, that looks complete for now. Thanks!
@marcelveldt ; can you please shed your light on this issue

**Comment by marcelveldt** [comment]
Are you able to play some radio URL to this speaker ?
So the media_player.play_media service with an url as media_content_id

**Comment by Emmettfl** [comment]
Hi @marcelveldt I dont really understand how to do that. I created a new media source and installed radio browser. I can browse radio stations but when I choose to play on the soundbar nothing happens. I hope this helps.

![Screenshot_20220923-105504_Edge](https://user-images.githubusercontent.com/68098778/191926922-fd8e3050-9dee-4b45-a1c2-8315c87cbe38.jpg)
![Screenshot_20220923-105515_Edge](https://user-images.githubusercontent.com/68098778/191926940-41ec933e-ce74-47d9-a595-9d0413fd0c70.jpg)
![Screenshot_20220923-105522_Edge](https://user-images.githubusercontent.com/68098778/191926951-00037c23-4893-4c3a-8b72-bba12c31fff7.jpg)
![Screenshot_20220923-105529_Edge](https://user-images.githubusercontent.com/68098778/191926965-b984f509-dbc0-48a8-83f8-d4fb4fbfa225.jpg)

**Comment by OzGav** [comment]
If you can't stream a radio station to the soundbar then it sounds like it isn't supported. What can you play to it from HA?

**Comment by erkr** [comment]
Hi @Emmettfl 
Marcel was indeed referring the radio browser to test its an media url can be streamed. Alternatively that can be done using triggering the play media service under the developer tools. Some interactions are found here: https://github.com/music-assistant/hass-music-assistant/discussions/622

But reading your attempt, this specific DNLA player seems to lack support for streaming an URL. So not compatible.

As @OzGav asked earlier (you mentioned it was working in HA). How? 
Best Eric

**Comment by Emmettfl** [comment]
> Hi @Emmettfl Marcel was indeed referring the radio browser to test its an media url can be streamed. Alternatively that can be done using triggering the play media service under the developer tools. Some instructions are found here: #622
> 
> But reading your attempt, this specific DNLA player seems to lack support for streaming an URL. So not compatible.
> 
> As @OzGav asked earlier (you mentioned it was working in HA). How? Best Eric

Hi Eric,

Oddly enough I uninstall MA and reinstalled using a beta version and now the speaker is appearing. It just doesnt seem to do anything. Turning the speaker off or on in MA also doesn't appear to do anything. The speaker must just be not properly compatible.

![image](https://user-images.githubusercontent.com/68098778/192092032-13d86de5-47f3-4e18-8421-09c76acfe22d.png)

**Comment by erkr** [comment]
Yes I guess so. I will close the issue for now. Thanks for reporting

**Comment by Emmettfl** [comment]
> Yes I guess so. I will close the issue for now. Thanks for reporting

Thanks!
