### ISSUE TITLE
Error setting up entry Music Assistant for mass

### ISSUE THREAD

**Issue by thenotoriousdrr** [music-assistant/hass-music-assistant#965]
### What version of Music Assistant has the issue?

2022.11.0

### The problem

Music Assistant is not able to start. This is the error that is displayed

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 119, in async_setup_entry
    f"with Home Assistant version {manifest['ha_version']} (or higher)."
KeyError: 'ha_version'

### How to reproduce

Update HA to latest version, same with Music Assistant

### Relevant log output

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:119
Integration: Music Assistant (documentation, issues)
First occurred: 2:26:34 PM (2 occurrences)
Last logged: 2:32:27 PM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 119, in async_setup_entry
    f"with Home Assistant version {manifest['ha_version']} (or higher)."
KeyError: 'ha_version'

### What version of Home Assistant Core are your running

2022.10.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by gieljnssns** [comment]
This version is only for HA core 2022.11+

**Comment by thenotoriousdrr** [comment]
Good to know. I guess I'll just have to wait until next month then...

**Comment by kksligh** [comment]
I updated this as well and now it's impossible to revert back to the older version without this error.

**Comment by marcelveldt** [comment]
I'll repeat here what I just posted on discord

![Scherm­afbeelding 2022-10-28 om 00 45 23](https://user-images.githubusercontent.com/6389780/198411909-f6763c17-7c64-4bdc-bea8-0544ef1f0168.png)

**Comment by kksligh** [comment]
restoring a backup doesnt work either.

**Comment by OzGav** [comment]
You will have to upgrade to the HA beta then or wait five days until HA 2022.11 comes out

**Comment by thenotoriousdrr** [comment]
Thanks @OzGav. I'll wait the few days. No biggie. Thanks to all the folks contributing to HA.

**Comment by marcelveldt** [comment]
> restoring a backup doesnt work either.

It should if you restore a full backup that also restores all dependencies (python packages) to its original state.
Issue lies in a python dependency (sqlalchemy) which is bumped in HA 2022.11 for which we released MA version 2022.11 as patch.

**Comment by JayJay-SmartHome** [comment]
How do we roll back if needed to

**Comment by kksligh** [comment]
> > restoring a backup doesnt work either.
> 
> 
> 
> It should if you restore a full backup that also restores all dependencies (python packages) to its original state.
> 
> Issue lies in a python dependency (sqlalchemy) which is bumped in HA 2022.11 for which we released MA version 2022.11 as patch. 

- [ ] I'll just wait until next week but i had a build working and re-installed it completely while wiping the non working build and it still didn't work. No worries but it's odd that didn't fix the issue. I'm guessing theres deeper build reverting at a back end Python level that I don't know how to do

**Comment by Krzysztonek** [comment]
I'm facing a similar error in my case:

![image](https://user-images.githubusercontent.com/87784133/199266358-ac8d6d52-df0d-473a-b78e-81f5ef1b8d53.png)
 And here are the details of my HA version:

![image](https://user-images.githubusercontent.com/87784133/199266781-4af1010e-4754-4db1-b93b-d13a314fe9a5.png)

**Comment by LordNex** [comment]
> > > restoring a backup doesnt work either.
> > 
> > 
> > 
> > It should if you restore a full backup that also restores all dependencies (python packages) to its original state.
> > 
> > Issue lies in a python dependency (sqlalchemy) which is bumped in HA 2022.11 for which we released MA version 2022.11 as patch. 
> 
> - [ ] I'll just wait until next week but i had a build working and re-installed it completely while wiping the non working build and it still didn't work. No worries but it's odd that didn't fix the issue. I'm guessing theres deeper build reverting at a back end Python level that I don't know how to do 

I'm having the exact same issue. Mine auto updated before I could catch it (updates on a script) and it errored out. I restored to 8.4 and still received the error. I tried removing the addon and redownloading the source files through HACS and then reading the integration and I still get the following error. 

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mass/__init__.py:190 
Integration: Music Assistant (documentation, issues) 
First occurred: 2:53:01 AM (1 occurrences) 
Last logged: 2:53:01 AM

Error setting up entry Music Assistant for mass
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 197, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 190, in async_setup_entry
    await mass.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/mass.py", line 79, in setup
    await self.database.setup()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 43, in setup
    await self._migrate()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 186, in _migrate
    await self.__create_database_tables()
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 220, in __create_database_tables
    await self.execute(
  File "/usr/local/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 181, in execute
    return await self._db.execute(query, values)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 163, in execute
    return await connection.execute(query, values)
  File "/usr/local/lib/python3.10/site-packages/databases/core.py", line 274, in execute
    return await self._connection.execute(built_query)
  File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 131, in execute
    query_str, args, context = self._compile(query)
  File "/usr/local/lib/python3.10/site-packages/databases/backends/sqlite.py", line 188, in _compile
    compiled._ad_hoc_textual,
AttributeError: 'SQLiteCompiler' object has no attribute '_ad_hoc_textual'

```

Hopefully the new HA will drop soon and fix the issue as I'm anxious to try out these new Muze Lux speakers with SqueezeLite

**Comment by scottgerring** [comment]
I'm getting an error setting up on HA2022.11 / MA 2022.11 that seems to be also related to SQLalchemy:

```


Logger: homeassistant.config_entries
Source: deps/lib/python3.10/site-packages/databases/backends/sqlite.py:120
First occurred: 12:36:44 PM (1 occurrences)
Last logged: 12:36:44 PM
Error setting up entry Music Assistant for mass

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mass/__init__.py", line 197, in async_setup_entry
    raise exc
  File "/config/custom_components/mass/__init__.py", line 190, in async_setup_entry
    await mass.setup()
  File "/config/deps/lib/python3.10/site-packages/music_assistant/mass.py", line 79, in setup
    await self.database.setup()
  File "/config/deps/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 43, in setup
    await self._migrate()
  File "/config/deps/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 216, in _migrate
    await self.set_setting("version", str(SCHEMA_VERSION))
  File "/config/deps/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 60, in set_setting
    return await self.insert(
  File "/config/deps/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 137, in insert
    return await self.get_row(table, lookup_vals)
  File "/config/deps/lib/python3.10/site-packages/music_assistant/controllers/database.py", line 115, in get_row
    return await self._db.fetch_one(sql_query, match)
  File "/config/deps/lib/python3.10/site-packages/databases/core.py", line 148, in fetch_one
    return await connection.fetch_one(query, values)
  File "/config/deps/lib/python3.10/site-packages/databases/core.py", line 257, in fetch_one
    return await self._connection.fetch_one(built_query)
  File "/config/deps/lib/python3.10/site-packages/databases/backends/sqlite.py", line 120, in fetch_one
    metadata = CursorResultMetaData(context, cursor.description)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 164, in __init__
    (
ValueError: not enough values to unpack (expected 5, got 4)
```
