### ISSUE TITLE
Config flow could not be loaded: undefined

### ISSUE THREAD

**Issue by antonyslater** [music-assistant/hass-music-assistant#97]
Having installed the Music Assistant I get no errors on installation and it finds numerous devices and entities...  However, I am unable to adjust the configuration without removing and reinstalling as I get the following error message:

Error
Config flow could not be loaded: undefined

Any help would be gratefully received.

**Comment by marcelveldt** [comment]
Hmmm, do you spot the full error in your log perhaps ?

**Comment by antonyslater** [comment]
OK, I've restarted HomeAssistant and I now get an error, might be linked...

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:96
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:04:21 (14 occurrences)
Last logged: 13:04:21

[140602177126560] Received invalid command: mass/subscribe

**Comment by marcelveldt** [comment]
Nope, thats a so called "race condition". The frontend of MA tries to connect to the backend just before its loaded.
Happens when you restart HA with the MA panel open

**Comment by marcelveldt** [comment]
I have just published version 1.0.12 to HACS can you have a look if that resolves your issue ?

**Comment by antonyslater** [comment]
Updated to the latest version and restarted HA - no change
Removed and reinstalled Music Assistant, restarted HA - no change

Sorry! :-(

**Comment by marcelveldt** [comment]
Strange, what do you see when you open the full log file in HA ?
In the settings menu where you can view the log, there's a button below to view the full file.

**Comment by antonyslater** [comment]
These are the only entries I get this time referencing MASS I'm afraid... Down from 14 instances of the ERROR now only 2 but you already advised what they were.

2022-05-09 12:15:41 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration mass which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-05-09 12:16:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140146199946384] Received invalid command: mass/subscribe
2022-05-09 12:16:05 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140146199946384] Received invalid command: mass/subscribe

**Comment by antonyslater** [comment]
Interestingly however my favourite in InTune DOES now appear in the browser.

That said I may have another issue as it fails to play on any Alexa device saying "Sorry TTS can only be called with the notify.alexa_media service please see the alexa_media wiki for details."

**Comment by marcelveldt** [comment]
Yeah, playback is a different story... I'm working on that right now.
Track progress here: https://github.com/music-assistant/hass-music-assistant/issues/72

In short I need to implement a workaround for each mediaplayer platform.
So far working:

- slimproto (squeezebox players)
- kodi
- chromecast
- apple tv (not generic airplay devices)

**Comment by antonyslater** [comment]
No probs, will leave both issues with you for a time, but I must say kudos to you for the prompt replies, very much appreciated! :-)

**Comment by marcelveldt** [comment]
Well, you shouldn't have to remove and reinstall to make configuration changes in the first place ;-)
That said, you can edit the file "/config/.storage/config_entries" --> look for the music assistant config entry

Be aware that you treat that file with care or you loose access to your HA instance

**Comment by antonyslater** [comment]
> 

Touché, that wasn't a "dig" though... just wanting to keep trying stuff with it, really excited to see this fully working!

**Comment by antonyslater** [comment]
Today is the first time I've tried to use Music Assistant, so I've not had any previous versions installed prior to today...

**Background**
I run Home Assistant in Docker on a Synology NAS with 6gb RAM, HACS installed for community repositories.  I am running version 2022.3.5 presently.

**Procedure to arrive here**
1) Downloaded the Music Assistant repository from HACS
2) Restarted HA
3) Installed Music Assistant through Configuration->Integrations->Add Integration
4) Ticked use InTune and added InTune userID
5) Tried adding home server too first time, obviously wrong path so failed to add
6) Tried again with ONLY InTune and it worked showing me the entities it had found etc
All the while the Configuration button has not worked.

**Comment by marcelveldt** [comment]
I think I know what is going on... The local files music provider currently only supports a local path (e.g. /music)
Maybe the configure only breaks if you enter some invalid path ?

**Comment by marcelveldt** [comment]
You don't have to download any files manually, Just use HACS and that will do that for you.

**Comment by antonyslater** [comment]
> I think I know what is going on... The local files music provider currently only supports a local path (e.g. /music) Maybe the configure only breaks if you enter some invalid path ?


Here is my current config:
            {
                "entry_id": "768a62948a4e650f132edbba70eab728",
                "version": 1,
                "domain": "mass",
                "title": "Music Assistant",
                "data": {},
                "options": {
                    "spotify_enabled": false,
                    "qobuz_enabled": false,
                    "tunein_enabled": true,
                    "filesystem_enabled": false,
                    "tunein_username": "sl*****an",
                    "filesystem_directory": ""
                },
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
            },

**Comment by antonyslater** [comment]
> You don't have to download any files manually, Just use HACS and that will do that for you.

Which is how I did it... Was just a though??

**Comment by marcelveldt** [comment]
OK, so you're all set.
So, with the config you have now (without local folders) you still can not use the configure button?
Very strange! Are you on Home Assistant 2022.5.x ?

Can you make a screenshot of the issue ?

Sorry for all the questions but I simply can't reproduce nor understand why it's happening to you.

Your local files collection should work if the files are accessible from the Home Assistant container (mounted).
At this time there's no support for remote folders like SMB or cloud drives.

**Comment by antonyslater** [comment]
Please, no apology necessary, I REALLY appreciate you taking the time to work through this with me.

I am using HA 2022.3.5 loaded in a docker container.
**Without** local folders I **can** use the Music Assistant to "cast" radio stations to my ChromeCast using InTune saved Radio Favourites. This was configured/set at the point I installed the integration.
The "CONFIGURE" button on the integration panel **does not** work for me.

Loaded integration panel
![image](https://user-images.githubusercontent.com/38159952/167437084-6b161521-526f-4925-acdd-405602c2b67b.png)

Error message received when I click on "CONFIGURE"
![image](https://user-images.githubusercontent.com/38159952/167438555-9bcb6c1c-2647-4724-942a-0fcf7c43519e.png)

Hope this helps, anything else please just shout.

**Comment by marcelveldt** [comment]
Uhm, I'm not sure if I'm compatible with HA versions below 2022.5 because this project has just launched last weekend so its really new. There's a very big chance that we simply have an incompatibility issue

**Comment by marcelveldt** [comment]
Your second screenshot is the proof that your local files are accessible from the Home Assistant container.
So if you use that path it should work. I guess: /media/Diskstation

**Comment by antonyslater** [comment]
UPDATE : I can confirm that following my upgrade to Home Assistant Core 2022.5.3 this evening that the "CONFIGURE" button does now work as intended in that I can set all my player entities, configure the sources and control the use of MUTE for power control.

Once again I can't thank you enough @marcelveldt for all your precious time today and patience with what turned out to be an issue at my end rather than yours.

**Comment by marcelveldt** [comment]
Great to hear that resolved it! Thank you for your patience testing my little pet project :-)
I will close this issue now because the initial issue is now resolved.
Please let me know if you find anything else!

**Comment by antonyslater** [comment]
No thanks necessary, this is exactly what the Home Assistant community should be about!  If I can be of ANY further help please do not hesitate to shout. :-)

**Comment by baj24** [comment]
I'm on 2022.5.3 and I'm still getting the same message "Config flow could not be loaded: undefined"

**Comment by marcelveldt** [comment]
> I'm on 2022.5.3 and I'm still getting the same message "Config flow could not be loaded: undefined"

please attach your homeassistant.log file here so I can have a look

**Comment by wasyl00** [comment]
Hello I too struggle with "Config flow could not be loaded: undefined" when trying to add Music assistant integration

Here is the log 

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 22:18:01 (3 occurrences)
Last logged: 22:18:08

Unable to install package music-assistant==1.4.3: Traceback (most recent call last): File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code exec(code, run_globals) File "/usr/local/lib/python3.9/site-packages/pip/__main__.py", line 29, in <module> from pip._internal.cli.main import main as _main File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 9, in <module> from pip._internal.cli.autocompletion import autocomplete File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py", line 10, in <module> from pip._internal.cli.main_parser import create_main_parser File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py", line 8, in <module> from pip._internal.cli import cmdoptions File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module> from pip._internal.cli.parser import ConfigOptionParser File "/usr/local/lib/python3.9/site-packages/pip/_internal/cli/parser.py", line 12, in <module> from pip._internal.configuration import Configuration, ConfigurationError File "/usr/local/lib/python3.9/site-packages/pip/_internal/configuration.py", line 26, in <module> from pip._internal.utils.logging import getLogger File "/usr/local/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 19, in <module> from pip._vendor.rich.logging import RichHandler File "/usr/local/lib/python3.9/site-packages/pip/_vendor/rich/logging.py", line 12, in <module> from .traceback import Traceback File "/usr/local/lib/python3.9/site-packages/pip/_vendor/rich/traceback.py", line 18, in <module> from .columns import Columns File "<frozen importlib._bootstrap>", line 1007, in _find_and_load File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 680, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 846, in exec_module File "<frozen importlib._bootstrap_external>", line 978, in get_code File "<frozen importlib._bootstrap_external>", line 647, in _compile_bytecode ValueError: bad marshal data (unknown type code)
